# Camada Silver

## Biblioteca e DF

In [1]:
#bibliotecas padroes
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
# para limpar
import ast
import re
import unicodedata

In [3]:
df_2023 = pd.read_csv('/content/state_of_data_2023.csv', low_memory=False)
df_2024 = pd.read_csv('/content/state_of_data_2024.csv', low_memory=False)
df_2025 = pd.read_csv('/content/state_of_data_2025.csv', low_memory=False)

## **2023**

### Entender a base

In [4]:
df_2023.head()

,"('P0', 'id')","('P1_a ', 'Idade')","('P1_a_1 ', 'Faixa idade')","('P1_b ', 'Genero')","('P1_c ', 'Cor/raca/etnia')","('P1_d ', 'PCD')","('P1_e ', 'experiencia_profissional_prejudicada')","('P1_e_1 ', 'Não acredito que minha experiência profissional seja afetada')","('P1_e_2 ', 'Experiencia prejudicada devido a minha Cor Raça Etnia')","('P1_e_3 ', 'Experiencia prejudicada devido a minha identidade de gênero')",...,"('P8_d_3 ', 'Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.')","('P8_d_4 ', 'Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).')","('P8_d_5 ', 'Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.')","('P8_d_6 ', 'Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.')","('P8_d_7 ', 'Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc.')","('P8_d_8 ', 'Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.')","('P8_d_9 ', 'Criando e dando manutenção em ETLs, DAGs e automações de pipelines de dados.')","('P8_d_10 ', 'Criando e gerenciando soluções de Feature Store e cultura de MLOps.')","('P8_d_11 ', 'Criando e mantendo a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)')","('P8_d_12 ', 'Treinando e aplicando LLM's para solucionar problemas de negócio.')"
0,001b2d1qtli8t9z7oqgdhj001b2d4i0g,31,30-34,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0026aa3fwd78u0026asg7456tfkjg2cs,30,30-34,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00r21rb9pusd1b0v7ew00r21rw3dy69w,37,35-39,Feminino,Amarela,Não,"Sim, acredito que a minha a experiência profis...",0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,00urm3jf2cek12w6ygue00urm3jzd17j,22,22-24,Masculino,Preta,Não,Não acredito que minha experiência profissiona...,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00v0az4g792svil00vn6y1kfm9hq8vy9,34,30-34,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
print('Dimensões da Dataset:')
print(f'Linhas: {df_2023.shape[0]}')
print(f'Colunas: {df_2023.shape[1]}')

Dimensões da Dataset:
Linhas: 5293
Colunas: 399

In [6]:
print('Informações Gerais:')
print(df_2023.info())

Informações Gerais:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5293 entries, 0 to 5292
Columns: 399 entries, ('P0', 'id') to ('P8_d_12 ', 'Treinando e aplicando LLM's para solucionar problemas de negócio.')
dtypes: float64(328), int64(2), object(69)
memory usage: 16.1+ MB
None

In [7]:
print('Estátistica Descritivas')
print(df_2023.describe())

Estátistica Descritivas
       ('P1_a ', 'Idade')  \
count         5293.000000
mean            31.997166
std              7.623498
min             18.000000
25%             27.000000
50%             30.000000
75%             36.000000
max             73.000000

       ('P1_e_1 ', 'Não acredito que minha experiência profissional seja afetada')  \
count                                        2719.000000
mean                                            0.542111
std                                             0.498315
min                                             0.000000
25%                                             0.000000
50%                                             1.000000
75%                                             1.000000
max                                             1.000000

       ('P1_e_2 ', 'Experiencia prejudicada devido a minha Cor Raça Etnia')  \
count                                        2719.000000
mean                                            0.202648
std                                             0.402046
min                                             0.000000
25%                                             0.000000
50%                                             0.000000
75%                                             0.000000
max                                             1.000000

       ('P1_e_3 ', 'Experiencia prejudicada devido a minha identidade de gênero')  \
count                                        2719.000000
mean                                            0.291284
std                                             0.454437
min                                             0.000000
25%                                             0.000000
50%                                             0.000000
75%                                             1.000000
max                                             1.000000

       ('P1_e_4 ', 'Experiencia prejudicada devido ao fato de ser PCD')  \
count                                        2719.000000
mean                                            0.024641
std                                             0.155058
min                                             0.000000
25%                                             0.000000
50%                                             0.000000
75%                                             0.000000
max                                             1.000000

       ('P1_f_1', 'Quantidade de oportunidades de emprego/vagas recebidas')  \
count                                        1245.000000
mean                                            0.389558
std                                             0.487846
min                                             0.000000
25%                                             0.000000
50%                                             0.000000
75%                                             1.000000
max                                             1.000000

       ('P1_f_2', 'Senioridade das vagas recebidas em relação à sua experiência')  \
count                                        1245.000000
mean                                            0.342972
std                                             0.474893
min                                             0.000000
25%                                             0.000000
50%                                             0.000000
75%                                             1.000000
max                                             1.000000

       ('P1_f_3', 'Aprovação em processos seletivos/entrevistas')  \
count                                        1245.000000
mean                                            0.413655
std                                             0.492686
min                                             0.000000
25%                                             0.000000
50%                                             0.000000
75%                                             1.000000
max                                             1.000000

       ('P1_f_4', 'Oportunidades de progressão de carreira')  \
count                                        1245.000000
mean                                            0.490763
std                                             0.500116
min                                             0.000000
25%                                             0.000000
50%                                             0.000000
75%                                             1.000000
max                                             1.000000

       ('P1_f_5', 'Velocidade de progressão de carreira')  ...  \
count                                        1245.000000   ...
mean                                            0.516466   ...
std                                             0.499930   ...
min                                             0.000000   ...
25%                                             0.000000   ...
50%                                             1.000000   ...
75%                                             1.000000   ...
max                                             1.000000   ...

       ('P8_d_3 ', 'Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.')  \
count                                         748.000000
mean                                            0.243316
std                                             0.429371
min                                             0.000000
25%                                             0.000000
50%                                             0.000000
75%                                             0.000000
max                                             1.000000

       ('P8_d_4 ', 'Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).')  \
count                                         748.000000
mean                                            0.315508
std                                             0.465029
min                                             0.000000
25%                                             0.000000
50%                                             0.000000
75%                                             1.000000
max                                             1.000000

       ('P8_d_5 ', 'Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.')  \
count                                         748.000000
mean                                            0.070856
std                                             0.256755
min                                             0.000000
25%                                             0.000000
50%                                             0.000000
75%                                             0.000000
max                                             1.000000

       ('P8_d_6 ', 'Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.')  \
count                                         748.000000
mean                                            0.093583
std                                             0.291442
min                                             0.000000
25%                                             0.000000
50%                                             0.000000
75%                                             0.000000
max                                             1.000000

       ('P8_d_7 ', 'Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc.')  \
count                                         748.000000
mean                                            0.045455
std                                             0.208438
min                                             0.000000
25%                                             0.000000
50%                                             0.000000
75%                                             0.000000
max                                             1.000000

       ('P8_d_8 ', 'Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.')  \
count                                         748.000000
mean                                            0.009358
std                                             0.096349
min                                             0.000000
25%                                             0.000000
50%                                             0.000000
75%                                             0.000000
max                                             1.000000

       ('P8_d_9 ', 'Criando e dando manutenção em ETLs, DAGs e automações de pipelines de dados.')  \
count                                         748.000000
mean                                            0.025401
std                                             0.157445
min                                             0.000000
25%                                             0.000000
50%                                             0.000000
75%                                             0.000000
max                                             1.000000

       ('P8_d_10 ', 'Criando e gerenciando soluções de Feature Store e cultura de MLOps.')  \
count                                         748.000000
mean                                            0.020053
std                                             0.140277
min                                             0.000000
25%                                             0.000000
50%                                             0.000000
75%                                             0.000000
max                                             1.000000

       ('P8_d_11 ', 'Criando e mantendo a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)')  \
count                                         748.000000
mean                                            0.024064
std                                             0.153351
min                                             0.000000
25%                                             0.000000
50%                                             0.000000
75%                                             0.000000
max                                             1.000000

       ('P8_d_12 ', 'Treinando e aplicando LLM's para solucionar problemas de negócio.')
count                                         748.000000
mean                                            0.048128
std                                             0.214181
min                                             0.000000
25%                                             0.000000
50%                                             0.000000
75%                                             0.000000
max                                             1.000000

[8 rows x 330 columns]

In [8]:
print(df_2023.duplicated().sum())

0

In [9]:
print(df_2023.isnull().sum())

('P0', 'id')                                                                                                                     0
('P1_a ', 'Idade')                                                                                                               0
('P1_a_1 ', 'Faixa idade')                                                                                                       0
('P1_b ', 'Genero')                                                                                                              0
('P1_c ', 'Cor/raca/etnia')                                                                                                      0
                                                                                                                              ...
('P8_d_8 ', 'Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.')             4545
('P8_d_9 ', 'Criando e dando manutenção em ETLs, DAGs e automações de pipelines de dados.')                                   4545
('P8_d_10 ', 'Criando e gerenciando soluções de Feature Store e cultura de MLOps.')                                           4545
('P8_d_11 ', 'Criando e mantendo a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)')    4545
('P8_d_12 ', 'Treinando e aplicando LLM's para solucionar problemas de negócio.')                                             4545
Length: 399, dtype: int64

In [10]:
df_2023.isnull().sum()

('P0', 'id')                                                                                                                     0
('P1_a ', 'Idade')                                                                                                               0
('P1_a_1 ', 'Faixa idade')                                                                                                       0
('P1_b ', 'Genero')                                                                                                              0
('P1_c ', 'Cor/raca/etnia')                                                                                                      0
                                                                                                                              ...
('P8_d_8 ', 'Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.')             4545
('P8_d_9 ', 'Criando e dando manutenção em ETLs, DAGs e automações de pipelines de dados.')                                   4545
('P8_d_10 ', 'Criando e gerenciando soluções de Feature Store e cultura de MLOps.')                                           4545
('P8_d_11 ', 'Criando e mantendo a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)')    4545
('P8_d_12 ', 'Treinando e aplicando LLM's para solucionar problemas de negócio.')                                             4545
Length: 399, dtype: int64

In [11]:
for i, coluna in enumerate(df_2023.columns):
    print(f'{i}. {coluna}')

0. ('P0', 'id')
1. ('P1_a ', 'Idade')
2. ('P1_a_1 ', 'Faixa idade')
3. ('P1_b ', 'Genero')
4. ('P1_c ', 'Cor/raca/etnia')
5. ('P1_d ', 'PCD')
6. ('P1_e ', 'experiencia_profissional_prejudicada')
7. ('P1_e_1 ', 'Não acredito que minha experiência profissional seja afetada')
8. ('P1_e_2 ', 'Experiencia prejudicada devido a minha Cor Raça Etnia')
9. ('P1_e_3 ', 'Experiencia prejudicada devido a minha identidade de gênero')
10. ('P1_e_4 ', 'Experiencia prejudicada devido ao fato de ser PCD')
11. ('P1_f ', 'aspectos_prejudicados')
12. ('P1_f_1', 'Quantidade de oportunidades de emprego/vagas recebidas')
13. ('P1_f_2', 'Senioridade das vagas recebidas em relação à sua experiência')
14. ('P1_f_3', 'Aprovação em processos seletivos/entrevistas')
15. ('P1_f_4', 'Oportunidades de progressão de carreira')
16. ('P1_f_5', 'Velocidade de progressão de carreira')
17. ('P1_f_6', 'Nível de cobrança no trabalho/Stress no trabalho')
18. ('P1_f_7', 'Atenção dada diante das minhas opiniões e ideias')
19. ('P1_f_8', 'Relação com outros membros da empresa, em momentos de trabalho')
20. ('P1_f_9', 'Relação com outros membros da empresa, em momentos de integração e outros momentos fora do trabalho')
21. ('P1_g ', 'vive_no_brasil')
22. ('P1_i ', 'Estado onde mora')
23. ('P1_i_1 ', 'uf onde mora')
24. ('P1_i_2 ', 'Regiao onde mora')
25. ('P1_j ', 'Mudou de Estado?')
26. ('P1_k ', 'Regiao de origem')
27. ('P1_l ', 'Nivel de Ensino')
28. ('P1_m ', 'Área de Formação')
29. ('P2_a ', 'Qual sua situação atual de trabalho?')
30. ('P2_b ', 'Setor')
31. ('P2_c ', 'Numero de Funcionarios')
32. ('P2_d ', 'Gestor?')
33. ('P2_e ', 'Cargo como Gestor')
34. ('P2_f ', 'Cargo Atual')
35. ('P2_g ', 'Nivel')
36. ('P2_h ', 'Faixa salarial')
37. ('P2_i ', 'Quanto tempo de experiência na área de dados você tem?')
38. ('P2_j ', 'Quanto tempo de experiência na área de TI/Engenharia de Software você teve antes de começar a trabalhar na área de dados?')
39. ('P2_k ', 'Você está satisfeito na sua empresa atual?')
40. ('P2_l ', 'Qual o principal motivo da sua insatisfação com a empresa atual?')
41. ('P2_l_1 ', 'Falta de oportunidade de crescimento no emprego atual')
42. ('P2_l_2 ', 'Salário atual não corresponde ao mercado')
43. ('P2_l_3 ', 'Não tenho uma boa relação com meu líder/gestor')
44. ('P2_l_4 ', 'Gostaria de trabalhar em em outra área de atuação')
45. ('P2_l_5 ', 'Gostaria de receber mais benefícios')
46. ('P2_l_6 ', 'O clima de trabalho/ambiente não é bom')
47. ('P2_l_7 ', 'Falta de maturidade analítica na empresa')
48. ('P2_m ', 'Você participou de entrevistas de emprego nos últimos 6 meses?')
49. ('P2_n ', 'Você pretende mudar de emprego nos próximos 6 meses?')
50. ('P2_o ', 'Quais os principais critérios que você leva em consideração no momento de decidir onde trabalhar?')
51. ('P2_o_1 ', 'Remuneração/Salário')
52. ('P2_o_2 ', 'Benefícios')
53. ('P2_o_3 ', 'Propósito do trabalho e da empresa')
54. ('P2_o_4 ', 'Flexibilidade de trabalho remoto')
55. ('P2_o_5 ', 'Ambiente e clima de trabalho')
56. ('P2_o_6 ', 'Oportunidade de aprendizado e trabalhar com referências na área')
57. ('P2_o_7 ', 'Plano de carreira e oportunidades de crescimento profissional')
58. ('P2_o_8 ', 'Maturidade da empresa em termos de tecnologia e dados')
59. ('P2_o_9 ', 'Qualidade dos gestores e líderes')
60. ('P2_o_10 ', 'Reputação que a empresa tem no mercado')
61. ('P2_q ', 'Empresa que trabaha passou por layoff em 2023')
62. ('P2_r ', 'Atualmente qual a sua forma de trabalho?')
63. ('P2_s ', 'Qual a forma de trabalho ideal para você?')
64. ('P2_t ', 'Caso sua empresa decida pelo modelo 100% presencial qual será sua atitude?')
65. ('P3_a ', 'Qual o número aproximado de pessoas que atuam com dados na sua empresa hoje?')
66. ('P3_b ', 'Quais desses papéis/cargos fazem parte do time (ou chapter) de dados da sua empresa?')
67. ('P3_b_1 ', 'Analytics Engineer')
68. ('P3_b_2 ', 'Engenharia de Dados/Data Engineer')
69. ('P3_b_3 ', 'Analista de Dados/Data Analyst')
70. ('P3_b_4 ', 'Cientista de Dados/Data Scientist')
71. ('P3_b_5 ', 'Database Administrator/DBA')
72. ('P3_b_6 ', 'Analista de Business Intelligence/BI')
73. ('P3_b_7 ', 'Arquiteto de Dados/Data Architect')
74. ('P3_b_8 ', 'Data Product Manager/DPM')
75. ('P3_b_9 ', 'Business Analyst')
76. ('P3_c ', 'Quais dessas responsabilidades fazem parte da sua rotina atual de trabalho como gestor?')
77. ('P3_c_1 ', 'Pensar na visão de longo prazo de dados da empresa e fortalecimento da cultura analítica da companhia.')
78. ('P3_c_2 ', 'Organização de treinamentos e iniciativas com o objetivo de aumentar a maturidade analítica das áreas de negócios.')
79. ('P3_c_3 ', 'Atração, seleção e contratação de talentos para o time de dados.')
80. ('P3_c_4 ', 'Decisão sobre contratação de ferramentas e tecnologias relacionadas a dados.')
81. ('P3_c_5 ', 'Sou gestor da equipe responsável pela engenharia de dados e por manter o Data Lake da empresa como fonte única dos dados, garantindo a qualidade e confiabilidade da informação.')
82. ('P3_c_6 ', 'Sou gestor da equipe responsável pela entrega de dados, estudos, relatórios e dashboards para as áreas de negócio da empresa.')
83. ('P3_c_7 ', 'Sou gestor da equipe responsável por iniciativas e projetos envolvendo Inteligência Artificial e Machine Learning.')
84. ('P3_c_8 ', 'Apesar de ser gestor ainda atuo na parte técnica, construindo soluções/análises/modelos etc.')
85. ('P3_c_9 ', 'Gestão de projetos de dados, cuidando das etapas, equipes envolvidas, atingimento dos objetivos etc.')
86. ('P3_c_10 ', 'Gestão de produtos de dados, cuidando da visão dos produtos, backlog, feedback de usuários etc.')
87. ('P3_c_11 ', 'Gestão de pessoas, apoio no desenvolvimento das pessoas, evolução de carreira')
88. ('P3_d ', 'Quais são os 3 maiores desafios que você tem como gestor no atual momento?')
89. ('P3_d_1 ', 'a Contratar novos talentos.')
90. ('P3_d_2 ', 'b Reter talentos.')
91. ('P3_d_3 ', 'c Convencer a empresa a aumentar os investimentos na área de dados.')
92. ('P3_d_4 ', 'd Gestão de equipes no ambiente remoto.')
93. ('P3_d_5 ', 'e Gestão de projetos envolvendo áreas multidisciplinares da empresa.')
94. ('P3_d_6 ', 'f Organizar as informações e garantir a qualidade e confiabilidade.')
95. ('P3_d_7 ', 'g Conseguir processar e armazenar um alto volume de dados.')
96. ('P3_d_8 ', 'h Conseguir gerar valor para as áreas de negócios através de estudos e experimentos.')
97. ('P3_d_9 ', 'i Desenvolver e manter modelos Machine Learning em produção.')
98. ('P3_d_10 ', 'j Gerenciar a expectativa das áreas de negócio em relação as entregas das equipes de dados.')
99. ('P3_d_11 ', 'k Garantir a manutenção dos projetos e modelos em produção, em meio ao crescimento da empresa.')
100. ('P3_d_12 ', 'Conseguir levar inovação para a empresa através dos dados.')
101. ('P3_d_13 ', 'Garantir retorno do investimento (ROI) em projetos de dados.')
102. ('P3_d_14 ', 'Dividir o tempo entre entregas técnicas e gestão.')
103. ('P3_e ', 'AI Generativa é uma prioridade em sua empresa?')
104. ('P3_f ', 'Tipos de uso de AI Generativa e LLMs na empresa')
105. ('P3_f_1 ', 'Colaboradores usando AI generativa de forma independente e descentralizada')
106. ('P3_f_2 ', 'Direcionamento centralizado do uso de AI generativa')
107. ('P3_f_3 ', 'Desenvolvedores utilizando Copilots')
108. ('P3_f_4 ', 'AI Generativa e LLMs para melhorar produtos externos')
109. ('P3_f_5 ', 'AI Generativa e LLMs para melhorar produtos internos para os colaboradores')
110. ('P3_f_6 ', 'IA Generativa e LLMs como principal frente do negócio')
111. ('P3_f_7 ', 'IA Generativa e LLMs não é prioridade')
112. ('P3_f_8 ', 'Não sei opinar sobre o uso de IA Generativa e LLMs na empresa')
113. ('P3_g ', 'Motivos que levam a empresa a não usar AI Genrativa e LLMs')
114. ('P3_g_1 ', 'Falta de compreensão dos casos de uso')
115. ('P3_g_2 ', 'Falta de confiabilidade das saídas (alucinação dos modelos)')
116. ('P3_g_3 ', 'Incerteza em relação a regulamentação')
117. ('P3_g_4 ', 'Preocupações com segurança e privacidade de dados')
118. ('P3_g_5 ', 'Retorno sobre investimento (ROI) não comprovado de IA Generativa')
119. ('P3_g_6 ', 'Dados da empresa não estão prontos para uso de IA Generativa')
120. ('P3_g_7 ', 'Falta de expertise ou falta de recursos')
121. ('P3_g_8 ', 'Alta direção da empresa não vê valor ou não vê como prioridade')
122. ('P3_g_9 ', 'Preocupações com propriedade intelectual')
123. ('P4_a ', 'Mesmo que esse não seja seu cargo formal, você considera que sua atuação no dia a dia, reflete alguma das opções listadas abaixo?')
124. ('P4_a_1 ', 'Atuacao')
125. ('P4_b ', 'Quais das fontes de dados listadas você já analisou ou processou no trabalho?')
126. ('P4_b_1 ', 'Dados relacionais (estruturados em bancos SQL)')
127. ('P4_b_2 ', 'Dados armazenados em bancos NoSQL')
128. ('P4_b_3 ', 'Imagens')
129. ('P4_b_4 ', 'Textos/Documentos')
130. ('P4_b_5 ', 'Vídeos')
131. ('P4_b_6 ', 'Áudios')
132. ('P4_b_7 ', 'Planilhas')
133. ('P4_b_8 ', 'Dados georeferenciados')
134. ('P4_c ', 'Entre as fontes de dados listadas, quais você utiliza na maior parte do tempo?')
135. ('P4_c_1 ', 'Dados relacionais (estruturados em bancos SQL)')
136. ('P4_c_2 ', 'Dados armazenados em bancos NoSQL')
137. ('P4_c_3 ', 'Imagens')
138. ('P4_c_4 ', 'Textos/Documentos')
139. ('P4_c_5 ', 'Vídeos')
140. ('P4_c_6 ', 'Áudios')
141. ('P4_c_7 ', 'Planilhas')
142. ('P4_c_8 ', 'Dados georeferenciados')
143. ('P4_d ', 'Quais das linguagens listadas abaixo você utiliza no trabalho?')
144. ('P4_d_1 ', 'SQL')
145. ('P4_d_2 ', 'R ')
146. ('P4_d_3 ', 'Python')
147. ('P4_d_4 ', 'C/C++/C#')
148. ('P4_d_5 ', '.NET')
149. ('P4_d_6 ', 'Java')
150. ('P4_d_7 ', 'Julia')
151. ('P4_d_8 ', 'SAS/Stata')
152. ('P4_d_9 ', 'Visual Basic/VBA')
153. ('P4_d_10 ', 'Scala')
154. ('P4_d_11 ', 'Matlab')
155. ('P4_d_12 ', 'Rust')
156. ('P4_d_13 ', 'PHP')
157. ('P4_d_14 ', 'JavaScript')
158. ('P4_d_15 ', 'Não utilizo nenhuma linguagem')
159. ('P4_e ', 'Entre as linguagens listadas abaixo, qual é a que você mais utiliza no trabalho?')
160. ('P4_f ', 'Entre as linguagens listadas abaixo, qual é a sua preferida?')
161. ('P4_g ', 'Quais dos bancos de dados/fontes de dados listados abaixo você utiliza no trabalho?')
162. ('P4_g_1 ', 'MySQL')
163. ('P4_g_2 ', 'Oracle')
164. ('P4_g_3 ', 'SQL SERVER')
165. ('P4_g_4 ', 'Amazon Aurora ou RDS')
166. ('P4_g_5 ', 'DynamoDB')
167. ('P4_g_6 ', 'CoachDB')
168. ('P4_g_7 ', 'Cassandra')
169. ('P4_g_8 ', 'MongoDB')
170. ('P4_g_9 ', 'MariaDB')
171. ('P4_g_10 ', 'Datomic')
172. ('P4_g_11 ', 'S3')
173. ('P4_g_12 ', 'PostgreSQL')
174. ('P4_g_13 ', 'ElasticSearch')
175. ('P4_g_14 ', 'DB2')
176. ('P4_g_15 ', 'Microsoft Access')
177. ('P4_g_16 ', 'SQLite')
178. ('P4_g_17 ', 'Sybase')
179. ('P4_g_18 ', 'Firebase')
180. ('P4_g_19 ', 'Vertica')
181. ('P4_g_20 ', 'Redis')
182. ('P4_g_21 ', 'Neo4J')
183. ('P4_g_22 ', 'Google BigQuery')
184. ('P4_g_23 ', 'Google Firestore')
185. ('P4_g_24 ', 'Amazon Redshift')
186. ('P4_g_25 ', 'Amazon Athena')
187. ('P4_g_26 ', 'Snowflake')
188. ('P4_g_27 ', 'Databricks')
189. ('P4_g_28 ', 'HBase')
190. ('P4_g_29 ', 'Presto')
191. ('P4_g_30 ', 'Splunk')
192. ('P4_g_31 ', 'SAP HANA')
193. ('P4_g_32 ', 'Hive')
194. ('P4_g_33 ', 'Firebird')
195. ('P4_h ', 'Dentre as opções listadas, qual sua Cloud preferida?')
196. ('P4_h_1 ', 'Azure (Microsoft)')
197. ('P4_h_2 ', 'Amazon Web Services (AWS)')
198. ('P4_h_3 ', 'Google Cloud (GCP)')
199. ('P4_h_4 ', 'Oracle Cloud')
200. ('P4_h_5 ', 'IBM')
201. ('P4_h_6 ', 'Servidores On Premise/Não utilizamos Cloud')
202. ('P4_h_7 ', 'Cloud Própria')
203. ('P4_i ', 'Cloud preferida')
204. ('P4_j ', 'Ferramenta de BI utilizada no dia a dia')
205. ('P4_j_1 ', 'Microsoft PowerBI')
206. ('P4_j_2 ', 'Qlik View/Qlik Sense')
207. ('P4_j_3 ', 'Tableau')
208. ('P4_j_4 ', 'Metabase')
209. ('P4_j_5 ', 'Superset')
210. ('P4_j_6 ', 'Redash')
211. ('P4_j_7 ', 'Looker')
212. ('P4_j_8 ', 'Looker Studio(Google Data Studio)')
213. ('P4_j_9 ', 'Amazon Quicksight')
214. ('P4_j_10 ', 'Mode')
215. ('P4_j_11 ', 'Alteryx')
216. ('P4_j_12 ', 'MicroStrategy')
217. ('P4_j_13 ', 'IBM Analytics/Cognos')
218. ('P4_j_14 ', 'SAP Business Objects/SAP Analytics')
219. ('P4_j_15 ', 'Oracle Business Intelligence')
220. ('P4_j_16 ', 'Salesforce/Einstein Analytics')
221. ('P4_j_17 ', 'Birst')
222. ('P4_j_18 ', 'SAS Visual Analytics')
223. ('P4_j_19 ', 'Grafana')
224. ('P4_j_20 ', 'TIBCO Spotfire')
225. ('P4_j_21 ', 'Pentaho')
226. ('P4_j_22 ', 'Fazemos todas as análises utilizando apenas Excel ou planilhas do google')
227. ('P4_j_23 ', 'Não utilizo nenhuma ferramenta de BI no trabalho')
228. ('P4_k ', 'Qual sua ferramenta de BI preferida?')
229. ('P4_l ', 'Qual o tipo de uso de AI Generativa e LLMs na empresa')
230. ('P4_l_1 ', 'Colaboradores usando AI generativa de forma independente e descentralizada')
231. ('P4_l_2 ', 'Direcionamento centralizado do uso de AI generativa')
232. ('P4_l_3 ', 'Desenvolvedores utilizando Copilots')
233. ('P4_l_4 ', 'AI Generativa e LLMs para melhorar produtos externos para os clientes finais')
234. ('P4_l_5 ', 'AI Generativa e LLMs para melhorar produtos internos para os colaboradores')
235. ('P4_l_6 ', 'IA Generativa e LLMs como principal frente do negócio')
236. ('P4_l_7 ', 'IA Generativa e LLMs não é prioridade')
237. ('P4_l_8 ', 'Não sei opinar sobre o uso de IA Generativa e LLMs na empresa')
238. ('P4_m ', 'Utiliza ChatGPT ou LLMs no trabalho?')
239. ('P4_m_1 ', 'Não uso soluções de AI Generativa com foco em produtividade')
240. ('P4_m_2 ', 'Uso soluções gratuitas de AI Generativa com foco em produtividade')
241. ('P4_m_3 ', 'Uso e pago pelas soluções de AI Generativa com foco em produtividade')
242. ('P4_m_4 ', 'A empresa que trabalho paga pelas soluções de AI Generativa com foco em produtividade')
243. ('P4_m_5 ', 'Uso soluções do tipo Copilot')
244. ('P5_a ', 'Qual seu objetivo na área de dados?')
245. ('P5_b ', 'Qual oportunidade você está buscando?')
246. ('P5_c ', 'Há quanto tempo você busca uma oportunidade na área de dados?')
247. ('P5_d ', 'Como tem sido a busca por um emprego na área de dados?')
248. ('P6_a ', 'Quais das opções abaixo fazem parte da sua rotina no trabalho atual como engenheiro de dados?')
249. ('P6_a_1 ', 'Desenvolvo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.')
250. ('P6_a_2 ', 'Realizo construções de ETL's em ferramentas como Pentaho, Talend, Dataflow etc.')
251. ('P6_a_3 ', 'Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.')
252. ('P6_a_4 ', 'Atuo na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.')
253. ('P6_a_5 ', 'Modelo soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.')
254. ('P6_a_6 ', 'Desenvolvo/cuido da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.')
255. ('P6_a_7 ', 'Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts etc.')
256. ('P6_a_8 ', 'Cuido da qualidade dos dados, metadados e dicionário de dados.')
257. ('P6_a_9 ', 'Nenhuma das opções listadas refletem meu dia a dia.')
258. ('P6_b ', 'Quais as ferramentas/tecnologias de ETL que você utiliza no trabalho como Data Engineer?')
259. ('P6_b_1 ', 'Scripts Python')
260. ('P6_b_2 ', 'SQL & Stored Procedures')
261. ('P6_b_3 ', 'Apache Airflow')
262. ('P6_b_4 ', 'Apache NiFi')
263. ('P6_b_5 ', 'Luigi')
264. ('P6_b_6 ', 'AWS Glue')
265. ('P6_b_7 ', 'Talend')
266. ('P6_b_8 ', 'Pentaho')
267. ('P6_b_9 ', 'Alteryx')
268. ('P6_b_10 ', 'Stitch')
269. ('P6_b_11 ', 'Fivetran')
270. ('P6_b_12 ', 'Google Dataflow')
271. ('P6_b_13 ', 'Oracle Data Integrator')
272. ('P6_b_14 ', 'IBM DataStage')
273. ('P6_b_15 ', 'SAP BW ETL')
274. ('P6_b_16 ', 'SQL Server Integration Services (SSIS))
275. ('P6_b_17 ', 'SAS Data Integration')
276. ('P6_b_18 ', 'Qlik Sense')
277. ('P6_b_19 ', 'Knime')
278. ('P6_b_20 ', 'Databricks')
279. ('P6_b_21 ', 'Não utilizo ferramentas de ETL')
280. ('P6_c ', 'Sua organização possui um Data Lake?')
281. ('P6_d ', 'Qual tecnologia utilizada como plataforma do Data Lake?')
282. ('P6_e ', 'Sua organização possui um Data Warehouse?')
283. ('P6_f ', 'Qual tecnologia utilizada como plataforma do Data Warehouse?')
284. ('P6_g ', 'Quais as ferramentas de gestão de Qualidade de dados, Metadados e catálogo de dados você utiliza no trabalho?')
285. ('P6_h ', 'Em qual das opções abaixo você gasta a maior parte do seu tempo?')
286. ('P6_h_1 ', 'Desenvolvendo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.')
287. ('P6_h_2 ', 'Realizando construções de ETL's em ferramentas como Pentaho, Talend, Dataflow etc.')
288. ('P6_h_3 ', 'Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.')
289. ('P6_h_4 ', 'Atuando na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.')
290. ('P6_h_5 ', 'Modelando soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.')
291. ('P6_h_6 ', 'Desenvolvendo/cuidando da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.')
292. ('P6_h_7 ', 'Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts etc.')
293. ('P6_h_8 ', 'Cuidando da qualidade dos dados, metadados e dicionário de dados.')
294. ('P6_h_9 ', 'Nenhuma das opções listadas refletem meu dia a dia.')
295. ('P7_1 ', 'Quais das opções abaixo fazem parte da sua rotina no trabalho atual com análise de dados?')
296. ('P7_a_1 ', 'Processo e analiso dados utilizando linguagens de programação como Python, R etc.')
297. ('P7_a_2 ', 'Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.')
298. ('P7_a_3 ', 'Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.')
299. ('P7_a_4 ', 'Utilizo API's para extrair dados e complementar minhas análises.')
300. ('P7_a_5 ', 'Realizo experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.')
301. ('P7_a_6 ', 'Desenvolvo/cuido da manutenção de ETL's utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.')
302. ('P7_a_7 ', 'Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados, Data Warehouses, Data Marts etc.')
303. ('P7_a_8 ', 'Desenvolvo/cuido da manutenção de planilhas para atender as áreas de negócio.')
304. ('P7_a_9 ', 'Utilizo ferramentas avançadas de estatística como SASS, PSS, Stata etc')
305. ('P7_a_10 ', 'Nenhuma das opções listadas refletem meu dia a dia.')
306. ('P7_b ', 'Quais as ferramentas/tecnologias de ETL que você utiliza no trabalho como Data Analyst?')
307. ('P7_b_1 ', 'Scripts Python')
308. ('P7_b_2 ', 'SQL & Stored Procedures')
309. ('P7_b_3 ', 'Apache Airflow')
310. ('P7_b_4 ', 'Apache NiFi')
311. ('P7_b_5 ', 'Luigi')
312. ('P7_b_6 ', 'AWS Glue')
313. ('P7_b_7 ', 'Talend')
314. ('P7_b_8 ', 'Pentaho')
315. ('P7_b_9 ', 'Alteryx')
316. ('P7_b_10 ', 'Stitch')
317. ('P7_b_11 ', 'Fivetran')
318. ('P7_b_12 ', 'Google Dataflow')
319. ('P7_b_13 ', 'Oracle Data Integrator')
320. ('P7_b_14 ', 'IBM DataStage')
321. ('P7_b_15 ', 'SAP BW ETL')
322. ('P7_b_16 ', 'SQL Server Integration Services (SSIS)')
323. ('P7_b_17 ', 'SAS Data Integration')
324. ('P7_b_18 ', 'Qlik Sense')
325. ('P7_b_19 ', 'Knime')
326. ('P7_b_20 ', 'Databricks')
327. ('P7_b_21 ', 'Não utilizo ferramentas de ETL')
328. ('P7_c ', 'Sua empresa utiliza alguma das ferramentas listadas para dar mais autonomia em análise de dados para as áreas de negócio?')
329. ('P7_c_1 ', 'Ferramentas de AutoML como H2O.ai, Data Robot, BigML etc.')
330. ('P7_c_2 ', '""Point and Click"" Analytics como Alteryx, Knime, Rapidminer etc.')

In [12]:
print(df_2023.columns.tolist())

["('P0', 'id')", "('P1_a ', 'Idade')", "('P1_a_1 ', 'Faixa idade')", "('P1_b ', 'Genero')", "('P1_c ', 'Cor/raca/etnia')", "('P1_d ', 'PCD')", "('P1_e ', 'experiencia_profissional_prejudicada')", "('P1_e_1 ', 'Não acredito que minha experiência profissional seja afetada')", "('P1_e_2 ', 'Experiencia prejudicada devido a minha Cor Raça Etnia')", "('P1_e_3 ', 'Experiencia prejudicada devido a minha identidade de gênero')", "('P1_e_4 ', 'Experiencia prejudicada devido ao fato de ser PCD')", "('P1_f ', 'aspectos_prejudicados')", "('P1_f_1', 'Quantidade de oportunidades de emprego/vagas recebidas')", "('P1_f_2', 'Senioridade das vagas recebidas em relação à sua experiência')", "('P1_f_3', 'Aprovação em processos seletivos/entrevistas')", "('P1_f_4', 'Oportunidades de progressão de carreira')", "('P1_f_5', 'Velocidade de progressão de carreira')", "('P1_f_6', 'Nível de cobrança no trabalho/Stress no trabalho')", "('P1_f_7', 'Atenção dada diante das minhas opiniões e ideias')", "('P1_f_8', 'Relação com outros membros da empresa, em momentos de trabalho')", "('P1_f_9', 'Relação com outros membros da empresa, em momentos de integração e outros momentos fora do trabalho')", "('P1_g ', 'vive_no_brasil')", "('P1_i ', 'Estado onde mora')", "('P1_i_1 ', 'uf onde mora')", "('P1_i_2 ', 'Regiao onde mora')", "('P1_j ', 'Mudou de Estado?')", "('P1_k ', 'Regiao de origem')", "('P1_l ', 'Nivel de Ensino')", "('P1_m ', 'Área de Formação')", "('P2_a ', 'Qual sua situação atual de trabalho?')", "('P2_b ', 'Setor')", "('P2_c ', 'Numero de Funcionarios')", "('P2_d ', 'Gestor?')", "('P2_e ', 'Cargo como Gestor')", "('P2_f ', 'Cargo Atual')", "('P2_g ', 'Nivel')", "('P2_h ', 'Faixa salarial')", "('P2_i ', 'Quanto tempo de experiência na área de dados você tem?')", "('P2_j ', 'Quanto tempo de experiência na área de TI/Engenharia de Software você teve antes de começar a trabalhar na área de dados?')", "('P2_k ', 'Você está satisfeito na sua empresa atual?')", "('P2_l ', 'Qual o principal motivo da sua insatisfação com a empresa atual?')", "('P2_l_1 ', 'Falta de oportunidade de crescimento no emprego atual')", "('P2_l_2 ', 'Salário atual não corresponde ao mercado')", "('P2_l_3 ', 'Não tenho uma boa relação com meu líder/gestor')", "('P2_l_4 ', 'Gostaria de trabalhar em em outra área de atuação')", "('P2_l_5 ', 'Gostaria de receber mais benefícios')", "('P2_l_6 ', 'O clima de trabalho/ambiente não é bom')", "('P2_l_7 ', 'Falta de maturidade analítica na empresa')", "('P2_m ', 'Você participou de entrevistas de emprego nos últimos 6 meses?')", "('P2_n ', 'Você pretende mudar de emprego nos próximos 6 meses?')", "('P2_o ', 'Quais os principais critérios que você leva em consideração no momento de decidir onde trabalhar?')", "('P2_o_1 ', 'Remuneração/Salário')", "('P2_o_2 ', 'Benefícios')", "('P2_o_3 ', 'Propósito do trabalho e da empresa')", "('P2_o_4 ', 'Flexibilidade de trabalho remoto')", "('P2_o_5 ', 'Ambiente e clima de trabalho')", "('P2_o_6 ', 'Oportunidade de aprendizado e trabalhar com referências na área')", "('P2_o_7 ', 'Plano de carreira e oportunidades de crescimento profissional')", "('P2_o_8 ', 'Maturidade da empresa em termos de tecnologia e dados')", "('P2_o_9 ', 'Qualidade dos gestores e líderes')", "('P2_o_10 ', 'Reputação que a empresa tem no mercado')", "('P2_q ', 'Empresa que trabaha passou por layoff em 2023')", "('P2_r ', 'Atualmente qual a sua forma de trabalho?')", "('P2_s ', 'Qual a forma de trabalho ideal para você?')", "('P2_t ', 'Caso sua empresa decida pelo modelo 100% presencial qual será sua atitude?')", "('P3_a ', 'Qual o número aproximado de pessoas que atuam com dados na sua empresa hoje?')", "('P3_b ', 'Quais desses papéis/cargos fazem parte do time (ou chapter) de dados da sua empresa?')", "('P3_b_1 ', 'Analytics Engineer')", "('P3_b_2 ', 'Engenharia de Dados/Data Engineer')", "('P3_b_3 ', 'Analista de Dados/Data Analyst')", "('P3_b_4 ', 'Cientista de Dados/Data Scientist')", "('P3_b_5 ', 'Database Administrator/DBA')", "('P3_b_6 ', 'Analista de Business Intelligence/BI')", "('P3_b_7 ', 'Arquiteto de Dados/Data Architect')", "('P3_b_8 ', 'Data Product Manager/DPM')", "('P3_b_9 ', 'Business Analyst')", "('P3_c ', 'Quais dessas responsabilidades fazem parte da sua rotina atual de trabalho como gestor?')", "('P3_c_1 ', 'Pensar na visão de longo prazo de dados da empresa e fortalecimento da cultura analítica da companhia.')", "('P3_c_2 ', 'Organização de treinamentos e iniciativas com o objetivo de aumentar a maturidade analítica das áreas de negócios.')", "('P3_c_3 ', 'Atração, seleção e contratação de talentos para o time de dados.')", "('P3_c_4 ', 'Decisão sobre contratação de ferramentas e tecnologias relacionadas a dados.')", "('P3_c_5 ', 'Sou gestor da equipe responsável pela engenharia de dados e por manter o Data Lake da empresa como fonte única dos dados, garantindo a qualidade e confiabilidade da informação.')", "('P3_c_6 ', 'Sou gestor da equipe responsável pela entrega de dados, estudos, relatórios e dashboards para as áreas de negócio da empresa.')", "('P3_c_7 ', 'Sou gestor da equipe responsável por iniciativas e projetos envolvendo Inteligência Artificial e Machine Learning.')", "('P3_c_8 ', 'Apesar de ser gestor ainda atuo na parte técnica, construindo soluções/análises/modelos etc.')", "('P3_c_9 ', 'Gestão de projetos de dados, cuidando das etapas, equipes envolvidas, atingimento dos objetivos etc.')", "('P3_c_10 ', 'Gestão de produtos de dados, cuidando da visão dos produtos, backlog, feedback de usuários etc.')", "('P3_c_11 ', 'Gestão de pessoas, apoio no desenvolvimento das pessoas, evolução de carreira')", "('P3_d ', 'Quais são os 3 maiores desafios que você tem como gestor no atual momento?')", "('P3_d_1 ', 'a Contratar novos talentos.')", "('P3_d_2 ', 'b Reter talentos.')", "('P3_d_3 ', 'c Convencer a empresa a aumentar os investimentos na área de dados.')", "('P3_d_4 ', 'd Gestão de equipes no ambiente remoto.')", "('P3_d_5 ', 'e Gestão de projetos envolvendo áreas multidisciplinares da empresa.')", "('P3_d_6 ', 'f Organizar as informações e garantir a qualidade e confiabilidade.')", "('P3_d_7 ', 'g Conseguir processar e armazenar um alto volume de dados.')", "('P3_d_8 ', 'h Conseguir gerar valor para as áreas de negócios através de estudos e experimentos.')", "('P3_d_9 ', 'i Desenvolver e manter modelos Machine Learning em produção.')", "('P3_d_10 ', 'j Gerenciar a expectativa das áreas de negócio em relação as entregas das equipes de dados.')", "('P3_d_11 ', 'k Garantir a manutenção dos projetos e modelos em produção, em meio ao crescimento da empresa.')", "('P3_d_12 ', 'Conseguir levar inovação para a empresa através dos dados.')", "('P3_d_13 ', 'Garantir retorno do investimento (ROI) em projetos de dados.')", "('P3_d_14 ', 'Dividir o tempo entre entregas técnicas e gestão.')", "('P3_e ', 'AI Generativa é uma prioridade em sua empresa?')", "('P3_f ', 'Tipos de uso de AI Generativa e LLMs na empresa')", "('P3_f_1 ', 'Colaboradores usando AI generativa de forma independente e descentralizada')", "('P3_f_2 ', 'Direcionamento centralizado do uso de AI generativa')", "('P3_f_3 ', 'Desenvolvedores utilizando Copilots')", "('P3_f_4 ', 'AI Generativa e LLMs para melhorar produtos externos')", "('P3_f_5 ', 'AI Generativa e LLMs para melhorar produtos internos para os colaboradores')", "('P3_f_6 ', 'IA Generativa e LLMs como principal frente do negócio')", "('P3_f_7 ', 'IA Generativa e LLMs não é prioridade')", "('P3_f_8 ', 'Não sei opinar sobre o uso de IA Generativa e LLMs na empresa')", "('P3_g ', 'Motivos que levam a empresa a não usar AI Genrativa e LLMs')", "('P3_g_1 ', 'Falta de compreensão dos casos de uso')", "('P3_g_2 ', 'Falta de confiabilidade das saídas (alucinação dos modelos)')", "('P3_g_3 ', 'Incerteza em relação a regulamentação')", "('P3_g_4 ', 'Preocupações com segurança e privacidade de dados')", "('P3_g_5 ', 'Retorno sobre investimento (ROI) não comprovado de IA Generativa')", "('P3_g_6 ', 'Dados da empresa não estão prontos para uso de IA Generativa')", "('P3_g_7 ', 'Falta de expertise ou falta de recursos')", "('P3_g_8 ', 'Alta direção da empresa não vê valor ou não vê como prioridade')", "('P3_g_9 ', 'Preocupações com propriedade intelectual')", "('P4_a ', 'Mesmo que esse não seja seu cargo formal, você considera que sua atuação no dia a dia, reflete alguma das opções listadas abaixo?')", "('P4_a_1 ', 'Atuacao')", "('P4_b ', 'Quais das fontes de dados listadas você já analisou ou processou no trabalho?')", "('P4_b_1 ', 'Dados relacionais (estruturados em bancos SQL)')", "('P4_b_2 ', 'Dados armazenados em bancos NoSQL')", "('P4_b_3 ', 'Imagens')", "('P4_b_4 ', 'Textos/Documentos')", "('P4_b_5 ', 'Vídeos')", "('P4_b_6 ', 'Áudios')", "('P4_b_7 ', 'Planilhas')", "('P4_b_8 ', 'Dados georeferenciados')", "('P4_c ', 'Entre as fontes de dados listadas, quais você utiliza na maior parte do tempo?')", "('P4_c_1 ', 'Dados relacionais (estruturados em bancos SQL)')", "('P4_c_2 ', 'Dados armazenados em bancos NoSQL')", "('P4_c_3 ', 'Imagens')", "('P4_c_4 ', 'Textos/Documentos')", "('P4_c_5 ', 'Vídeos')", "('P4_c_6 ', 'Áudios')", "('P4_c_7 ', 'Planilhas')", "('P4_c_8 ', 'Dados georeferenciados')", "('P4_d ', 'Quais das linguagens listadas abaixo você utiliza no trabalho?')", "('P4_d_1 ', 'SQL')", "('P4_d_2 ', 'R ')", "('P4_d_3 ', 'Python')", "('P4_d_4 ', 'C/C++/C#')", "('P4_d_5 ', '.NET')", "('P4_d_6 ', 'Java')", "('P4_d_7 ', 'Julia')", "('P4_d_8 ', 'SAS/Stata')", "('P4_d_9 ', 'Visual Basic/VBA')", "('P4_d_10 ', 'Scala')", "('P4_d_11 ', 'Matlab')", "('P4_d_12 ', 'Rust')", "('P4_d_13 ', 'PHP')", "('P4_d_14 ', 'JavaScript')", "('P4_d_15 ', 'Não utilizo nenhuma linguagem')", "('P4_e ', 'Entre as linguagens listadas abaixo, qual é a que você mais utiliza no trabalho?')", "('P4_f ', 'Entre as linguagens listadas abaixo, qual é a sua preferida?')", "('P4_g ', 'Quais dos bancos de dados/fontes de dados listados abaixo você utiliza no trabalho?')", "('P4_g_1 ', 'MySQL')", "('P4_g_2 ', 'Oracle')", "('P4_g_3 ', 'SQL SERVER')", "('P4_g_4 ', 'Amazon Aurora ou RDS')", "('P4_g_5 ', 'DynamoDB')", "('P4_g_6 ', 'CoachDB')", "('P4_g_7 ', 'Cassandra')", "('P4_g_8 ', 'MongoDB')", "('P4_g_9 ', 'MariaDB')", "('P4_g_10 ', 'Datomic')", "('P4_g_11 ', 'S3')", "('P4_g_12 ', 'PostgreSQL')", "('P4_g_13 ', 'ElasticSearch')", "('P4_g_14 ', 'DB2')", "('P4_g_15 ', 'Microsoft Access')", "('P4_g_16 ', 'SQLite')", "('P4_g_17 ', 'Sybase')", "('P4_g_18 ', 'Firebase')", "('P4_g_19 ', 'Vertica')", "('P4_g_20 ', 'Redis')", "('P4_g_21 ', 'Neo4J')", "('P4_g_22 ', 'Google BigQuery')", "('P4_g_23 ', 'Google Firestore')", "('P4_g_24 ', 'Amazon Redshift')", "('P4_g_25 ', 'Amazon Athena')", "('P4_g_26 ', 'Snowflake')", "('P4_g_27 ', 'Databricks')", "('P4_g_28 ', 'HBase')", "('P4_g_29 ', 'Presto')", "('P4_g_30 ', 'Splunk')", "('P4_g_31 ', 'SAP HANA')", "('P4_g_32 ', 'Hive')", "('P4_g_33 ', 'Firebird')", "('P4_h ', 'Dentre as opções listadas, qual sua Cloud preferida?')", "('P4_h_1 ', 'Azure (Microsoft)')", "('P4_h_2 ', 'Amazon Web Services (AWS)')", "('P4_h_3 ', 'Google Cloud (GCP)')", "('P4_h_4 ', 'Oracle Cloud')", "('P4_h_5 ', 'IBM')", "('P4_h_6 ', 'Servidores On Premise/Não utilizamos Cloud')", "('P4_h_7 ', 'Cloud Própria')", "('P4_i ', 'Cloud preferida')", "('P4_j ', 'Ferramenta de BI utilizada no dia a dia')", "('P4_j_1 ', 'Microsoft PowerBI')", "('P4_j_2 ', 'Qlik View/Qlik Sense')", "('P4_j_3 ', 'Tableau')", "('P4_j_4 ', 'Metabase')", "('P4_j_5 ', 'Superset')", "('P4_j_6 ', 'Redash')", "('P4_j_7 ', 'Looker')", "('P4_j_8 ', 'Looker Studio(Google Data Studio)')", "('P4_j_9 ', 'Amazon Quicksight')", "('P4_j_10 ', 'Mode')", "('P4_j_11 ', 'Alteryx')", "('P4_j_12 ', 'MicroStrategy')", "('P4_j_13 ', 'IBM Analytics/Cognos')", "('P4_j_14 ', 'SAP Business Objects/SAP Analytics')", "('P4_j_15 ', 'Oracle Business Intelligence')", "('P4_j_16 ', 'Salesforce/Einstein Analytics')", "('P4_j_17 ', 'Birst')", "('P4_j_18 ', 'SAS Visual Analytics')", "('P4_j_19 ', 'Grafana')", "('P4_j_20 ', 'TIBCO Spotfire')", "('P4_j_21 ', 'Pentaho')", "('P4_j_22 ', 'Fazemos todas as análises utilizando apenas Excel ou planilhas do google')", "('P4_j_23 ', 'Não utilizo nenhuma ferramenta de BI no trabalho')", "('P4_k ', 'Qual sua ferramenta de BI preferida?')", "('P4_l ', 'Qual o tipo de uso de AI Generativa e LLMs na empresa')", "('P4_l_1 ', 'Colaboradores usando AI generativa de forma independente e descentralizada')", "('P4_l_2 ', 'Direcionamento centralizado do uso de AI generativa')", "('P4_l_3 ', 'Desenvolvedores utilizando Copilots')", "('P4_l_4 ', 'AI Generativa e LLMs para melhorar produtos externos para os clientes finais')", "('P4_l_5 ', 'AI Generativa e LLMs para melhorar produtos internos para os colaboradores')", "('P4_l_6 ', 'IA Generativa e LLMs como principal frente do negócio')", "('P4_l_7 ', 'IA Generativa e LLMs não é prioridade')", "('P4_l_8 ', 'Não sei opinar sobre o uso de IA Generativa e LLMs na empresa')", "('P4_m ', 'Utiliza ChatGPT ou LLMs no trabalho?')", "('P4_m_1 ', 'Não uso soluções de AI Generativa com foco em produtividade')", "('P4_m_2 ', 'Uso soluções gratuitas de AI Generativa com foco em produtividade')", "('P4_m_3 ', 'Uso e pago pelas soluções de AI Generativa com foco em produtividade')", "('P4_m_4 ', 'A empresa que trabalho paga pelas soluções de AI Generativa com foco em produtividade')", "('P4_m_5 ', 'Uso soluções do tipo Copilot')", "('P5_a ', 'Qual seu objetivo na área de dados?')", "('P5_b ', 'Qual oportunidade você está buscando?')", "('P5_c ', 'Há quanto tempo você busca uma oportunidade na área de dados?')", "('P5_d ', 'Como tem sido a busca por um emprego na área de dados?')", "('P6_a ', 'Quais das opções abaixo fazem parte da sua rotina no trabalho atual como engenheiro de dados?')", "('P6_a_1 ', 'Desenvolvo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.')", "('P6_a_2 ', 'Realizo construções de ETL's em ferramentas como Pentaho, Talend, Dataflow etc.')", "('P6_a_3 ', 'Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.')", "('P6_a_4 ', 'Atuo na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.')", "('P6_a_5 ', 'Modelo soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.')", "('P6_a_6 ', 'Desenvolvo/cuido da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.')", "('P6_a_7 ', 'Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts etc.')", "('P6_a_8 ', 'Cuido da qualidade dos dados, metadados e dicionário de dados.')", "('P6_a_9 ', 'Nenhuma das opções listadas refletem meu dia a dia.')", "('P6_b ', 'Quais as ferramentas/tecnologias de ETL que você utiliza no trabalho como Data Engineer?')", "('P6_b_1 ', 'Scripts Python')", "('P6_b_2 ', 'SQL & Stored Procedures')", "('P6_b_3 ', 'Apache Airflow')", "('P6_b_4 ', 'Apache NiFi')", "('P6_b_5 ', 'Luigi')", "('P6_b_6 ', 'AWS Glue')", "('P6_b_7 ', 'Talend')", "('P6_b_8 ', 'Pentaho')", "('P6_b_9 ', 'Alteryx')", "('P6_b_10 ', 'Stitch')", "('P6_b_11 ', 'Fivetran')", "('P6_b_12 ', 'Google Dataflow')", "('P6_b_13 ', 'Oracle Data Integrator')", "('P6_b_14 ', 'IBM DataStage')", "('P6_b_15 ', 'SAP BW ETL')", "('P6_b_16 ', 'SQL Server Integration Services (SSIS))", "('P6_b_17 ', 'SAS Data Integration')", "('P6_b_18 ', 'Qlik Sense')", "('P6_b_19 ', 'Knime')", "('P6_b_20 ', 'Databricks')", "('P6_b_21 ', 'Não utilizo ferramentas de ETL')", "('P6_c ', 'Sua organização possui um Data Lake?')", "('P6_d ', 'Qual tecnologia utilizada como plataforma do Data Lake?')", "('P6_e ', 'Sua organização possui um Data Warehouse?')", "('P6_f ', 'Qual tecnologia utilizada como plataforma do Data Warehouse?')", "('P6_g ', 'Quais as ferramentas de gestão de Qualidade de dados, Metadados e catálogo de dados você utiliza no trabalho?')", "('P6_h ', 'Em qual das opções abaixo você gasta a maior parte do seu tempo?')", "('P6_h_1 ', 'Desenvolvendo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.')", "('P6_h_2 ', 'Realizando construções de ETL's em ferramentas como Pentaho, Talend, Dataflow etc.')", "('P6_h_3 ', 'Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.')", "('P6_h_4 ', 'Atuando na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.')", "('P6_h_5 ', 'Modelando soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.')", "('P6_h_6 ', 'Desenvolvendo/cuidando da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.')", "('P6_h_7 ', 'Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts etc.')", "('P6_h_8 ', 'Cuidando da qualidade dos dados, metadados e dicionário de dados.')", "('P6_h_9 ', 'Nenhuma das opções listadas refletem meu dia a dia.')", "('P7_1 ', 'Quais das opções abaixo fazem parte da sua rotina no trabalho atual com análise de dados?')", "('P7_a_1 ', 'Processo e analiso dados utilizando linguagens de programação como Python, R etc.')", "('P7_a_2 ', 'Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.')", "('P7_a_3 ', 'Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.')", "('P7_a_4 ', 'Utilizo API's para extrair dados e complementar minhas análises.')", "('P7_a_5 ', 'Realizo experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.')", "('P7_a_6 ', 'Desenvolvo/cuido da manutenção de ETL's utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.')", "('P7_a_7 ', 'Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados, Data Warehouses, Data Marts etc.')", "('P7_a_8 ', 'Desenvolvo/cuido da manutenção de planilhas para atender as áreas de negócio.')", "('P7_a_9 ', 'Utilizo ferramentas avançadas de estatística como SASS, PSS, Stata etc')", "('P7_a_10 ', 'Nenhuma das opções listadas refletem meu dia a dia.')", "('P7_b ', 'Quais as ferramentas/tecnologias de ETL que você utiliza no trabalho como Data Analyst?')", "('P7_b_1 ', 'Scripts Python')", "('P7_b_2 ', 'SQL & Stored Procedures')", "('P7_b_3 ', 'Apache Airflow')", "('P7_b_4 ', 'Apache NiFi')", "('P7_b_5 ', 'Luigi')", "('P7_b_6 ', 'AWS Glue')", "('P7_b_7 ', 'Talend')", "('P7_b_8 ', 'Pentaho')", "('P7_b_9 ', 'Alteryx')", "('P7_b_10 ', 'Stitch')", "('P7_b_11 ', 'Fivetran')", "('P7_b_12 ', 'Google Dataflow')", "('P7_b_13 ', 'Oracle Data Integrator')", "('P7_b_14 ', 'IBM DataStage')", "('P7_b_15 ', 'SAP BW ETL')", "('P7_b_16 ', 'SQL Server Integration Services (SSIS)')", "('P7_b_17 ', 'SAS Data Integration')", "('P7_b_18 ', 'Qlik Sense')", "('P7_b_19 ', 'Knime')", "('P7_b_20 ', 'Databricks')", "('P7_b_21 ', 'Não utilizo ferramentas de ETL')", "('P7_c ', 'Sua empresa utiliza alguma das ferramentas listadas para dar mais autonomia em análise de dados para as áreas de negócio?')", "('P7_c_1 ', 'Ferramentas de AutoML como H2O.ai, Data Robot, BigML etc.')", '(\'P7_c_2 \', \'""Point and Click"" Analytics como Alteryx, Knime, Rapidminer etc.\')', "('P7_c_3 ', 'Product metricts & Insights como Mixpanel, Amplitude, Adobe Analytics.')", "('P7_c_4 ', 'Ferramentas de análise dentro de ferramentas de CRM como Salesforce Einstein Anaytics ou Zendesk dashboards.')", "('P7_c_5 ', 'Minha empresa não utiliza essas ferramentas.')", "('P7_c_6 ', 'Não sei informar.')", "('P7_d ', 'Em qual das opções abaixo você gasta a maior parte do seu tempo de trabalho?')", "('P7_d_1 ', 'Processando e analisando dados utilizando linguagens de programação como Python, R etc.')", "('P7_d_2 ', 'Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker,

In [13]:
df_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5293 entries, 0 to 5292
Columns: 399 entries, ('P0', 'id') to ('P8_d_12 ', 'Treinando e aplicando LLM's para solucionar problemas de negócio.')
dtypes: float64(328), int64(2), object(69)
memory usage: 16.1+ MB

In [14]:
print(df_2023.head(3).to_markdown())

|    | ('P0', 'id')                     |   ('P1_a ', 'Idade') | ('P1_a_1 ', 'Faixa idade')   | ('P1_b ', 'Genero')   | ('P1_c ', 'Cor/raca/etnia')   | ('P1_d ', 'PCD')   | ('P1_e ', 'experiencia_profissional_prejudicada')                                                     |   ('P1_e_1 ', 'Não acredito que minha experiência profissional seja afetada') |   ('P1_e_2 ', 'Experiencia prejudicada devido a minha Cor Raça Etnia') |   ('P1_e_3 ', 'Experiencia prejudicada devido a minha identidade de gênero') |   ('P1_e_4 ', 'Experiencia prejudicada devido ao fato de ser PCD') | ('P1_f ', 'aspectos_prejudicados')                                                                                                                                   |   ('P1_f_1', 'Quantidade de oportunidades de emprego/vagas recebidas') |   ('P1_f_2', 'Senioridade das vagas recebidas em relação à sua experiência') |   ('P1_f_3', 'Aprovação em processos seletivos/entrevistas') |   ('P1_f_4', 'Oportunidades de progressão de carreira') |   ('P1_f_5', 'Velocidade de progressão de carreira') |   ('P1_f_6', 'Nível de cobrança no trabalho/Stress no trabalho') |   ('P1_f_7', 'Atenção dada diante das minhas opiniões e ideias') |   ('P1_f_8', 'Relação com outros membros da empresa, em momentos de trabalho') |   ('P1_f_9', 'Relação com outros membros da empresa, em momentos de integração e outros momentos fora do trabalho') |   ('P1_g ', 'vive_no_brasil') | ('P1_i ', 'Estado onde mora')   | ('P1_i_1 ', 'uf onde mora')   | ('P1_i_2 ', 'Regiao onde mora')   |   ('P1_j ', 'Mudou de Estado?') |   ('P1_k ', 'Regiao de origem') | ('P1_l ', 'Nivel de Ensino')   | ('P1_m ', 'Área de Formação')                                    | ('P2_a ', 'Qual sua situação atual de trabalho?')   | ('P2_b ', 'Setor')   | ('P2_c ', 'Numero de Funcionarios')   |   ('P2_d ', 'Gestor?') |   ('P2_e ', 'Cargo como Gestor') | ('P2_f ', 'Cargo Atual')          | ('P2_g ', 'Nivel')   | ('P2_h ', 'Faixa salarial')      | ('P2_i ', 'Quanto tempo de experiência na área de dados você tem?')   | ('P2_j ', 'Quanto tempo de experiência na área de TI/Engenharia de Software você teve antes de começar a trabalhar na área de dados?')   |   ('P2_k ', 'Você está satisfeito na sua empresa atual?') | ('P2_l ', 'Qual o principal motivo da sua insatisfação com a empresa atual?')   |   ('P2_l_1 ', 'Falta de oportunidade de crescimento no emprego atual') |   ('P2_l_2 ', 'Salário atual não corresponde ao mercado') |   ('P2_l_3 ', 'Não tenho uma boa relação com meu líder/gestor') |   ('P2_l_4 ', 'Gostaria de trabalhar em em outra área de atuação') |   ('P2_l_5 ', 'Gostaria de receber mais benefícios') |   ('P2_l_6 ', 'O clima de trabalho/ambiente não é bom') |   ('P2_l_7 ', 'Falta de maturidade analítica na empresa') | ('P2_m ', 'Você participou de entrevistas de emprego nos últimos 6 meses?')      | ('P2_n ', 'Você pretende mudar de emprego nos próximos 6 meses?')   | ('P2_o ', 'Quais os principais critérios que você leva em consideração no momento de decidir onde trabalhar?')         |   ('P2_o_1 ', 'Remuneração/Salário') |   ('P2_o_2 ', 'Benefícios') |   ('P2_o_3 ', 'Propósito do trabalho e da empresa') |   ('P2_o_4 ', 'Flexibilidade de trabalho remoto') |   ('P2_o_5 ', 'Ambiente e clima de trabalho') |   ('P2_o_6 ', 'Oportunidade de aprendizado e trabalhar com referências na área') |   ('P2_o_7 ', 'Plano de carreira e oportunidades de crescimento profissional') |   ('P2_o_8 ', 'Maturidade da empresa em termos de tecnologia e dados') |   ('P2_o_9 ', 'Qualidade dos gestores e líderes') |   ('P2_o_10 ', 'Reputação que a empresa tem no mercado') | ('P2_q ', 'Empresa que trabaha passou por layoff em 2023')                               | ('P2_r ', 'Atualmente qual a sua forma de trabalho?')                                                          | ('P2_s ', 'Qual a forma de trabalho ideal para você?')   | ('P2_t ', 'Caso sua empresa decida pelo modelo 100% presencial qual será sua atitude?')   |   ('P3_a ', 'Qual o número aproximado de pessoas que atuam com dados na sua empresa hoje?') |   ('P3_b ', 'Quais desses papéis/cargos fazem parte do time (ou chapter) de dados da sua empresa?') |   ('P3_b_1 ', 'Analytics Engineer') |   ('P3_b_2 ', 'Engenharia de Dados/Data Engineer') |   ('P3_b_3 ', 'Analista de Dados/Data Analyst') |   ('P3_b_4 ', 'Cientista de Dados/Data Scientist') |   ('P3_b_5 ', 'Database Administrator/DBA') |   ('P3_b_6 ', 'Analista de Business Intelligence/BI') |   ('P3_b_7 ', 'Arquiteto de Dados/Data Architect') |   ('P3_b_8 ', 'Data Product Manager/DPM') |   ('P3_b_9 ', 'Business Analyst') |   ('P3_c ', 'Quais dessas responsabilidades fazem parte da sua rotina atual de trabalho como gestor?') |   ('P3_c_1 ', 'Pensar na visão de longo prazo de dados da empresa e fortalecimento da cultura analítica da companhia.') |   ('P3_c_2 ', 'Organização de treinamentos e iniciativas com o objetivo de aumentar a maturidade analítica das áreas de negócios.') |   ('P3_c_3 ', 'Atração, seleção e contratação de talentos para o time de dados.') |   ('P3_c_4 ', 'Decisão sobre contratação de ferramentas e tecnologias relacionadas a dados.') |   ('P3_c_5 ', 'Sou gestor da equipe responsável pela engenharia de dados e por manter o Data Lake da empresa como fonte única dos dados, garantindo a qualidade e confiabilidade da informação.') |   ('P3_c_6 ', 'Sou gestor da equipe responsável pela entrega de dados, estudos, relatórios e dashboards para as áreas de negócio da empresa.') |   ('P3_c_7 ', 'Sou gestor da equipe responsável por iniciativas e projetos envolvendo Inteligência Artificial e Machine Learning.') |   ('P3_c_8 ', 'Apesar de ser gestor ainda atuo na parte técnica, construindo soluções/análises/modelos etc.') |   ('P3_c_9 ', 'Gestão de projetos de dados, cuidando das etapas, equipes envolvidas, atingimento dos objetivos etc.') |   ('P3_c_10 ', 'Gestão de produtos de dados, cuidando da visão dos produtos, backlog, feedback de usuários etc.') |   ('P3_c_11 ', 'Gestão de pessoas, apoio no desenvolvimento das pessoas, evolução de carreira') |   ('P3_d ', 'Quais são os 3 maiores desafios que você tem como gestor no atual momento?') |   ('P3_d_1 ', 'a Contratar novos talentos.') |   ('P3_d_2 ', 'b Reter talentos.') |   ('P3_d_3 ', 'c Convencer a empresa a aumentar os investimentos na área de dados.') |   ('P3_d_4 ', 'd Gestão de equipes no ambiente remoto.') |   ('P3_d_5 ', 'e Gestão de projetos envolvendo áreas multidisciplinares da empresa.') |   ('P3_d_6 ', 'f Organizar as informações e garantir a qualidade e confiabilidade.') |   ('P3_d_7 ', 'g Conseguir processar e armazenar um alto volume de dados.') |   ('P3_d_8 ', 'h Conseguir gerar valor para as áreas de negócios através de estudos e experimentos.') |   ('P3_d_9 ', 'i Desenvolver e manter modelos Machine Learning em produção.') |   ('P3_d_10 ', 'j Gerenciar a expectativa das áreas de negócio em relação as entregas das equipes de dados.') |   ('P3_d_11 ', 'k Garantir a manutenção dos projetos e modelos em produção, em meio ao crescimento da empresa.') |   ('P3_d_12 ', 'Conseguir levar inovação para a empresa através dos dados.') |   ('P3_d_13 ', 'Garantir retorno do investimento (ROI) em projetos de dados.') |   ('P3_d_14 ', 'Dividir o tempo entre entregas técnicas e gestão.') |   ('P3_e ', 'AI Generativa é uma prioridade em sua empresa?') |   ('P3_f ', 'Tipos de uso de AI Generativa e LLMs na empresa') |   ('P3_f_1 ', 'Colaboradores usando AI generativa de forma independente e descentralizada') |   ('P3_f_2 ', 'Direcionamento centralizado do uso de AI generativa') |   ('P3_f_3 ', 'Desenvolvedores utilizando Copilots') |   ('P3_f_4 ', 'AI Generativa e LLMs para melhorar produtos externos') |   ('P3_f_5 ', 'AI Generativa e LLMs para melhorar produtos internos para os colaboradores') |   ('P3_f_6 ', 'IA Generativa e LLMs como principal frente do negócio') |   ('P3_f_7 ', 'IA Generativa e LLMs não é prioridade') |   ('P3_f_8 ', 'Não sei opinar sobre o uso de IA Generativa e LLMs na empresa') |   ('P3_g ', 'Motivos que levam a empresa a não usar AI Genrativa e LLMs') |   ('P3_g_1 ', 'Falta de compreensão dos casos de uso') |   ('P3_g_2 ', 'Falta de confiabilidade das saídas (alucinação dos modelos)') |   ('P3_g_3 ', 'Incerteza em relação a regulamentação') |   ('P3_g_4 ', 'Preocupações com segurança e privacidade de dados') |   ('P3_g_5 ', 'Retorno sobre investimento (ROI) não comprovado de IA Generativa') |   ('P3_g_6 ', 'Dados da empresa não estão prontos para uso de IA Generativa') |   ('P3_g_7 ', 'Falta de expertise ou falta de recursos') |   ('P3_g_8 ', 'Alta direção da empresa não vê valor ou não vê como prioridade') |   ('P3_g_9 ', 'Preocupações com propriedade intelectual') | ('P4_a ', 'Mesmo que esse não seja seu cargo formal, você considera que sua atuação no dia a dia, reflete alguma das opções listadas abaixo?')                                                                                                        | ('P4_a_1 ', 'Atuacao')   | ('P4_b ', 'Quais das fontes de dados listadas você já analisou ou processou no trabalho?')                                                      |   ('P4_b_1 ', 'Dados relacionais (estruturados em bancos SQL)') |   ('P4_b_2 ', 'Dados armazenados em bancos NoSQL') |   ('P4_b_3 ', 'Imagens') |   ('P4_b_4 ', 'Textos/Documentos') |   ('P4_b_5 ', 'Vídeos') |   ('P4_b_6 ', 'Áudios') |   ('P4_b_7 ', 'Planilhas') |   ('P4_b_8 ', 'Dados georeferenciados') | ('P4_c ', 'Entre as fontes de dados listadas, quais você utiliza na maior parte do tempo?')   |   ('P4_c_1 ', 'Dados relacionais (estruturados em bancos SQL)') |   ('P4_c_2 ', 'Dados armazenados em bancos NoSQL') |   ('P4_c_3 ', 'Imagens') |   ('P4_c_4 ', 'Textos/Documentos') |   ('P4_c_5 ', 'Vídeos') |   ('P4_c_6 ', 'Áudios') |   ('P4_c_7 ', 'Planilhas') |   ('P4_c_8 ', 'Dados georeferenciados') | ('P4_d ', 'Quais das linguagens listadas abaixo você utiliza no trabalho?')   |   ('P4_d_1 ', 'SQL') |   ('P4_d_2 ', 'R ') |   ('P4_d_3 ', 'Python') |   ('P4_d_4 ', 'C/C++/C#') |   ('P4_d_5 ', '.NET') |   ('P4_d_6 ', 'Java') |   ('P4_d_7 ', 'Julia') |   ('P4_d_8 ', 'SAS/Stata') |   ('P4_d_9 ', 'Visual Basic/VBA') |   ('P4_d_10 ', 'Scala') |   ('P4_d_11 ', 'Matlab') |   ('P4_d_12 ', 'Rust') |   ('P4_d_13 ', 'PHP') |   ('P4_d_14 ', 'JavaScript') |   ('P4_d_15 ', 'Não utilizo nenhuma linguagem') | ('P4_e ', 'Entre as linguagens listadas abaixo, qual é a que você mais utiliza no trabalho?')   | ('P4_f ', 'Entre as linguagens listadas abaixo, qual é a sua preferida?')   | ('P4_g ', 'Quais dos bancos de dados/fontes de dados listados abaixo você utiliza no trabalho?')   |   ('P4_g_1 ', 'MySQL') |   ('P4_g_2 ', 'Oracle') |   ('P4_g_3 ', 'SQL SERVER') |   ('P4_g_4 ', 'Amazon Aurora ou RDS') |   ('P4_g_5 ', 'DynamoDB') |   ('P4_g_6 ', 'CoachDB') |   ('P4_g_7 ', 'Cassandra') |   ('P4_g_8 ', 'MongoDB') |   ('P4_g_9 ', 'MariaDB') |   ('P4_g_10 ', 'Datomic') |   ('P4_g_11 ', 'S3') |   ('P4_g_12 ', 'PostgreSQL') |   ('P4_g_13 ', 'ElasticSearch') |   ('P4_g_14 ', 'DB2') |   ('P4_g_15 ', 'Microsoft Access') |   ('P4_g_16 ', 'SQLite') |   ('P4_g_17 ', 'Sybase') |   ('P4_g_18 ', 'Firebase') |   ('P4_g_19 ', 'Vertica') |   ('P4_g_20 ', 'Redis') |   ('P4_g_21 ', 'Neo4J') |   ('P4_g_22 ', 'Google BigQuery') |   ('P4_g_23 ', 'Google Firestore') |   ('P4_g_24 ', 'Amazon Redshift') |   ('P4_g_25 ', 'Amazon Athena') |   ('P4_g_26 ', 'Snowflake') |   ('P4_g_27 ', 'Databricks') |   ('P4_g_28 ', 'HBase') |   ('P4_g_29 ', 'Presto') |   ('P4_g_30 ', 'Splunk') |   ('P4_g_31 ', 'SAP HANA') |   ('P4_g_32 ', 'Hive') |   ('P4_g_33 ', 'Firebird') | ('P4_h ', 'Dentre as opções listadas, qual sua Cloud preferida?')   |   ('P4_h_1 ', 'Azure (Microsoft)') |   ('P4_h_2 ', 'Amazon Web Services (AWS)') |   ('P4_h_3 ', 'Google Cloud (GCP)') |   ('P4_h_4 ', 'Oracle Cloud') |   ('P4_h_5 ', 'IBM') |   ('P4_h_6 ', 'Servidores On Premise/Não utilizamos Cloud') |   ('P4_h_7 ', 'Cloud Própria') | ('P4_i ', 'Cloud preferida')   | ('P4_j ', 'Ferramenta de BI utilizada no dia a dia')                                                                                                            |   ('P4_j_1 ', 'Microsoft PowerBI') |   ('P4_j_2 ', 'Qlik View/Qlik Sense') |   ('P4_j_3 ', 'Tableau') |   ('P4_j_4 ', 'Metabase') |   ('P4_j_5 ', 'Superset') |   ('P4_j_6 ', 'Redash') |   ('P4_j_7 ', 'Looker') |   ('P4_j_8 ', 'Looker Studio(Google Data Studio)') |   ('P4_j_9 ', 'Amazon Quicksight') |   ('P4_j_10 ', 'Mode') |   ('P4_j_11 ', 'Alteryx') |   ('P4_j_12 ', 'MicroStrategy') |   ('P4_j_13 ', 'IBM Analytics/Cognos') |   ('P4_j_14 ', 'SAP Business Objects/SAP Analytics') |   ('P4_j_15 ', 'Oracle Business Intelligence') |   ('P4_j_16 ', 'Salesforce/Einstein Analytics') |   ('P4_j_17 ', 'Birst') |   ('P4_j_18 ', 'SAS Visual Analytics') |   ('P4_j_19 ', 'Grafana') |   ('P4_j_20 ', 'TIBCO Spotfire') |   ('P4_j_21 ', 'Pentaho') |   ('P4_j_22 ', 'Fazemos todas as análises utilizando apenas Excel ou planilhas do google') |   ('P4_j_23 ', 'Não utilizo nenhuma ferramenta de BI no trabalho') | ('P4_k ', 'Qual sua ferramenta de BI preferida?')   | ('P4_l ', 'Qual o tipo de uso de AI Generativa e LLMs na empresa')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |   ('P4_l_1 ', 'Colaboradores usando AI generativa de forma independente e descentralizada') |   ('P4_l_2 ', 'Direcionamento centralizado do uso de AI generativa') |   ('P4_l_3 ', 'Desenvolvedores utilizando Copilots') |   ('P4_l_4 ', 'AI Generativa e LLMs para melhorar produtos externos para os clientes finais') |   ('P4_l_5 ', 'AI Generativa e LLMs para melhorar produtos internos para os colaboradores') |   ('P4_l_6 ', 'IA Generativa e LLMs como principal frente do negócio') |   ('P4_l_7 ', 'IA Generativa e LLMs não é prioridade') |   ('P4_l_8 ', 'Não sei opinar sobre o uso de IA Generativa e LLMs na empresa') | ('P4_m ', 'Utiliza ChatGPT ou LLMs no trabalho?')                                                                    |   ('P4_m_1 ', 'Não uso soluções de AI Generativa com foco em produtividade') |   ('P4_m_2 ', 'Uso soluções gratuitas de AI Generativa com foco em produtividade') |   ('P4_m_3 ', 'Uso e pago pelas soluções de AI Generativa com foco em produtividade') |   ('P4_m_4 ', 'A empresa que trabalho paga pelas soluções de AI Generativa com foco em produtividade') |   ('P4_m_5 ', 'Uso soluções do tipo Copilot') |   ('P5_a ', 'Qual seu objetivo na área de dados?') |   ('P5_b ', 'Qual oportunidade você está buscando?') |   ('P5_c ', 'Há quanto tempo você busca uma oportunidade na área de dados?') |   ('P5_d ', 'Como tem sido a busca por um emprego na área de dados?') |   ('P6_a ', 'Quais das opções abaixo fazem parte da sua rotina no trabalho atual como engenheiro de dados?') |   ('P6_a_1 ', 'Desenvolvo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.') |   ('P6_a_2 ', 'Realizo construções de ETL's em ferramentas como Pentaho, Talend, Dataflow etc.') |   ('P6_a_3 ', 'Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.') |   ('P6_a_4 ', 'Atuo na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.') |   ('P6_a_5 ', 'Modelo soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.') |   ('P6_a_6 ', 'Desenvolvo/cuido da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.') |   ('P6_a_7 ', 'Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts etc.') |   ('P6_a_8 ', 'Cuido da qualidade dos dados, metadados e dicionário de dados.') |   ('P6_a_9 ', 'Nenhuma das opções listadas refletem meu dia a dia.') |   ('P6_b ', 'Quais as ferramentas/tecnologias de ETL que você utiliza no trabalho como Data Engineer?') |   ('P6_b_1 ', 'Scripts Python') |   ('P6_b_2 ', 'SQL & Stored Procedures') |   ('P6_b_3 ', 'Apache Airflow') |   ('P6_b_4 ', 'Apache NiFi') |   ('P6_b_5 ', 'Luigi') |   ('P6_b_6 ', 'AWS Glue') |   ('P6_b_7 ', 'Talend') |   ('P6_b_8 ', 'Pentaho') |   ('P6_b_9 ', 'Alteryx') |   ('P6_b_10 ', 'Stitch') |   ('P6_b_11 ', 'Fivetran') |   ('P6_b_12 ', 'Google Dataflow') |   ('P6_b_13 ', 'Oracle Data Integrator') |   ('P6_b_14 ', 'IBM DataStage') |   ('P6_b_15 ', 'SAP BW ETL') |   ('P6_b_16 ', 'SQL Server Integration Services (SSIS)) |   ('P6_b_17 ', 'SAS Data Integration') |   ('P6_b_18 ', 'Qlik Sense') |   ('P6_b_19 ', 'Knime') |   ('P6_b_20 ', 'Databricks') |   ('P6_b_21 ', 'Não utilizo ferramentas de ETL') |   ('P6_c ', 'Sua organização possui um Data Lake?') |   ('P6_d ', 'Qual tecnologia utilizada como plataforma do Data Lake?') |   ('P6_e ', 'Sua organização possui um Data Warehouse?') |   ('P6_f ', 'Qual tecnologia utilizada como plataforma do Data Warehouse?') |   ('P6_g ', 'Quais as ferramentas de gestão de Qualidade de dados, Metadados e catálogo de dados você utiliza no trabalho?') |   ('P6_h ', 'Em qual das opções abaixo você gasta a maior parte do seu tempo?') |   ('P6_h_1 ', 'Desenvolvendo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.') |   ('P6_h_2 ', 'Realizando construções de ETL's em ferramentas como Pentaho, Talend, Dataflow etc.') |   ('P6_h_3 ', 'Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.') |   ('P6_h_4 ', 'Atuando na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.') |   ('P6_h_5 ', 'Modelando soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.') |   ('P6_h_6 ', 'Desenvolvendo/cuidando da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.') |   ('P6_h_7 ', 'Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts etc.') |   ('P6_h_8 ', 'Cuidando da qualidade dos dados, metadados e dicionário de dados.') |   ('P6_h_9 ', 'Nenhuma das opções listadas refletem meu dia a dia.') | ('P7_1 ', 'Quais das opções abaixo fazem parte da sua rotina no trabalho atual com análise de dados?')                                                                                       |   ('P7_a_1 ', 'Processo e analiso dados utilizando linguagens de programação como Python, R etc.') |   ('P7_a_2 ', 'Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.') |   ('P7_a_3 ', 'Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.') |   ('P7_a_4 ', 'Utilizo API's para extrair dados e complementar minhas análises.') |   ('P7_a_5 ', 'Realizo experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.') |   ('P7_a_6 ', 'Desenvolvo/cuido da manutenção de ETL's utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.') |   ('P7_a_7 ', 'Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados, Data Warehouses, Data Marts etc.') |   ('P7_a_8 ', 'Desenvolvo/cuido da manutenção de planilhas para atender as áreas de negócio.') |   ('P7_a_9 ', 'Utilizo ferramentas avançadas de esta

### Limpandon a base

In [15]:
def limpar_nome_coluna_v2(col):
    col_str = str(col).strip()

    # 1. Se já for uma tupla real do Python, pega o segundo elemento
    if isinstance(col, tuple) and len(col) >= 2:
        nome = col[1]

    # 2. Se for uma string que parece tupla malformada: "('cod', 'texto com apóstrofo's')"
    elif col_str.startswith("('") or col_str.startswith('("'):
        if "', '" in col_str:
            # Separa na primeira ocorrência de "', '" e pega a segunda parte, removendo o final "')"
            nome = col_str.split("', '", 1)[1].rstrip("')")
        elif '", ' in col_str:
            nome = col_str.split('", ', 1)[1].rstrip('")')
        else:
            nome = col_str # Fallback de segurança

    # 3. Se for um nome normal, mantém
    else:
        nome = col_str

    # --- LIMPEZA PADRÃO DO TEXTO ---
    nome = nome.strip().lower()

    # Substitui caracteres problemáticos por underline ou remove
    nome = nome.replace(" ", "_").replace("/", "_").replace("-", "_")
    nome = nome.replace("?", "").replace("(", "").replace(")", "")
    nome = nome.replace("'", "").replace('"', "") # Remove os apóstrofos que sobrarem (ex: etls em vez de etl's)

    # Remove acentos de forma segura e profissional
    nome = ''.join(c for c in unicodedata.normalize('NFD', nome) if unicodedata.category(c) != 'Mn')

    return nome

# Aplica a nova função em todas as colunas
df_2023.columns = [limpar_nome_coluna_v2(c) for c in df_2023.columns]

# Verifica se ficou limpo (procure por 'etl' ou 'api' agora)
print("Colunas que antes estavam quebradas:")
print([c for c in df_2023.columns if 'etl' in c or 'api' in c or 'hmm' in c])

Colunas que antes estavam quebradas:
['realizo_construcoes_de_etls_em_ferramentas_como_pentaho,_talend,_dataflow_etc.', 'quais_as_ferramentas_tecnologias_de_etl_que_voce_utiliza_no_trabalho_como_data_engineer', 'sap_bw_etl', 'nao_utilizo_ferramentas_de_etl', 'realizando_construcoes_de_etls_em_ferramentas_como_pentaho,_talend,_dataflow_etc.', 'utilizo_apis_para_extrair_dados_e_complementar_minhas_analises.', 'desenvolvo_cuido_da_manutencao_de_etls_utilizando_tecnologias_como_talend,_pentaho,_airflow,_dataflow_etc.', 'quais_as_ferramentas_tecnologias_de_etl_que_voce_utiliza_no_trabalho_como_data_analyst', 'sap_bw_etl', 'nao_utilizo_ferramentas_de_etl', 'point_and_click_analytics_como_alteryx,_knime,_rapidminer_etc.', 'utilizando_apis_para_extrair_dados_e_complementar_minhas_analises.', 'desenvolvendo_cuidando_da_manutencao_de_etls_utilizando_tecnologias_como_talend,_pentaho,_airflow,_dataflow_etc.', 'sou_responsavel_por_colocar_modelos_em_producao,_criar_os_pipelines_de_dados,_apis_de_consumo_e_monitoramento.', 'crio_e_dou_manutencao_em_etls,_dags_e_automacoes_de_pipelines_de_dados.', 'sou_responsavel_por_criar_e_manter_a_infra_que_meus_modelos_e_solucoes_rodam_clusters,_servidores,_api,_containers,_etc.', 'utilizo_cadeias_de_markov_ou_hmms_para_realizar_analises_de_dados', 'ferramentas_de_etl_apache_airflow,_nifi,_stitch,_fivetran,_pentaho_etc', 'colocando_modelos_em_producao,_criando_os_pipelines_de_dados,_apis_de_consumo_e_monitoramento.', 'criando_e_dando_manutencao_em_etls,_dags_e_automacoes_de_pipelines_de_dados.', 'criando_e_mantendo_a_infra_que_meus_modelos_e_solucoes_rodam_clusters,_servidores,_api,_containers,_etc.']

In [16]:
for i, coluna in enumerate(df_2023.columns):
    print(f'{i}. {coluna}')

0. id
1. idade
2. faixa_idade
3. genero
4. cor_raca_etnia
5. pcd
6. experiencia_profissional_prejudicada
7. nao_acredito_que_minha_experiencia_profissional_seja_afetada
8. experiencia_prejudicada_devido_a_minha_cor_raca_etnia
9. experiencia_prejudicada_devido_a_minha_identidade_de_genero
10. experiencia_prejudicada_devido_ao_fato_de_ser_pcd
11. aspectos_prejudicados
12. quantidade_de_oportunidades_de_emprego_vagas_recebidas
13. senioridade_das_vagas_recebidas_em_relacao_a_sua_experiencia
14. aprovacao_em_processos_seletivos_entrevistas
15. oportunidades_de_progressao_de_carreira
16. velocidade_de_progressao_de_carreira
17. nivel_de_cobranca_no_trabalho_stress_no_trabalho
18. atencao_dada_diante_das_minhas_opinioes_e_ideias
19. relacao_com_outros_membros_da_empresa,_em_momentos_de_trabalho
20. relacao_com_outros_membros_da_empresa,_em_momentos_de_integracao_e_outros_momentos_fora_do_trabalho
21. vive_no_brasil
22. estado_onde_mora
23. uf_onde_mora
24. regiao_onde_mora
25. mudou_de_estado
26. regiao_de_origem
27. nivel_de_ensino
28. area_de_formacao
29. qual_sua_situacao_atual_de_trabalho
30. setor
31. numero_de_funcionarios
32. gestor
33. cargo_como_gestor
34. cargo_atual
35. nivel
36. faixa_salarial
37. quanto_tempo_de_experiencia_na_area_de_dados_voce_tem
38. quanto_tempo_de_experiencia_na_area_de_ti_engenharia_de_software_voce_teve_antes_de_comecar_a_trabalhar_na_area_de_dados
39. voce_esta_satisfeito_na_sua_empresa_atual
40. qual_o_principal_motivo_da_sua_insatisfacao_com_a_empresa_atual
41. falta_de_oportunidade_de_crescimento_no_emprego_atual
42. salario_atual_nao_corresponde_ao_mercado
43. nao_tenho_uma_boa_relacao_com_meu_lider_gestor
44. gostaria_de_trabalhar_em_em_outra_area_de_atuacao
45. gostaria_de_receber_mais_beneficios
46. o_clima_de_trabalho_ambiente_nao_e_bom
47. falta_de_maturidade_analitica_na_empresa
48. voce_participou_de_entrevistas_de_emprego_nos_ultimos_6_meses
49. voce_pretende_mudar_de_emprego_nos_proximos_6_meses
50. quais_os_principais_criterios_que_voce_leva_em_consideracao_no_momento_de_decidir_onde_trabalhar
51. remuneracao_salario
52. beneficios
53. proposito_do_trabalho_e_da_empresa
54. flexibilidade_de_trabalho_remoto
55. ambiente_e_clima_de_trabalho
56. oportunidade_de_aprendizado_e_trabalhar_com_referencias_na_area
57. plano_de_carreira_e_oportunidades_de_crescimento_profissional
58. maturidade_da_empresa_em_termos_de_tecnologia_e_dados
59. qualidade_dos_gestores_e_lideres
60. reputacao_que_a_empresa_tem_no_mercado
61. empresa_que_trabaha_passou_por_layoff_em_2023
62. atualmente_qual_a_sua_forma_de_trabalho
63. qual_a_forma_de_trabalho_ideal_para_voce
64. caso_sua_empresa_decida_pelo_modelo_100%_presencial_qual_sera_sua_atitude
65. qual_o_numero_aproximado_de_pessoas_que_atuam_com_dados_na_sua_empresa_hoje
66. quais_desses_papeis_cargos_fazem_parte_do_time_ou_chapter_de_dados_da_sua_empresa
67. analytics_engineer
68. engenharia_de_dados_data_engineer
69. analista_de_dados_data_analyst
70. cientista_de_dados_data_scientist
71. database_administrator_dba
72. analista_de_business_intelligence_bi
73. arquiteto_de_dados_data_architect
74. data_product_manager_dpm
75. business_analyst
76. quais_dessas_responsabilidades_fazem_parte_da_sua_rotina_atual_de_trabalho_como_gestor
77. pensar_na_visao_de_longo_prazo_de_dados_da_empresa_e_fortalecimento_da_cultura_analitica_da_companhia.
78. organizacao_de_treinamentos_e_iniciativas_com_o_objetivo_de_aumentar_a_maturidade_analitica_das_areas_de_negocios.
79. atracao,_selecao_e_contratacao_de_talentos_para_o_time_de_dados.
80. decisao_sobre_contratacao_de_ferramentas_e_tecnologias_relacionadas_a_dados.
81. sou_gestor_da_equipe_responsavel_pela_engenharia_de_dados_e_por_manter_o_data_lake_da_empresa_como_fonte_unica_dos_dados,_garantindo_a_qualidade_e_confiabilidade_da_informacao.
82. sou_gestor_da_equipe_responsavel_pela_entrega_de_dados,_estudos,_relatorios_e_dashboards_para_as_areas_de_negocio_da_empresa.
83. sou_gestor_da_equipe_responsavel_por_iniciativas_e_projetos_envolvendo_inteligencia_artificial_e_machine_learning.
84. apesar_de_ser_gestor_ainda_atuo_na_parte_tecnica,_construindo_solucoes_analises_modelos_etc.
85. gestao_de_projetos_de_dados,_cuidando_das_etapas,_equipes_envolvidas,_atingimento_dos_objetivos_etc.
86. gestao_de_produtos_de_dados,_cuidando_da_visao_dos_produtos,_backlog,_feedback_de_usuarios_etc.
87. gestao_de_pessoas,_apoio_no_desenvolvimento_das_pessoas,_evolucao_de_carreira
88. quais_sao_os_3_maiores_desafios_que_voce_tem_como_gestor_no_atual_momento
89. a_contratar_novos_talentos.
90. b_reter_talentos.
91. c_convencer_a_empresa_a_aumentar_os_investimentos_na_area_de_dados.
92. d_gestao_de_equipes_no_ambiente_remoto.
93. e_gestao_de_projetos_envolvendo_areas_multidisciplinares_da_empresa.
94. f_organizar_as_informacoes_e_garantir_a_qualidade_e_confiabilidade.
95. g_conseguir_processar_e_armazenar_um_alto_volume_de_dados.
96. h_conseguir_gerar_valor_para_as_areas_de_negocios_atraves_de_estudos_e_experimentos.
97. i_desenvolver_e_manter_modelos_machine_learning_em_producao.
98. j_gerenciar_a_expectativa_das_areas_de_negocio_em_relacao_as_entregas_das_equipes_de_dados.
99. k_garantir_a_manutencao_dos_projetos_e_modelos_em_producao,_em_meio_ao_crescimento_da_empresa.
100. conseguir_levar_inovacao_para_a_empresa_atraves_dos_dados.
101. garantir_retorno_do_investimento_roi_em_projetos_de_dados.
102. dividir_o_tempo_entre_entregas_tecnicas_e_gestao.
103. ai_generativa_e_uma_prioridade_em_sua_empresa
104. tipos_de_uso_de_ai_generativa_e_llms_na_empresa
105. colaboradores_usando_ai_generativa_de_forma_independente_e_descentralizada
106. direcionamento_centralizado_do_uso_de_ai_generativa
107. desenvolvedores_utilizando_copilots
108. ai_generativa_e_llms_para_melhorar_produtos_externos
109. ai_generativa_e_llms_para_melhorar_produtos_internos_para_os_colaboradores
110. ia_generativa_e_llms_como_principal_frente_do_negocio
111. ia_generativa_e_llms_nao_e_prioridade
112. nao_sei_opinar_sobre_o_uso_de_ia_generativa_e_llms_na_empresa
113. motivos_que_levam_a_empresa_a_nao_usar_ai_genrativa_e_llms
114. falta_de_compreensao_dos_casos_de_uso
115. falta_de_confiabilidade_das_saidas_alucinacao_dos_modelos
116. incerteza_em_relacao_a_regulamentacao
117. preocupacoes_com_seguranca_e_privacidade_de_dados
118. retorno_sobre_investimento_roi_nao_comprovado_de_ia_generativa
119. dados_da_empresa_nao_estao_prontos_para_uso_de_ia_generativa
120. falta_de_expertise_ou_falta_de_recursos
121. alta_direcao_da_empresa_nao_ve_valor_ou_nao_ve_como_prioridade
122. preocupacoes_com_propriedade_intelectual
123. mesmo_que_esse_nao_seja_seu_cargo_formal,_voce_considera_que_sua_atuacao_no_dia_a_dia,_reflete_alguma_das_opcoes_listadas_abaixo
124. atuacao
125. quais_das_fontes_de_dados_listadas_voce_ja_analisou_ou_processou_no_trabalho
126. dados_relacionais_estruturados_em_bancos_sql
127. dados_armazenados_em_bancos_nosql
128. imagens
129. textos_documentos
130. videos
131. audios
132. planilhas
133. dados_georeferenciados
134. entre_as_fontes_de_dados_listadas,_quais_voce_utiliza_na_maior_parte_do_tempo
135. dados_relacionais_estruturados_em_bancos_sql
136. dados_armazenados_em_bancos_nosql
137. imagens
138. textos_documentos
139. videos
140. audios
141. planilhas
142. dados_georeferenciados
143. quais_das_linguagens_listadas_abaixo_voce_utiliza_no_trabalho
144. sql
145. r
146. python
147. c_c++_c#
148. .net
149. java
150. julia
151. sas_stata
152. visual_basic_vba
153. scala
154. matlab
155. rust
156. php
157. javascript
158. nao_utilizo_nenhuma_linguagem
159. entre_as_linguagens_listadas_abaixo,_qual_e_a_que_voce_mais_utiliza_no_trabalho
160. entre_as_linguagens_listadas_abaixo,_qual_e_a_sua_preferida
161. quais_dos_bancos_de_dados_fontes_de_dados_listados_abaixo_voce_utiliza_no_trabalho
162. mysql
163. oracle
164. sql_server
165. amazon_aurora_ou_rds
166. dynamodb
167. coachdb
168. cassandra
169. mongodb
170. mariadb
171. datomic
172. s3
173. postgresql
174. elasticsearch
175. db2
176. microsoft_access
177. sqlite
178. sybase
179. firebase
180. vertica
181. redis
182. neo4j
183. google_bigquery
184. google_firestore
185. amazon_redshift
186. amazon_athena
187. snowflake
188. databricks
189. hbase
190. presto
191. splunk
192. sap_hana
193. hive
194. firebird
195. dentre_as_opcoes_listadas,_qual_sua_cloud_preferida
196. azure_microsoft
197. amazon_web_services_aws
198. google_cloud_gcp
199. oracle_cloud
200. ibm
201. servidores_on_premise_nao_utilizamos_cloud
202. cloud_propria
203. cloud_preferida
204. ferramenta_de_bi_utilizada_no_dia_a_dia
205. microsoft_powerbi
206. qlik_view_qlik_sense
207. tableau
208. metabase
209. superset
210. redash
211. looker
212. looker_studiogoogle_data_studio
213. amazon_quicksight
214. mode
215. alteryx
216. microstrategy
217. ibm_analytics_cognos
218. sap_business_objects_sap_analytics
219. oracle_business_intelligence
220. salesforce_einstein_analytics
221. birst
222. sas_visual_analytics
223. grafana
224. tibco_spotfire
225. pentaho
226. fazemos_todas_as_analises_utilizando_apenas_excel_ou_planilhas_do_google
227. nao_utilizo_nenhuma_ferramenta_de_bi_no_trabalho
228. qual_sua_ferramenta_de_bi_preferida
229. qual_o_tipo_de_uso_de_ai_generativa_e_llms_na_empresa
230. colaboradores_usando_ai_generativa_de_forma_independente_e_descentralizada
231. direcionamento_centralizado_do_uso_de_ai_generativa
232. desenvolvedores_utilizando_copilots
233. ai_generativa_e_llms_para_melhorar_produtos_externos_para_os_clientes_finais
234. ai_generativa_e_llms_para_melhorar_produtos_internos_para_os_colaboradores
235. ia_generativa_e_llms_como_principal_frente_do_negocio
236. ia_generativa_e_llms_nao_e_prioridade
237. nao_sei_opinar_sobre_o_uso_de_ia_generativa_e_llms_na_empresa
238. utiliza_chatgpt_ou_llms_no_trabalho
239. nao_uso_solucoes_de_ai_generativa_com_foco_em_produtividade
240. uso_solucoes_gratuitas_de_ai_generativa_com_foco_em_produtividade
241. uso_e_pago_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade
242. a_empresa_que_trabalho_paga_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade
243. uso_solucoes_do_tipo_copilot
244. qual_seu_objetivo_na_area_de_dados
245. qual_oportunidade_voce_esta_buscando
246. ha_quanto_tempo_voce_busca_uma_oportunidade_na_area_de_dados
247. como_tem_sido_a_busca_por_um_emprego_na_area_de_dados
248. quais_das_opcoes_abaixo_fazem_parte_da_sua_rotina_no_trabalho_atual_como_engenheiro_de_dados
249. desenvolvo_pipelines_de_dados_utilizando_linguagens_de_programacao_como_python,_scala,_java_etc.
250. realizo_construcoes_de_etls_em_ferramentas_como_pentaho,_talend,_dataflow_etc.
251. crio_consultas_atraves_da_linguagem_sql_para_exportar_informacoes_e_compartilhar_com_as_areas_de_negocio.
252. atuo_na_integracao_de_diferentes_fontes_de_dados_atraves_de_plataformas_proprietarias_como_stitch_data,_fivetran_etc.
253. modelo_solucoes_de_arquitetura_de_dados,_criando_componentes_de_ingestao_de_dados,_transformacao_e_recuperacao_da_informacao.
254. desenvolvo_cuido_da_manutencao_de_repositorios_de_dados_baseados_em_streaming_de_eventos_como_data_lakes_e_data_lakehouses.
255. atuo_na_modelagem_dos_dados,_com_o_objetivo_de_criar_conjuntos_de_dados_como_data_warehouses,_data_marts_etc.
256. cuido_da_qualidade_dos_dados,_metadados_e_dicionario_de_dados.
257. nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.
258. quais_as_ferramentas_tecnologias_de_etl_que_voce_utiliza_no_trabalho_como_data_engineer
259. scripts_python
260. sql_&_stored_procedures
261. apache_airflow
262. apache_nifi
263. luigi
264. aws_glue
265. talend
266. pentaho
267. alteryx
268. stitch
269. fivetran
270. google_dataflow
271. oracle_data_integrator
272. ibm_datastage
273. sap_bw_etl
274. sql_server_integration_services_ssis
275. sas_data_integration
276. qlik_sense
277. knime
278. databricks
279. nao_utilizo_ferramentas_de_etl
280. sua_organizacao_possui_um_data_lake
281. qual_tecnologia_utilizada_como_plataforma_do_data_lake
282. sua_organizacao_possui_um_data_warehouse
283. qual_tecnologia_utilizada_como_plataforma_do_data_warehouse
284. quais_as_ferramentas_de_gestao_de_qualidade_de_dados,_metadados_e_catalogo_de_dados_voce_utiliza_no_trabalho
285. em_qual_das_opcoes_abaixo_voce_gasta_a_maior_parte_do_seu_tempo
286. desenvolvendo_pipelines_de_dados_utilizando_linguagens_de_programacao_como_python,_scala,_java_etc.
287. realizando_construcoes_de_etls_em_ferramentas_como_pentaho,_talend,_dataflow_etc.
288. criando_consultas_atraves_da_linguagem_sql_para_exportar_informacoes_e_compartilhar_com_as_areas_de_negocio.
289. atuando_na_integracao_de_diferentes_fontes_de_dados_atraves_de_plataformas_proprietarias_como_stitch_data,_fivetran_etc.
290. modelando_solucoes_de_arquitetura_de_dados,_criando_componentes_de_ingestao_de_dados,_transformacao_e_recuperacao_da_informacao.
291. desenvolvendo_cuidando_da_manutencao_de_repositorios_de_dados_baseados_em_streaming_de_eventos_como_data_lakes_e_data_lakehouses.
292. atuando_na_modelagem_dos_dados,_com_o_objetivo_de_criar_conjuntos_de_dados_como_data_warehouses,_data_marts_etc.
293. cuidando_da_qualidade_dos_dados,_metadados_e_dicionario_de_dados.
294. nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.
295. quais_das_opcoes_abaixo_fazem_parte_da_sua_rotina_no_trabalho_atual_com_analise_de_dados
296. processo_e_analiso_dados_utilizando_linguagens_de_programacao_como_python,_r_etc.
297. realizo_construcoes_de_dashboards_em_ferramentas_de_bi_como_powerbi,_tableau,_looker,_qlik_etc.
298. crio_consultas_atraves_da_linguagem_sql_para_exportar_informacoes_e_compartilhar_com_as_areas_de_negocio.
299. utilizo_apis_para_extrair_dados_e_complementar_minhas_analises.
300. realizo_experimentos_e_estudos_utilizando_metodologias_estatisticas_como_teste_de_hipotese,_modelos_de_regressao_etc.
301. desenvolvo_cuido_da_manutencao_de_etls_utilizando_tecnologias_como_talend,_pentaho,_airflow,_dataflow_etc.
302. atuo_na_modelagem_dos_dados,_com_o_objetivo_de_criar_conjuntos_de_dados,_data_warehouses,_data_marts_etc.
303. desenvolvo_cuido_da_manutencao_de_planilhas_para_atender_as_areas_de_negocio.
304. utilizo_ferramentas_avancadas_de_estatistica_como_sass,_pss,_stata_etc
305. nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.
306. quais_as_ferramentas_tecnologias_de_etl_que_voce_utiliza_no_trabalho_como_data_analyst
307. scripts_python
308. sql_&_stored_procedures
309. apache_airflow
310. apache_nifi
311. luigi
312. aws_glue
313. talend
314. pentaho
315. alteryx
316. stitch
317. fivetran
318. google_dataflow
319. oracle_data_integrator
320. ibm_datastage
321. sap_bw_etl
322. sql_server_integration_services_ssis
323. sas_data_integration
324. qlik_sense
325. knime
326. databricks
327. nao_utilizo_ferramentas_de_etl
328. sua_empresa_utiliza_alguma_das_ferramentas_listadas_para_dar_mais_autonomia_em_analise_de_dados_para_as_areas_de_negocio
329. ferramentas_de_automl_como_h2o.ai,_data_robot,_bigml_etc.
330. point_and_click_analytics_como_alteryx,_knime,_rapidminer_etc.
331. product_metricts_&_insights_como_mixpanel,_amplitude,_adobe_analytics.
332. ferramentas_de_analise_dentro_de_ferramentas_de_crm_como_salesforce_einstein_anaytics_ou_zendesk_dashboards.
333. minha_empresa_nao_utiliza_essas_ferramentas.
334. nao_sei_informar.
335. em_qual_das_opcoes_abaixo_voce_gasta_a_maior_parte_do_seu_tempo_de_trabalho
336. processando_e_analisando_dados_utilizando_linguagens_de_programacao_como_python,_r_etc.
337. realizando_construcoes_de_dashboards_em_ferramentas_de_bi_como_powerbi,_tableau,_looker,_qlik_etc.
338. criando_consultas_atraves_da_linguagem_sql_para_exportar_informacoes_e_compartilhar_com_as_areas_de_negocio.
339. utilizando_apis_para_extrair_dados_e_complementar_minhas_analises.
340. realizando_experimentos_e_estudos_utilizando_metodologias_estatisticas_como_teste_de_hipotese,_modelos_de_regressao_etc.
341. desenvolvendo_cuidando_da_manutencao_de_etls_utilizando_tecnologias_como_talend,_pentaho,_airflow,_dataflow_etc.
342. atuando_na_modelagem_dos_dados,_com_o_objetivo_de_criar_conjuntos_de_dados,_data_warehouses,_data_marts_etc.
343. desenvolvendo_cuidando_da_manutencao_de_planilhas_do_excel_ou_google_sheets_para_atender_as_areas_de_negocio.
344. utilizando_ferramentas_avancadas_de_estatistica_como_sas,_spss,_stata_etc,_para_realizar_analises.
345. nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.
346. quais_das_opcoes_abaixo_fazem_parte_da_sua_rotina_no_trabalho_atual_com_ciencia_de_dados
347. estudos_ad_hoc_com_o_objetivo_de_confirmar_hipoteses,_realizar_modelos_preditivos,_forecasts,_analise_de_cluster_para_resolver_problemas_pontuais_e_responder_perguntas_das_areas_de_negocio.
348. sou_responsavel_pela_coleta_e_limpeza_dos_dados_que_uso_para_analise_e_modelagem.
349. sou_responsavel_por_entrar_em_contato_com_os_times_de_negocio_para_definicao_do_problema,_identificar_a_solucao_e_apresentacao_de_resultados.
350. desenvolvo_modelos_de_machine_learning_com_o_objetivo_de_colocar_em_producao_em_sistemas_produtos_de_dados.
351. sou_responsavel_por_colocar_modelos_em_producao,_criar_os_pipelines_de_dados,_apis_de_consumo_e_monitoramento.
352. cuido_da_manutencao_de_modelos_de_machine_learning_ja_em_producao,_atuando_no_monitoramento,_ajustes_e_refatoracao_quando_necessario.
353. realizo_construcoes_de_dashboards_em_ferramentas_de_bi_como_powerbi,_tableau,_looker,_qlik,_etc
354. utilizo_ferramentas_avancadas_de_estatistica_como_sas,_spss,_stata_etc,_para_realizar_analises_estatisticas_e_ajustar_modelos.
355. crio_e_dou_manutencao_em_etls,_dags_e_automacoes_de_pipelines_de_dados.
356. crio_e_gerencio_solucoes_de_feature_store_e_cultura_de_mlops.
357. sou_responsavel_por_criar_e_manter_a_infra_que_meus_modelos_e_solucoes_rodam_clusters,_servidores,_api,_containers,_etc.
358. treino_e_aplico_llms_para_solucionar_problemas_de_negocio.
359. quais_as_tecnicas_e_metodos_listados_abaixo_voce_costuma_utilizar_no_trabalho
360. utilizo_modelos_de_regressao_linear,_logistica,_glm
361. utilizo_redes_neurais_ou_modelos_baseados_em_arvore_para_criar_modelos_de_classificacao
362. desenvolvo_sistemas_de_recomendacao_recsys
363. utilizo_metodos_estatisticos_bayesianos_para_analisar_dados
364. utilizo_tecnicas_de_nlp_natural_language_processing_para_analisar_dados_nao_estruturados
365. utilizo_metodos_estatisticos_classicos_testes_de_hipotese,_analise_multivariada,_sobrevivencia,_dados_longitudinais,_inferencia_estatistica_para_analisar_dados
366. utilizo_cadeias_de_markov_ou_hmms_para_realizar_analises_de_dados
367. desenvolvo_tecnicas_de_clusterizacao_k_means,_spectral,_dbscan_etc
368. realizo_previsoes_atraves_de_modelos_de_series_temporais_time_series
369. utilizo_modelos_de_reinforcement_learning_aprendizado_por_reforco
370. utilizo_modelos_de_machine_learning_para_deteccao_de_fraude
371. utilizo_metodos_de_visao_computacional
372. utilizo_modelos_de_deteccao_de_churn
373. utilizo_llms_para_solucionar_problemas_de_negocio
374. quais_dessas_tecnologias_fazem_parte_do_seu_dia_a_dia_como_cientista_de_dados
375. ferramentas_de_bi_powerbi,_looker,_tableau,_qlik_etc
376. planilhas_excel,_google_sheets_etc
377. ambientes_de_desenvolvimento_local_r_studio,_jupyterlab,_anaconda
378. ambientes_de_desenvolvimento_na_nuvem_google_colab,_aws_sagemaker,_kaggle_notebooks_etc
379. ferramentas_de_automl_datarobot,_h2o,_auto_keras_etc
380. ferramentas_de_etl_apache_airflow,_nifi,_stitch,_fivetran,_pentaho_etc
381. plataformas_de_machine_learning_tensorflow,_azure_machine_learning,_kubeflow_etc
382. feature_store_feast,_hopsworks,_aws_feature_store,_databricks_feature_store_etc
383. sistemas_de_controle_de_versao_github,_dvc,_neptune,_gitlab_etc
384. plataformas_de_data_apps_streamlit,_shiny,_plotly_dash_etc
385. ferramentas_de_estatistica_avancada_como_spss,_sas,_etc.
386. em_qual_das_opcoes_abaixo_voce_gasta_a_maior_parte_do_seu_tempo_no_trabalho
387. estudos_ad_hoc_com_o_objetivo_de_confirmar_hipoteses,_realizar_modelos_preditivos,_forecasts,_analise_de_cluster_para_resolver_problemas_pontuais_e_responder_perguntas_das_areas_de_negocio.

In [17]:
# Ranking direto da linguagem principal
print(df_2023['entre_as_linguagens_listadas_abaixo,_qual_e_a_que_voce_mais_utiliza_no_trabalho'].value_counts())

# Cruzando com salário (Anatomia do Top Tier!)
df_2023.groupby('faixa_salarial')['entre_as_linguagens_listadas_abaixo,_qual_e_a_que_voce_mais_utiliza_no_trabalho'].value_counts()

entre_as_linguagens_listadas_abaixo,_qual_e_a_que_voce_mais_utiliza_no_trabalho
SQL                                            1807
Python                                         1358
Não utilizo nenhuma das linguagens listadas     325
R                                               105
Visual Basic/VBA                                 54
SAS/Stata                                        34
Scala                                            27
JavaScript                                       25
Java                                             15
PHP                                               9
C/C++/C#                                          7
.NET                                              4
Julia                                             1
Matlab                                            1
Name: count, dtype: int64

faixa_salarial                   entre_as_linguagens_listadas_abaixo,_qual_e_a_que_voce_mais_utiliza_no_trabalho
Acima de R$ 40.001/mês           Python                                                                             12
                                 SQL                                                                                 9
                                 Não utilizo nenhuma das linguagens listadas                                         2
                                 Scala                                                                               2
                                 Java                                                                                1
                                                                                                                    ..
de R$ 8.001/mês a R$ 12.000/mês  C/C++/C#                                                                            2
                                 JavaScript                                                                          2
                                 PHP                                                                                 2
                                 .NET                                                                                1
                                 Matlab                                                                              1
Name: count, Length: 107, dtype: int64

### Conhecendo as colunas

In [18]:
# ID
print(df_2023['id'].duplicated().sum())

0

In [19]:
print(df_2023['id'].count())

5293

In [20]:
df_2023['genero'].value_counts()

genero
Masculino               3975
Feminino                1293
Prefiro não informar      16
Outro                      9
Name: count, dtype: int64

In [21]:
df_2023['regiao_onde_mora'].unique()

array(['Sudeste', 'Nordeste', 'Sul', 'Centro-oeste', nan, 'Norte'],
      dtype=object)

In [22]:
df_2023['nivel_de_ensino'].value_counts()

nivel_de_ensino
Pós-graduação                 1818
Graduação/Bacharelado         1798
Estudante de Graduação         678
Mestrado                       676
Doutorado ou Phd               210
Não tenho graduação formal     105
Prefiro não informar             8
Name: count, dtype: int64

In [23]:
df_2023['faixa_salarial'].value_counts()

faixa_salarial
de R$ 8.001/mês a R$ 12.000/mês     1026
de R$ 4.001/mês a R$ 6.000/mês       745
de R$ 12.001/mês a R$ 16.000/mês     650
de R$ 6.001/mês a R$ 8.000/mês       637
de R$ 3.001/mês a R$ 4.000/mês       352
de R$ 16.001/mês a R$ 20.000/mês     328
de R$ 2.001/mês a R$ 3.000/mês       288
de R$ 1.001/mês a R$ 2.000/mês       215
de R$ 20.001/mês a R$ 25.000/mês     195
de R$ 25.001/mês a R$ 30.000/mês     128
de R$ 30.001/mês a R$ 40.000/mês      86
Acima de R$ 40.001/mês                72
Menos de R$ 1.000/mês                 30
de R$ 101/mês a R$ 2.000/mês           1
Name: count, dtype: int64

In [24]:
df_2023['nivel'].value_counts()

nivel
Sênior    1419
Pleno     1392
Júnior    1046
Name: count, dtype: int64

In [25]:
df_2023['cargo_atual'].value_counts()

cargo_atual
Analista de Dados/Data Analyst                                         907
Cientista de Dados/Data Scientist                                      687
Engenheiro de Dados/Arquiteto de Dados/Data Engineer/Data Architect    684
Analista de BI/BI Analyst                                              506
Outra Opção                                                            262
Analista de Negócios/Business Analyst                                  195
Analytics Engineer                                                     139
Desenvolvedor/ Engenheiro de Software/ Analista de Sistemas            105
Data Product Manager/ Product Manager (PM/APM/DPM/GPM/PO)               81
Engenheiro de Machine Learning/ML Engineer/AI Engineer                  75
Analista de Suporte/Analista Técnico                                    72
Analista de Inteligência de Mercado/Market Intelligence                 39
Outras Engenharias (não inclui dev)                                     31
Professor/Pesquisador                                                   28
Estatístico                                                             21
DBA/Administrador de Banco de Dados                                     20
Economista                                                               5
Name: count, dtype: int64

### Limpeza finalizado, selecionar as colunas que vamos usar

In [26]:
# vem antes do criar
cols = df_2023.columns.tolist()
contador = {}
for i, nome in enumerate(cols):
    if nome in contador:
        contador[nome] += 1
        cols[i] = f"{nome}__{contador[nome]}"
    else:
        contador[nome] = 0
df_2023.columns = cols

# Confere que zerou:
print(df_2023.columns[df_2023.columns.duplicated()].tolist())

[]

In [27]:
colunas_silver = [

    # ========== IDENTIFICAÇÃO E DEMOGRAFIA ==========
    'id', 'idade', 'faixa_idade', 'genero', 'cor_raca_etnia', 'pcd',

    # ========== DIVERSIDADE: VIVÊNCIAS DE PRECONCEITO ==========
    'experiencia_prejudicada_devido_a_minha_identidade_de_genero',
    'experiencia_prejudicada_devido_a_minha_cor_raca_etnia',
    'experiencia_prejudicada_devido_ao_fato_de_ser_pcd',
    'quantidade_de_oportunidades_de_emprego_vagas_recebidas',
    'senioridade_das_vagas_recebidas_em_relacao_a_sua_experiencia',
    'aprovacao_em_processos_seletivos_entrevistas',
    'oportunidades_de_progressao_de_carreira',

    # ========== LOCALIZAÇÃO E FORMAÇÃO ==========
    'estado_onde_mora', 'uf_onde_mora', 'regiao_onde_mora',
    'nivel_de_ensino', 'area_de_formacao',

    # ========== TRABALHO, CARGO E SALÁRIO ==========
    'qual_sua_situacao_atual_de_trabalho', 'setor', 'cargo_atual', 'nivel', 'faixa_salarial',
    'quanto_tempo_de_experiencia_na_area_de_dados_voce_tem',
    'quanto_tempo_de_experiencia_na_area_de_ti_engenharia_de_software_voce_teve_antes_de_comecar_a_trabalhar_na_area_de_dados',
    'atualmente_qual_a_sua_forma_de_trabalho',
    'qual_a_forma_de_trabalho_ideal_para_voce',
    'caso_sua_empresa_decida_pelo_modelo_100%_presencial_qual_sera_sua_atitude',

    # ========== SATISFAÇÃO E INSATISFAÇÃO ==========
    'voce_esta_satisfeito_na_sua_empresa_atual',
    'qual_o_principal_motivo_da_sua_insatisfacao_com_a_empresa_atual',
    'falta_de_oportunidade_de_crescimento_no_emprego_atual',
    'salario_atual_nao_corresponde_ao_mercado',
    'nao_tenho_uma_boa_relacao_com_meu_lider_gestor',
    'gostaria_de_trabalhar_em_em_outra_area_de_atuacao',
    'gostaria_de_receber_mais_beneficios',
    'o_clima_de_trabalho_ambiente_nao_e_bom',
    'falta_de_maturidade_analitica_na_empresa',

    # ========== CRITÉRIOS PARA ESCOLHER ONDE TRABALHAR ==========
    'remuneracao_salario', 'beneficios', 'proposito_do_trabalho_e_da_empresa',
    'flexibilidade_de_trabalho_remoto', 'ambiente_e_clima_de_trabalho',
    'oportunidade_de_aprendizado_e_trabalhar_com_referencias_na_area',
    'plano_de_carreira_e_oportunidades_de_crescimento_profissional',
    'maturidade_da_empresa_em_termos_de_tecnologia_e_dados',
    'qualidade_dos_gestores_e_lideres', 'reputacao_que_a_empresa_tem_no_mercado',

    # ========== DESAFIOS DOS GESTORES ==========
    'a_contratar_novos_talentos.', 'b_reter_talentos.',
    'c_convencer_a_empresa_a_aumentar_os_investimentos_na_area_de_dados.',
    'd_gestao_de_equipes_no_ambiente_remoto.',
    'e_gestao_de_projetos_envolvendo_areas_multidisciplinares_da_empresa.',
    'f_organizar_as_informacoes_e_garantir_a_qualidade_e_confiabilidade.',
    'g_conseguir_processar_e_armazenar_um_alto_volume_de_dados.',
    'h_conseguir_gerar_valor_para_as_areas_de_negocios_atraves_de_estudos_e_experimentos.',
    'i_desenvolver_e_manter_modelos_machine_learning_em_producao.',
    'j_gerenciar_a_expectativa_das_areas_de_negocio_em_relacao_as_entregas_das_equipes_de_dados.',
    'k_garantir_a_manutencao_dos_projetos_e_modelos_em_producao,_em_meio_ao_crescimento_da_empresa.',
    'conseguir_levar_inovacao_para_a_empresa_atraves_dos_dados.',
    'garantir_retorno_do_investimento_roi_em_projetos_de_dados.',
    'dividir_o_tempo_entre_entregas_tecnicas_e_gestao.',

    # ========== IA NA EMPRESA (prioridade, usos e barreiras) ==========
    'ai_generativa_e_uma_prioridade_em_sua_empresa',
    'colaboradores_usando_ai_generativa_de_forma_independente_e_descentralizada',
    'direcionamento_centralizado_do_uso_de_ai_generativa',
    'desenvolvedores_utilizando_copilots',
    'ai_generativa_e_llms_para_melhorar_produtos_externos',
    'ai_generativa_e_llms_para_melhorar_produtos_internos_para_os_colaboradores',
    'ia_generativa_e_llms_como_principal_frente_do_negocio',
    'ia_generativa_e_llms_nao_e_prioridade',
    'nao_sei_opinar_sobre_o_uso_de_ia_generativa_e_llms_na_empresa',
    'falta_de_compreensao_dos_casos_de_uso',
    'falta_de_confiabilidade_das_saidas_alucinacao_dos_modelos',
    'incerteza_em_relacao_a_regulamentacao',
    'preocupacoes_com_seguranca_e_privacidade_de_dados',
    'retorno_sobre_investimento_roi_nao_comprovado_de_ia_generativa',
    'dados_da_empresa_nao_estao_prontos_para_uso_de_ia_generativa',
    'falta_de_expertise_ou_falta_de_recursos',
    'alta_direcao_da_empresa_nao_ve_valor_ou_nao_ve_como_prioridade',
    'preocupacoes_com_propriedade_intelectual',

    # ========== ATUAÇÃO E LINGUAGENS ==========
    'atuacao',
    'sql', 'r', 'python', 'c_c++_c#', '.net', 'java', 'julia', 'sas_stata',
    'visual_basic_vba', 'scala', 'matlab', 'rust', 'php', 'javascript',
    'nao_utilizo_nenhuma_linguagem',
    'entre_as_linguagens_listadas_abaixo,_qual_e_a_que_voce_mais_utiliza_no_trabalho',

    # ========== BANCOS DE DADOS ==========
    'mysql', 'oracle', 'sql_server', 'amazon_aurora_ou_rds', 'dynamodb', 'coachdb',
    'cassandra', 'mongodb', 'mariadb', 'datomic', 's3', 'postgresql', 'elasticsearch',
    'db2', 'microsoft_access', 'sqlite', 'sybase', 'firebase', 'vertica', 'redis',
    'neo4j', 'google_bigquery', 'google_firestore', 'amazon_redshift', 'amazon_athena',
    'snowflake', 'databricks', 'hbase', 'presto', 'splunk', 'sap_hana', 'hive', 'firebird',

    # ========== CLOUD ==========
    'azure_microsoft', 'amazon_web_services_aws', 'google_cloud_gcp', 'oracle_cloud',
    'ibm', 'servidores_on_premise_nao_utilizamos_cloud', 'cloud_propria', 'cloud_preferida',

    # ========== FERRAMENTAS DE BI ==========
    'ferramenta_de_bi_utilizada_no_dia_a_dia',   # adicionei de volta (estava no nosso combinado!)
    'microsoft_powerbi', 'qlik_view_qlik_sense', 'tableau', 'metabase', 'superset',
    'redash', 'looker', 'looker_studiogoogle_data_studio', 'amazon_quicksight', 'mode',
    'alteryx', 'microstrategy', 'ibm_analytics_cognos', 'sap_business_objects_sap_analytics',
    'oracle_business_intelligence', 'salesforce_einstein_analytics', 'birst',
    'sas_visual_analytics', 'grafana', 'tibco_spotfire', 'pentaho',
    'fazemos_todas_as_analises_utilizando_apenas_excel_ou_planilhas_do_google',
    'nao_utilizo_nenhuma_ferramenta_de_bi_no_trabalho',

    # ========== IA INDIVIDUAL (ChatGPT / Copilot) ==========
    'utiliza_chatgpt_ou_llms_no_trabalho?',
    'nao_uso_solucoes_de_ai_generativa_com_foco_em_produtividade',
    'uso_solucoes_gratuitas_de_ai_generativa_com_foco_em_produtividade',
    'uso_e_pago_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade',
    'a_empresa_que_trabalho_paga_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade',
    'uso_solucoes_do_tipo_copilot',

    # ========== FERRAMENTAS DE ETL ==========
    'scripts_python', 'sql_&_stored_procedures', 'apache_airflow', 'apache_nifi', 'luigi',
    'aws_glue', 'talend', 'pentaho', 'alteryx', 'stitch', 'fivetran', 'google_dataflow',
    'oracle_data_integrator', 'ibm_datastage', 'sap_bw_etl', 'sql_server_integration_services_ssis',
    'sas_data_integration', 'qlik_sense', 'knime', 'databricks', 'nao_utilizo_ferramentas_de_etl',

    # ========== MATURIDADE DA EMPRESA ==========
    'sua_organizacao_possui_um_data_lake?',
    'sua_organizacao_possui_um_data_warehouse?',

    # ========== FERRAMENTAS DE CIÊNCIA DE DADOS (MLOps) ==========
    'ambientes_de_desenvolvimento_na_nuvem_google_colab,_aws_sagemaker,_kaggle_notebooks_etc',
    'plataformas_de_machine_learning_tensorflow,_azure_machine_learning,_kubeflow_etc',
    'feature_store_feast,_hopsworks,_aws_feature_store,_databricks_feature_store_etc',
    'sistemas_de_controle_de_versao_github,_dvc,_neptune,_gitlab_etc',
    'plataformas_de_data_apps_streamlit,_shiny,_plotly_dash_etc',
]

# ---------- TRAVA 1: remove duplicadas (mantém a ordem) ----------
colunas_silver = list(dict.fromkeys(colunas_silver))

# ---------- TRAVA 2: encontra a coluna mesmo com diferenças de nome ----------
def normalizar(nome):
    nome = str(nome).strip().lower().rstrip('.').replace('?', '').replace('%', '')
    return ''.join(c for c in unicodedata.normalize('NFD', nome)
                   if unicodedata.category(c) != 'Mn')

mapa_df = {normalizar(c): c for c in df_2023.columns}

colunas_finais, faltando = [], []
for c in colunas_silver:
    real = mapa_df.get(normalizar(c))
    if real:
        colunas_finais.append(real)
    else:
        faltando.append(c)

print(f" {len(colunas_finais)} colunas encontradas!")
print(f" {len(faltando)} não encontradas (se aparecer alguma, precisa ajustar o nome):")
print(faltando)

# ---------- CRIA A TABELA FINAL ----------
df_silver_2023 = df_2023[colunas_finais].copy()

# ---------- TRAVA 3: limpa nomes com %, ? ou ponto final (p/ Athena depois) ----------
renomear = {}
for c in df_silver_2023.columns:
    limpo = c.replace('%', 'pct').replace('?', '').rstrip('.')
    if limpo != c:
        renomear[c] = limpo
df_silver_2023 = df_silver_2023.rename(columns=renomear)

print(f"\nShape final: {df_silver_2023.shape}")
df_silver_2023.head()

 192 colunas encontradas!
 0 não encontradas (se aparecer alguma, precisa ajustar o nome):
[]

Shape final: (5293, 192)

,id,idade,faixa_idade,genero,cor_raca_etnia,pcd,experiencia_prejudicada_devido_a_minha_identidade_de_genero,experiencia_prejudicada_devido_a_minha_cor_raca_etnia,experiencia_prejudicada_devido_ao_fato_de_ser_pcd,quantidade_de_oportunidades_de_emprego_vagas_recebidas,...,qlik_sense,knime,nao_utilizo_ferramentas_de_etl,sua_organizacao_possui_um_data_lake,sua_organizacao_possui_um_data_warehouse,"ambientes_de_desenvolvimento_na_nuvem_google_colab,_aws_sagemaker,_kaggle_notebooks_etc","plataformas_de_machine_learning_tensorflow,_azure_machine_learning,_kubeflow_etc","feature_store_feast,_hopsworks,_aws_feature_store,_databricks_feature_store_etc","sistemas_de_controle_de_versao_github,_dvc,_neptune,_gitlab_etc","plataformas_de_data_apps_streamlit,_shiny,_plotly_dash_etc"
0,001b2d1qtli8t9z7oqgdhj001b2d4i0g,31,30-34,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,1.0,1.0
1,0026aa3fwd78u0026asg7456tfkjg2cs,30,30-34,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00r21rb9pusd1b0v7ew00r21rw3dy69w,37,35-39,Feminino,Amarela,Não,1.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,1.0,0.0
3,00urm3jf2cek12w6ygue00urm3jzd17j,22,22-24,Masculino,Preta,Não,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00v0az4g792svil00vn6y1kfm9hq8vy9,34,30-34,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
print('Dimensões da Dataset:')
print(f'Linhas: {df_silver_2023.shape[0]}')
print(f'Colunas: {df_silver_2023.shape[1]}')

Dimensões da Dataset:
Linhas: 5293
Colunas: 192

In [29]:
df_silver_2023

,id,idade,faixa_idade,genero,cor_raca_etnia,pcd,experiencia_prejudicada_devido_a_minha_identidade_de_genero,experiencia_prejudicada_devido_a_minha_cor_raca_etnia,experiencia_prejudicada_devido_ao_fato_de_ser_pcd,quantidade_de_oportunidades_de_emprego_vagas_recebidas,...,qlik_sense,knime,nao_utilizo_ferramentas_de_etl,sua_organizacao_possui_um_data_lake,sua_organizacao_possui_um_data_warehouse,"ambientes_de_desenvolvimento_na_nuvem_google_colab,_aws_sagemaker,_kaggle_notebooks_etc","plataformas_de_machine_learning_tensorflow,_azure_machine_learning,_kubeflow_etc","feature_store_feast,_hopsworks,_aws_feature_store,_databricks_feature_store_etc","sistemas_de_controle_de_versao_github,_dvc,_neptune,_gitlab_etc","plataformas_de_data_apps_streamlit,_shiny,_plotly_dash_etc"
0,001b2d1qtli8t9z7oqgdhj001b2d4i0g,31,30-34,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,1.0,1.0
1,0026aa3fwd78u0026asg7456tfkjg2cs,30,30-34,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00r21rb9pusd1b0v7ew00r21rw3dy69w,37,35-39,Feminino,Amarela,Não,1.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,1.0,0.0
3,00urm3jf2cek12w6ygue00urm3jzd17j,22,22-24,Masculino,Preta,Não,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00v0az4g792svil00vn6y1kfm9hq8vy9,34,30-34,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5288,zyg9519671iqrgy93qzyg95183k8ix5f,34,30-34,Masculino,Preta,Não,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5289,zyppgxzxko25qkgwsbrgpzyppgxzxs81,32,30-34,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,1.0,1.0
5290,zysl5f50cnz3r0cbe6t2zysrxbzfsrng,25,25-29,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5291,zyt2656c9e1becxp457zyt26566dsng8,31,30-34,Masculino,Parda,Não,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5292,zzvyz3z5jy2lzzvyziv62lvtjrab9r5x,31,30-34,Masculino,Amarela,Não,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## **2024**

### Entendendo o DF

In [30]:
df_2024.head()

,0.a_token,0.d_data/hora_envio,1.a_idade,1.a.1_faixa_idade,1.b_genero,1.c_cor/raca/etnia,1.d_pcd,1.e_experiencia_profissional_prejudicada,1.e.1_Não acredito que minha experiência profissional seja afetada,"1.e.2_Sim, devido a minha Cor/Raça/Etnia",...,"8.d.3_Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.",8.d.4_Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).,"8.d.5_Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.","8.d.6_Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.","8.d.7_Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc.","8.d.8_Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.","8.d.9_Criando e dando manutenção em ETLs, DAGs e automações de pipelines de dados.",8.d.10_Criando e gerenciando soluções de Feature Store e cultura de MLOps.,"8.d.11_Criando e mantendo a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)",8.d.12_Treinando e aplicando LLM's para solucionar problemas de negócio.
0,reb94rv0msth7q4nreb94riaq80iz3yi,16/10/2024 11:19:17,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1zc66g69jjt49y32l1zc66g8wqj79m4e,16/10/2024 20:45:31,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,uu99wmam4n5kc2uu99wmydf0rk7l58f7,17/10/2024 18:10:59,18,17-21,Masculino,Parda,Não,Não acredito que minha experiência profissiona...,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3ynsw7z0hl5hhpbfvaeqk73ynsw7z04l,22/10/2024 18:03:00,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,v6bji2ct5xckpl1uouv6bjiotkrf3b4f,23/10/2024 01:33:23,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
print('Dimensões da Dataset:')
print(f'Linhas: {df_2024.shape[0]}')
print(f'Colunas: {df_2024.shape[1]}')

Dimensões da Dataset:
Linhas: 5217
Colunas: 403

In [32]:
print('Informações Gerais:')
print(df_2024.info())

Informações Gerais:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5217 entries, 0 to 5216
Columns: 403 entries, 0.a_token to 8.d.12_Treinando e aplicando LLM's para solucionar problemas de negócio.
dtypes: bool(1), float64(323), int64(1), object(78)
memory usage: 16.0+ MB
None

In [33]:
print(df_2024.duplicated().sum())

2

In [34]:
df_2024.isnull().sum()

0.a_token                                                                                                               0
0.d_data/hora_envio                                                                                                     0
1.a_idade                                                                                                               0
1.a.1_faixa_idade                                                                                                       0
1.b_genero                                                                                                              0
                                                                                                                     ...
8.d.8_Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.             4444
8.d.9_Criando e dando manutenção em ETLs, DAGs e automações de pipelines de dados.                                   4444
8.d.10_Criando e gerenciando soluções de Feature Store e cultura de MLOps.                                           4444
8.d.11_Criando e mantendo a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)    4444
8.d.12_Treinando e aplicando LLM's para solucionar problemas de negócio.                                             4444
Length: 403, dtype: int64

In [35]:
for i, coluna in enumerate(df_2024.columns):
    print(f'{i}. {coluna}')

0. 0.a_token
1. 0.d_data/hora_envio
2. 1.a_idade
3. 1.a.1_faixa_idade
4. 1.b_genero
5. 1.c_cor/raca/etnia
6. 1.d_pcd
7. 1.e_experiencia_profissional_prejudicada
8. 1.e.1_Não acredito que minha experiência profissional seja afetada
9. 1.e.2_Sim, devido a minha Cor/Raça/Etnia
10. 1.e.3_Sim, devido a minha identidade de gênero
11. 1.e.4_Sim, devido ao fato de ser PCD
12. 1.i.1_uf_onde_mora
13. 1.f.1_Quantidade de oportunidades de emprego/vagas recebidas
14. 1.f.2_Senioridade das vagas recebidas em relação à sua experiência
15. 1.f.3_Aprovação em processos seletivos/entrevistas
16. 1.f.4_Oportunidades de progressão de carreira
17. 1.f.5_Velocidade de progressão de carreira
18. 1.f.6_Nível de cobrança no trabalho/Stress no trabalho
19. 1.f.7_Atenção dada pelas pessoas diante das minhas opiniões e ideias
20. 1.f.8_Relação com outras pessoas da empresa, em momentos de trabalho
21. 1.f.9_Relação com outras pessoas da empresa, em momentos de integração e outros momentos fora do trabalho
22. 1.i.2_regiao_onde_mora
23. 1.f_aspectos_prejudicados
24. 1.k.1_uf_de_origem
25. 1.k.2_regiao_de_origem
26. 1.g_vive_no_brasil
27. 1.h_pais_onde_mora
28. 1.i_estado_onde_mora
29. 1.j_vive_no_estado_de_formacao
30. 1.k_estado_de_origem
31. 1.l_nivel_de_ensino
32. 1.m_área_de_formação
33. 2.a_situação_de_trabalho
34. 2.b_setor
35. 2.c_numero_de_funcionarios
36. 2.d_atua_como_gestor
37. 2.e_cargo_como_gestor
38. 2.f_cargo_atual
39. 2.g_nivel
40. 2.h_faixa_salarial
41. 2.i_tempo_de_experiencia_em_dados
42. 2.j_tempo_de_experiencia_em_ti
43. 2.k_satisfeito_atualmente
44. 2.l.1_Remuneração/Salário
45. 2.l.2_Benefícios
46. 2.l.3_Propósito do trabalho e da empresa
47. 2.l.4_Flexibilidade de trabalho remoto
48. 2.l.5_Ambiente e clima de trabalho
49. 2.l.6_Oportunidade de aprendizado e trabalhar com referências
50. 2.l.7_Oportunidades de crescimento
51. 2.l.8_Maturidade da empresa em termos de tecnologia e dados
52. 2.l.9_Relação com os gestores e líderes
53. 2.l.10_Reputação que a empresa tem no mercado
54. 2.l.11_Gostaria de trabalhar em outra área
55. 2.l_motivo_insatisfacao
56. 2.m_participou_de_entrevistas_ultimos_6m
57. 2.n_planos_de_mudar_de_emprego_6m
58. 2.o_criterios_para_escolha_de_emprego
59. 2.o.1_Remuneração/Salário
60. 2.o.2_Benefícios
61. 2.o.3_Propósito do trabalho e da empresa
62. 2.o.4_Flexibilidade de trabalho remoto
63. 2.o.5_Ambiente e clima de trabalho
64. 2.o.6_Oportunidade de aprendizado e trabalhar com referências
65. 2.o.7_Plano de carreira e oportunidades de crescimento
66. 2.o.8_Maturidade da empresa em termos de tecnologia e dados
67. 2.o.9_Qualidade dos gestores e líderes
68. 2.o.10_Reputação que a empresa tem no mercado
69. 2.q_empresa_passou_por_layoff_em_2024
70. 2.r_modelo_de_trabalho_atual
71. 2.s_modelo_de_trabalho_ideal
72. 2.t_atitude_em_caso_de_retorno_presencial
73. 3.a_numero_de_pessoas_em_dados
74. 3.b_cargos_no_time_de_dados_da_empresa
75. 3.b.1_Analytics Engineer
76. 3.b.2_Engenharia de Dados/Data Engineer
77. 3.b.3_Analista de Dados/Data Analyst
78. 3.b.4_Cientista de Dados/Data Scientist
79. 3.b.5_Database Administrator/DBA
80. 3.b.6_Analista de Business Intelligence/BI
81. 3.b.7_Arquiteto de Dados/Data Architect
82. 3.b.8_Data Product Manager/DPM
83. 3.b.9_Business Analyst
84. 3.b.10_ML Engineer/AI Engineer
85. 3.c_responsabilidades_como_gestor
86. 3.c.1_Pensar na visão de longo prazo de dados
87. 3.c.2_Organização de treinamentos e iniciativas
88. 3.c.3_Atração, seleção e contratação
89. 3.c.4_Decisão sobre contratação de ferramentas
90. 3.c.5_gestor da equipe de engenharia de dados
91. 3.c.6_gestor da equipe de estudos, relatórios
92. 3.c.7_gestor da equipe de Inteligência Artificial e Machine Learning
93. 3.c.8_Apesar de ser gestor ainda atuo na parte técnica
94. 3.c.9_Gestão de projetos de dados
95. 3.c.10_Gestão de produtos de dados
96. 3.c.11_Gestão de pessoas
97. 3.d_desafios_como_gestor
98. 3.d.1_Contratar talentos
99. 3.d.2_Reter talentos
100. 3.d.3_Convencer a empresa a aumentar investimentos
101. 3.d.4_Gestão de equipes no ambiente remoto
102. 3.d.5_Gestão de projetos envolvendo áreas multidisciplinares
103. 3.d.6_Organizar as informações com qualidade e confiabilidade
104. 3.d.7_Processar e armazenar um alto volume de dados
105. 3.d.8_Gerar valor para as áreas de negócios
106. 3.d.9_Desenvolver e manter modelos Machine Learning em produção
107. 3.d.10_Gerenciar a expectativa das áreas
108. 3.d.11_Garantir a manutenção dos projetos e modelos em produção
109. 3.d.12_Conseguir levar inovação para a empresa
110. 3.d.13_Garantir (ROI) em projetos de dados
111. 3.d.14_Dividir o tempo entre entregas técnicas e gestão
112. 3.e_ai_generativa_e_llm_é_uma_prioridade?
113. 3.f_tipo_de_uso_de_ai_generativa_e_llm_na_empresa
114. 3.f.1 Colaboradores usando AI generativa de forma independente e descentralizada
115. 3.f.2 Direcionamento centralizado do uso de AI generativa
116. 3.f.3 Desenvolvedores utilizando Copilots
117. 3.f.4 AI Generativa e LLMs para melhorar produtos externos para os clientes finais
118. 3.f.5 AI Generativa e LLMs para melhorar produtos internos para os colaboradores
119. 3.f.6 IA Generativa e LLMs como principal frente do negócio
120. 3.f.7 IA Generativa e LLMs não é prioridade
121. 3.f.8 Não sei opinar sobre o uso de IA Generativa e LLMs na empresa
122. 3.g_motivos_para_não_usar_ai_generativa_e_llm
123. 3.g.1 Falta de compreensão dos casos de uso
124. 3.g.2 Falta de confiabilidade das saídas (alucinação dos modelos)
125. 3.g.3 Incerteza em relação a regulamentação
126. 3.g.4 Preocupações com segurança e privacidade de dados
127. 3.g.5 Retorno sobre investimento (ROI) não comprovado de IA Generativa
128. 3.g.6 Dados da empresa não estão prontos para uso de IA Generativa
129. 3.g.7 Falta de expertise ou falta de recursos
130. 3.g.8 Alta direção da empresa não vê valor ou não vê como prioridade
131. 3.g.9 Preocupações com propriedade intelectual
132. 4.a_funcao_de_atuacao
133. 4.a.1_atuacao_em_dados
134. 4.b_fontes_de_dados_(dia_a_dia)
135. 4.b.1_Dados relacionais (estruturados em bancos SQL)
136. 4.b.2_Dados armazenados em bancos NoSQL
137. 4.b.3_Imagens
138. 4.b.4_Textos/Documentos
139. 4.b.5_Vídeos
140. 4.b.6_Áudios
141. 4.b.7_Planilhas
142. 4.b.8_Dados georeferenciados
143. 4.c_fonte_de_dado_mais_usada
144. 4.c.1_Dados relacionais (estruturados em bancos SQL)
145. 4.c.2_Dados armazenados em bancos NoSQL
146. 4.c.3_Imagens
147. 4.c.4_Textos/Documentos
148. 4.c.5_Vídeos
149. 4.c.6_Áudios
150. 4.c.7_Planilhas
151. 4.c.8_Dados georeferenciados
152. 4.d_linguagem_de_programacao_(dia_a_dia)
153. 4.d.1_SQL
154. 4.d.2_R
155. 4.d.3_Python
156. 4.d.4_C/C++/C#
157. 4.d.5_.NET
158. 4.d.6_Java
159. 4.d.7_Julia
160. 4.d.8_SAS/Stata
161. 4.d.9_Visual Basic/VBA
162. 4.d.10_Scala
163. 4.d.11_Matlab
164. 4.d.12_Rust
165. 4.d.13_PHP
166. 4.d.14_JavaScript
167. 4.d.15_Não utilizo nenhuma das linguagens listadas
168. 4.e_linguagem_mais_usada
169. 4.f_linguagem_preferida
170. 4.g_banco_de_dados_(dia_a_dia)
171. 4.g.1_MySQL
172. 4.g.2_Oracle
173. 4.g.3_SQL SERVER
174. 4.g.4_Amazon Aurora ou RDS
175. 4.g.5_DynamoDB
176. 4.g.6_CoachDB
177. 4.g.7_Cassandra
178. 4.g.8_MongoDB
179. 4.g.9_MariaDB
180. 4.g.10_Datomic
181. 4.g.11_S3
182. 4.g.12_PostgreSQL
183. 4.g.13_ElasticSearch
184. 4.g.14_DB2
185. 4.g.15_Microsoft Access
186. 4.g.16_SQLite
187. 4.g.17_Sybase
188. 4.g.18_Firebase
189. 4.g.19_Vertica
190. 4.g.20_Redis
191. 4.g.21_Neo4J
192. 4.g.22_Google BigQuery
193. 4.g.23_Google Firestore
194. 4.g.24_Amazon Redshift
195. 4.g.25_Amazon Athena
196. 4.g.26_Snowflake
197. 4.g.27_Databricks
198. 4.g.28_HBase
199. 4.g.29_Presto
200. 4.g.30_Splunk
201. 4.g.31_SAP HANA
202. 4.g.32_Hive
203. 4.g.33_Firebird
204. 4.h_cloud_(dia_a_dia)
205. 4.h.1_Amazon Web Services (AWS)
206. 4.h.2_Google Cloud (GCP)
207. 4.h.3_Azure (Microsoft)
208. 4.h.4_Oracle Cloud
209. 4.h.5_IBM
210. 4.h.6_Servidores On Premise/Não utilizamos Cloud
211. 4.h.7_Cloud Própria
212. 4.i_cloud_preferida
213. 4.j_ferramenta_de_bi_(dia_a_dia)
214. 4.j.1_Microsoft PowerBI
215. 4.j.2_Qlik View/Qlik Sense
216. 4.j.3_Tableau
217. 4.j.4_Metabase
218. 4.j.5_Superset
219. 4.j.6_Redash
220. 4.j.7_Looker
221. 4.j.8_Looker Studio(Google Data Studio)
222. 4.j.9_Amazon Quicksight
223. 4.j.10_Alteryx
224. 4.j.11_SAP Business Objects/SAP Analytics
225. 4.j.12_Oracle Business Intelligence
226. 4.j.13_Salesforce/Einstein Analytics
227. 4.j.14_SAS Visual Analytics
228. 4.j.15_Grafana
229. 4.j.16_Pentaho
230. 4.j.17_Fazemos todas as análises utilizando apenas Excel ou planilhas do google
231. 4.j.18_Não utilizo nenhuma ferramenta de BI no trabalho
232. 4.k_ferramenta_de_bi_preferida
233. 4.l_tipo_de_uso_de_ai_generativa_e_llm_na_empresa
234. 4.l.1 Colaboradores usando AI generativa de forma independente e descentralizada
235. 4.l.2 Direcionamento centralizado do uso de AI generativa
236. 4.l.3 Desenvolvedores utilizando Copilots
237. 4.l.4 AI Generativa e LLMs para melhorar produtos externos para os clientes finais
238. 4.l.5 AI Generativa e LLMs para melhorar produtos internos para os colaboradores
239. 4.l.6 IA Generativa e LLMs como principal frente do negócio
240. 4.l.7 IA Generativa e LLMs não é prioridade
241. 4.l.8 Não sei opinar sobre o uso de IA Generativa e LLMs na empresa
242. 4.m_usa_chatgpt_ou_copilot_no_trabalho?
243. 4.m.1 Não uso soluções de AI Generativa com foco em produtividade
244. 4.m.2 Uso soluções gratuitas de AI Generativa com foco em produtividade
245. 4.m.3 Uso e pago pelas soluções de AI Generativa com foco em produtividade
246. 4.m.4 A empresa que trabalho paga pelas soluções de AI Generativa com foco em produtividade
247. 4.m.5 Uso soluções do tipo Copilot
248. 5.a_objetivo_na_area_de_dados
249. 5.b_oportunidade_buscada
250. 5.c_tempo_em_busca_de_oportunidade
251. 5.d_experiencia_em_processos_seletivos
252. 6.a_rotina_como_de
253. 6.a.1_Desenvolvo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.
254. 6.a.2_Realizo construções de ETL's em ferramentas como Pentaho, Talend, Dataflow etc.
255. 6.a.3_Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.
256. 6.a.4_Atuo na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.
257. 6.a.5_Modelo soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.
258. 6.a.6_Desenvolvo/cuido da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.
259. 6.a.7_Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.
260. 6.a.8_Cuido da qualidade dos dados, metadados e dicionário de dados.
261. 6.a.9_Nenhuma das opções listadas refletem meu dia a dia.
262. 6.b_ferramentas_etl_de
263. 6.b.1_Scripts Python
264. 6.b.2_SQL & Stored Procedures
265. 6.b.3_Apache Airflow
266. 6.b.4_Apache NiFi
267. 6.b.5_Luigi
268. 6.b.6_AWS Glue
269. 6.b.7_Talend
270. 6.b.8_Pentaho
271. 6.b.9_Alteryx
272. 6.b.10_Stitch
273. 6.b.11_Fivetran
274. 6.b.12_Google Dataflow
275. 6.b.13_Oracle Data Integrator
276. 6.b.14_IBM DataStage
277. 6.b.15_SAP BW ETL
278. 6.b.16_SQL Server Integration Services (SSIS)
279. 6.b.17_SAS Data Integration
280. 6.b.18_Qlik Sense
281. 6.b.19_Knime
282. 6.b.20_Databricks
283. 6.b.21_Não utilizo ferramentas de ETL
284. 6.c_possui_data_lake
285. 6.d_tecnologia_data_lake
286. 6.e_possui_data_warehouse
287. 6.f_tecnologia_data_warehouse
288. 6.g_ferramentas_de_qualidade_de_dados_(dia_a_dia)
289. 6.h_maior_tempo_gasto_como_de
290. 6.h.1_Desenvolvendo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.
291. 6.h.2_Realizando construções de ETL\s em ferramentas como Pentaho, Talend, Dataflow etc.
292. 6.h.3_Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.
293. 6.h.4_Atuando na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.
294. 6.h.5_Modelando soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.
295. 6.h.6_Desenvolvendo/cuidando da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.
296. 6.h.7_Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.
297. 6.h.8_Cuidando da qualidade dos dados, metadados e dicionário de dados.
298. 6.h.9_Nenhuma das opções listadas refletem meu dia a dia.
299. 7.a_rotina_como_da
300. 7.a.1_Processo e analiso dados utilizando linguagens de programação como Python, R etc.
301. 7.a.2_Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.
302. 7.a.3_Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.
303. 7.a.4_Utilizo API\s para extrair dados e complementar minhas análises.
304. 7.a.5_Realizo experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.
305. 7.a.6_Desenvolvo/cuido da manutenção de ETL\s utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.
306. 7.a.7_Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts etc.
307. 7.a.8_Desenvolvo/cuido da manutenção de planilhas para atender as áreas de negócio.
308. 7.a.9_Utilizo ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises de dados.
309. 7.a.10_Nenhuma das opções listadas refletem meu dia a dia.
310. 7.b_ferramentas_etl_da
311. 7.b.1_Scripts Python
312. 7.b.2_SQL & Stored Procedures
313. 7.b.3_Apache Airflow
314. 7.b.4_Apache NiFi
315. 7.b.5_Luigi
316. 7.b.6_AWS Glue
317. 7.b.7_Talend
318. 7.b.8_Pentaho
319. 7.b.9_Alteryx
320. 7.b.10_Stitch
321. 7.b.11_Fivetran
322. 7.b.12_Google Dataflow
323. 7.b.13_Oracle Data Integrator
324. 7.b.14_IBM DataStage
325. 7.b.15_SAP BW ETL
326. 7.b.16_SQL Server Integration Services (SSIS)
327. 7.b.17_SAS Data Integration
328. 7.b.18_Qlik Sense
329. 7.b.19_Knime
330. 7.b.20_Databricks
331. 7.b.21_Não utilizo ferramentas de ETL
332. 7.c_ferramentas_autonomia_area_de_negocios
333. 7.c.1_Ferramentas de AutoML como H2O.ai, Data Robot, BigML etc.
334. 7.c.2_"Point and Click" Analytics como Alteryx, Knime, Rapidminer etc.
335. 7.c.3_Product metricts & Insights como Mixpanel, Amplitude, Adobe Analytics.
336. 7.c.4_Ferramentas de análise dentro de ferramentas de CRM como Salesforce Einstein Anaytics ou Zendesk dashboards.
337. 7.c.5_Minha empresa não utiliza essas ferramentas.
338. 7.c.6_Não sei informar.
339. 7.d_maior_tempo_gasto_como_da
340. 7.d.1_Processando e analisando dados utilizando linguagens de programação como Python, R etc.
341. 7.d.2_Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.
342. 7.d.3_Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.
343. 7.d.4_Utilizando API's para extrair dados e complementar minhas análises.
344. 7.d.5_Realizando experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.
345. 7.d.6_Desenvolvendo/cuidando da manutenção de ETL's utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.
346. 7.d.7_Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.
347. 7.d.8_Desenvolvendo/cuidando da manutenção de planilhas para atender as áreas de negócio.
348. 7.d.9_Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises de dados.
349. 7.d.10_Nenhuma das opções listadas refletem meu dia a dia.
350. 8.a_rotina_como_ds
351. 8.a.1_Estudos Ad-hoc com o objetivo de confirmar hipóteses, realizar modelos preditivos, forecasts, análise de cluster para resolver problemas pontuais e responder perguntas das áreas de negócio.
352. 8.a.2_Sou responsável pela coleta e limpeza dos dados que uso para análise e modelagem.
353. 8.a.3_Sou responsável por entrar em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.
354. 8.a.4_Desenvolvo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).
355. 8.a.5_Sou responsável por colocar modelos em produção, criar os pipelines de dados, APIs de consumo e monitoramento.
356. 8.a.6_Cuido da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.
357. 8.a.7_Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc
358. 8.a.8_Utilizo ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.
359. 8.a.9_Crio e dou manutenção em ETLs, DAGs e automações de pipelines de dados.
360. 8.a.10_Crio e gerencio soluções de Feature Store e cultura de MLOps.
361. 8.a.11_Sou responsável por criar e manter a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)
362. 8.a.12_Treino e aplico LLM's para solucionar problemas de negócio.
363. 8.b_tecnicas_e_metodos_ds
364. 8.b.1_Utilizo modelos de regressão (linear, logística, GLM).
365. 8.b.2_Utilizo redes neurais ou modelos baseados em árvore para criar modelos de classificação.
366. 8.b.3_Desenvolvo sistemas de recomendação (RecSys).
367. 8.b.4_Utilizo métodos estatísticos Bayesianos para analisar dados.
368. 8.b.5_Utilizo técnicas de NLP (Natural Language Processing) para análisar dados não-estruturados.
369. 8.b.6_Utilizo métodos estatísticos clássicos (Testes de hipótese, análise multivariada, sobrevivência, dados longitudinais, inferência estatistica) para analisar dados.
370. 8.b.7_Utilizo cadeias de Markov ou HMM\s para realizar análises de dados.
371. 8.b.8_Desenvolvo técnicas de Clusterização (K-means, Spectral, DBScan etc).
372. 8.b.9_Realizo previsões através de modelos de Séries Temporais (Time Series).
373. 8.b.10_Utilizo modelos de Reinforcement Learning (aprendizado por reforço).
374. 8.b.11_Utilizo modelos de Machine Learning para detecção de fraude.
375. 8.b.12_Utilizo métodos de Visão Computacional.
376. 8.b.13_Utilizo modelos de Detecção de Churn.
377. 8.b.14_Utilizo LLM's para solucionar problemas de negócio.
378. 8.c_tecnologias_ds
379. 8.c.1_Ferramentas de BI (PowerBI, Looker, Tableau, Qlik etc).
380. 8.c.2_Planilhas (Excel, Google Sheets etc).
381. 8.c.3_Ambientes de desenvolvimento local (R-studio, JupyterLab, Anaconda).
382. 8.c.4_Ambientes de desenvolvimento na nuvem (Google Colab, AWS Sagemaker, Kaggle Notebooks etc).
383. 8.c.5_Ferramentas de AutoML (Datarobot, H2O, Auto-Keras etc).
384. 8.c.6_Ferramentas de ETL (Apache Airflow, NiFi, Stitch, Fivetran, Pentaho etc).
385. 8.c.7_Plataformas de Machine Learning (TensorFlow, Azure Machine Learning, Kubeflow etc).
386. 8.c.8_Feature Store (Feast, Hopsworks, AWS Feature Store, Databricks Feature Store etc).
387. 8.c.9_Sistemas de controle de versão (Github, DVC, Neptune, Gitlab etc).
388. 8.c.10_Plataformas de Data Apps (Streamlit, Shiny, Plotly Dash etc).
389. 8.c.11_Ferramentas de estatística avançada como SPSS, SAS, etc.
390. 8.d_maior_tempo_gasto_como_ds
391. 8.d.1_Estudos Ad-hoc com o objetivo de confirmar hipóteses, realizar modelos preditivos, forecasts, análise de cluster para resolver problemas pontuais e responder perguntas das áreas de negócio.
392. 8.d.2_Coletando e limpando dos dados que uso para análise e modelagem.
393. 8.d.3_Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.
394. 8.d.4_Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).
395. 8.d.5_Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.

### Limpando

In [36]:
def limpar_2024(col):
    col = str(col).strip()
    # 1) Arranca o código do início: '7.a.4_', '2.h_', '4.l.1 '
    col = re.sub(r'^\d+(\.[a-zA-Z0-9]+)*[_\s]+', '', col)
    # 2) Mesma normalização que usamos no 2023
    col = col.lower()
    col = ''.join(c for c in unicodedata.normalize('NFD', col)
                  if unicodedata.category(c) != 'Mn')   # tira acentos
    col = col.replace(' ', '_').replace('/', '_').replace('-', '_')
    col = col.replace('?', '').replace('(', '').replace(')', '')
    col = col.replace("'", '').replace('"', '')
    return col

df_2024.columns = [limpar_2024(c) for c in df_2024.columns]

# 3) TRUE/FALSE vira 1/0 (para casar com o que foi feito em 2023!)
df_2024 = df_2024.replace({True: 1, False: 0, 'TRUE': 1, 'FALSE': 0})

# 4) Deduplica as gêmeas (ETL eng/analista etc.), igual foi feito antes
cols = df_2024.columns.tolist()
contador = {}
for i, nome in enumerate(cols):
    if nome in contador:
        contador[nome] += 1
        cols[i] = f"{nome}__{contador[nome]}"
    else:
        contador[nome] = 0
df_2024.columns = cols

print(df_2024.columns[:15].tolist())  # espiada nos nomes limpos

['token', 'data_hora_envio', 'idade', 'faixa_idade', 'genero', 'cor_raca_etnia', 'pcd', 'experiencia_profissional_prejudicada', 'nao_acredito_que_minha_experiencia_profissional_seja_afetada', 'sim,_devido_a_minha_cor_raca_etnia', 'sim,_devido_a_minha_identidade_de_genero', 'sim,_devido_ao_fato_de_ser_pcd', 'uf_onde_mora', 'quantidade_de_oportunidades_de_emprego_vagas_recebidas', 'senioridade_das_vagas_recebidas_em_relacao_a_sua_experiencia']

In [37]:
for i, coluna in enumerate(df_2024.columns):
    print(f'{i}. {coluna}')

0. token
1. data_hora_envio
2. idade
3. faixa_idade
4. genero
5. cor_raca_etnia
6. pcd
7. experiencia_profissional_prejudicada
8. nao_acredito_que_minha_experiencia_profissional_seja_afetada
9. sim,_devido_a_minha_cor_raca_etnia
10. sim,_devido_a_minha_identidade_de_genero
11. sim,_devido_ao_fato_de_ser_pcd
12. uf_onde_mora
13. quantidade_de_oportunidades_de_emprego_vagas_recebidas
14. senioridade_das_vagas_recebidas_em_relacao_a_sua_experiencia
15. aprovacao_em_processos_seletivos_entrevistas
16. oportunidades_de_progressao_de_carreira
17. velocidade_de_progressao_de_carreira
18. nivel_de_cobranca_no_trabalho_stress_no_trabalho
19. atencao_dada_pelas_pessoas_diante_das_minhas_opinioes_e_ideias
20. relacao_com_outras_pessoas_da_empresa,_em_momentos_de_trabalho
21. relacao_com_outras_pessoas_da_empresa,_em_momentos_de_integracao_e_outros_momentos_fora_do_trabalho
22. regiao_onde_mora
23. aspectos_prejudicados
24. uf_de_origem
25. regiao_de_origem
26. vive_no_brasil
27. pais_onde_mora
28. estado_onde_mora
29. vive_no_estado_de_formacao
30. estado_de_origem
31. nivel_de_ensino
32. area_de_formacao
33. situacao_de_trabalho
34. setor
35. numero_de_funcionarios
36. atua_como_gestor
37. cargo_como_gestor
38. cargo_atual
39. nivel
40. faixa_salarial
41. tempo_de_experiencia_em_dados
42. tempo_de_experiencia_em_ti
43. satisfeito_atualmente
44. remuneracao_salario
45. beneficios
46. proposito_do_trabalho_e_da_empresa
47. flexibilidade_de_trabalho_remoto
48. ambiente_e_clima_de_trabalho
49. oportunidade_de_aprendizado_e_trabalhar_com_referencias
50. oportunidades_de_crescimento
51. maturidade_da_empresa_em_termos_de_tecnologia_e_dados
52. relacao_com_os_gestores_e_lideres
53. reputacao_que_a_empresa_tem_no_mercado
54. gostaria_de_trabalhar_em_outra_area
55. motivo_insatisfacao
56. participou_de_entrevistas_ultimos_6m
57. planos_de_mudar_de_emprego_6m
58. criterios_para_escolha_de_emprego
59. remuneracao_salario__1
60. beneficios__1
61. proposito_do_trabalho_e_da_empresa__1
62. flexibilidade_de_trabalho_remoto__1
63. ambiente_e_clima_de_trabalho__1
64. oportunidade_de_aprendizado_e_trabalhar_com_referencias__1
65. plano_de_carreira_e_oportunidades_de_crescimento
66. maturidade_da_empresa_em_termos_de_tecnologia_e_dados__1
67. qualidade_dos_gestores_e_lideres
68. reputacao_que_a_empresa_tem_no_mercado__1
69. empresa_passou_por_layoff_em_2024
70. modelo_de_trabalho_atual
71. modelo_de_trabalho_ideal
72. atitude_em_caso_de_retorno_presencial
73. numero_de_pessoas_em_dados
74. cargos_no_time_de_dados_da_empresa
75. analytics_engineer
76. engenharia_de_dados_data_engineer
77. analista_de_dados_data_analyst
78. cientista_de_dados_data_scientist
79. database_administrator_dba
80. analista_de_business_intelligence_bi
81. arquiteto_de_dados_data_architect
82. data_product_manager_dpm
83. business_analyst
84. ml_engineer_ai_engineer
85. responsabilidades_como_gestor
86. pensar_na_visao_de_longo_prazo_de_dados
87. organizacao_de_treinamentos_e_iniciativas
88. atracao,_selecao_e_contratacao
89. decisao_sobre_contratacao_de_ferramentas
90. gestor_da_equipe_de_engenharia_de_dados
91. gestor_da_equipe_de_estudos,_relatorios
92. gestor_da_equipe_de_inteligencia_artificial_e_machine_learning
93. apesar_de_ser_gestor_ainda_atuo_na_parte_tecnica
94. gestao_de_projetos_de_dados
95. gestao_de_produtos_de_dados
96. gestao_de_pessoas
97. desafios_como_gestor
98. contratar_talentos
99. reter_talentos
100. convencer_a_empresa_a_aumentar_investimentos
101. gestao_de_equipes_no_ambiente_remoto
102. gestao_de_projetos_envolvendo_areas_multidisciplinares
103. organizar_as_informacoes_com_qualidade_e_confiabilidade
104. processar_e_armazenar_um_alto_volume_de_dados
105. gerar_valor_para_as_areas_de_negocios
106. desenvolver_e_manter_modelos_machine_learning_em_producao
107. gerenciar_a_expectativa_das_areas
108. garantir_a_manutencao_dos_projetos_e_modelos_em_producao
109. conseguir_levar_inovacao_para_a_empresa
110. garantir_roi_em_projetos_de_dados
111. dividir_o_tempo_entre_entregas_tecnicas_e_gestao
112. ai_generativa_e_llm_e_uma_prioridade
113. tipo_de_uso_de_ai_generativa_e_llm_na_empresa
114. colaboradores_usando_ai_generativa_de_forma_independente_e_descentralizada
115. direcionamento_centralizado_do_uso_de_ai_generativa
116. desenvolvedores_utilizando_copilots
117. ai_generativa_e_llms_para_melhorar_produtos_externos_para_os_clientes_finais
118. ai_generativa_e_llms_para_melhorar_produtos_internos_para_os_colaboradores
119. ia_generativa_e_llms_como_principal_frente_do_negocio
120. ia_generativa_e_llms_nao_e_prioridade
121. nao_sei_opinar_sobre_o_uso_de_ia_generativa_e_llms_na_empresa
122. motivos_para_nao_usar_ai_generativa_e_llm
123. falta_de_compreensao_dos_casos_de_uso
124. falta_de_confiabilidade_das_saidas_alucinacao_dos_modelos
125. incerteza_em_relacao_a_regulamentacao
126. preocupacoes_com_seguranca_e_privacidade_de_dados
127. retorno_sobre_investimento_roi_nao_comprovado_de_ia_generativa
128. dados_da_empresa_nao_estao_prontos_para_uso_de_ia_generativa
129. falta_de_expertise_ou_falta_de_recursos
130. alta_direcao_da_empresa_nao_ve_valor_ou_nao_ve_como_prioridade
131. preocupacoes_com_propriedade_intelectual
132. funcao_de_atuacao
133. atuacao_em_dados
134. fontes_de_dados_dia_a_dia
135. dados_relacionais_estruturados_em_bancos_sql
136. dados_armazenados_em_bancos_nosql
137. imagens
138. textos_documentos
139. videos
140. audios
141. planilhas
142. dados_georeferenciados
143. fonte_de_dado_mais_usada
144. dados_relacionais_estruturados_em_bancos_sql__1
145. dados_armazenados_em_bancos_nosql__1
146. imagens__1
147. textos_documentos__1
148. videos__1
149. audios__1
150. planilhas__1
151. dados_georeferenciados__1
152. linguagem_de_programacao_dia_a_dia
153. sql
154. r
155. python
156. c_c++_c#
157. .net
158. java
159. julia
160. sas_stata
161. visual_basic_vba
162. scala
163. matlab
164. rust
165. php
166. javascript
167. nao_utilizo_nenhuma_das_linguagens_listadas
168. linguagem_mais_usada
169. linguagem_preferida
170. banco_de_dados_dia_a_dia
171. mysql
172. oracle
173. sql_server
174. amazon_aurora_ou_rds
175. dynamodb
176. coachdb
177. cassandra
178. mongodb
179. mariadb
180. datomic
181. s3
182. postgresql
183. elasticsearch
184. db2
185. microsoft_access
186. sqlite
187. sybase
188. firebase
189. vertica
190. redis
191. neo4j
192. google_bigquery
193. google_firestore
194. amazon_redshift
195. amazon_athena
196. snowflake
197. databricks
198. hbase
199. presto
200. splunk
201. sap_hana
202. hive
203. firebird
204. cloud_dia_a_dia
205. amazon_web_services_aws
206. google_cloud_gcp
207. azure_microsoft
208. oracle_cloud
209. ibm
210. servidores_on_premise_nao_utilizamos_cloud
211. cloud_propria
212. cloud_preferida
213. ferramenta_de_bi_dia_a_dia
214. microsoft_powerbi
215. qlik_view_qlik_sense
216. tableau
217. metabase
218. superset
219. redash
220. looker
221. looker_studiogoogle_data_studio
222. amazon_quicksight
223. alteryx
224. sap_business_objects_sap_analytics
225. oracle_business_intelligence
226. salesforce_einstein_analytics
227. sas_visual_analytics
228. grafana
229. pentaho
230. fazemos_todas_as_analises_utilizando_apenas_excel_ou_planilhas_do_google
231. nao_utilizo_nenhuma_ferramenta_de_bi_no_trabalho
232. ferramenta_de_bi_preferida
233. tipo_de_uso_de_ai_generativa_e_llm_na_empresa__1
234. colaboradores_usando_ai_generativa_de_forma_independente_e_descentralizada__1
235. direcionamento_centralizado_do_uso_de_ai_generativa__1
236. desenvolvedores_utilizando_copilots__1
237. ai_generativa_e_llms_para_melhorar_produtos_externos_para_os_clientes_finais__1
238. ai_generativa_e_llms_para_melhorar_produtos_internos_para_os_colaboradores__1
239. ia_generativa_e_llms_como_principal_frente_do_negocio__1
240. ia_generativa_e_llms_nao_e_prioridade__1
241. nao_sei_opinar_sobre_o_uso_de_ia_generativa_e_llms_na_empresa__1
242. usa_chatgpt_ou_copilot_no_trabalho
243. nao_uso_solucoes_de_ai_generativa_com_foco_em_produtividade
244. uso_solucoes_gratuitas_de_ai_generativa_com_foco_em_produtividade
245. uso_e_pago_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade
246. a_empresa_que_trabalho_paga_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade
247. uso_solucoes_do_tipo_copilot
248. objetivo_na_area_de_dados
249. oportunidade_buscada
250. tempo_em_busca_de_oportunidade
251. experiencia_em_processos_seletivos
252. rotina_como_de
253. desenvolvo_pipelines_de_dados_utilizando_linguagens_de_programacao_como_python,_scala,_java_etc.
254. realizo_construcoes_de_etls_em_ferramentas_como_pentaho,_talend,_dataflow_etc.
255. crio_consultas_atraves_da_linguagem_sql_para_exportar_informacoes_e_compartilhar_com_as_areas_de_negocio.
256. atuo_na_integracao_de_diferentes_fontes_de_dados_atraves_de_plataformas_proprietarias_como_stitch_data,_fivetran_etc.
257. modelo_solucoes_de_arquitetura_de_dados,_criando_componentes_de_ingestao_de_dados,_transformacao_e_recuperacao_da_informacao.
258. desenvolvo_cuido_da_manutencao_de_repositorios_de_dados_baseados_em_streaming_de_eventos_como_data_lakes_e_data_lakehouses.
259. atuo_na_modelagem_dos_dados,_com_o_objetivo_de_criar_conjuntos_de_dados_como_data_warehouses,_data_marts,_datasets_etc.
260. cuido_da_qualidade_dos_dados,_metadados_e_dicionario_de_dados.
261. nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.
262. ferramentas_etl_de
263. scripts_python
264. sql_&_stored_procedures
265. apache_airflow
266. apache_nifi
267. luigi
268. aws_glue
269. talend
270. pentaho__1
271. alteryx__1
272. stitch
273. fivetran
274. google_dataflow
275. oracle_data_integrator
276. ibm_datastage
277. sap_bw_etl
278. sql_server_integration_services_ssis
279. sas_data_integration
280. qlik_sense
281. knime
282. databricks__1
283. nao_utilizo_ferramentas_de_etl
284. possui_data_lake
285. tecnologia_data_lake
286. possui_data_warehouse
287. tecnologia_data_warehouse
288. ferramentas_de_qualidade_de_dados_dia_a_dia
289. maior_tempo_gasto_como_de
290. desenvolvendo_pipelines_de_dados_utilizando_linguagens_de_programacao_como_python,_scala,_java_etc.
291. realizando_construcoes_de_etl\s_em_ferramentas_como_pentaho,_talend,_dataflow_etc.
292. criando_consultas_atraves_da_linguagem_sql_para_exportar_informacoes_e_compartilhar_com_as_areas_de_negocio.
293. atuando_na_integracao_de_diferentes_fontes_de_dados_atraves_de_plataformas_proprietarias_como_stitch_data,_fivetran_etc.
294. modelando_solucoes_de_arquitetura_de_dados,_criando_componentes_de_ingestao_de_dados,_transformacao_e_recuperacao_da_informacao.
295. desenvolvendo_cuidando_da_manutencao_de_repositorios_de_dados_baseados_em_streaming_de_eventos_como_data_lakes_e_data_lakehouses.
296. atuando_na_modelagem_dos_dados,_com_o_objetivo_de_criar_conjuntos_de_dados_como_data_warehouses,_data_marts,_datasets_etc.
297. cuidando_da_qualidade_dos_dados,_metadados_e_dicionario_de_dados.
298. nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.__1
299. rotina_como_da
300. processo_e_analiso_dados_utilizando_linguagens_de_programacao_como_python,_r_etc.
301. realizo_construcoes_de_dashboards_em_ferramentas_de_bi_como_powerbi,_tableau,_looker,_qlik_etc.
302. crio_consultas_atraves_da_linguagem_sql_para_exportar_informacoes_e_compartilhar_com_as_areas_de_negocio.__1
303. utilizo_api\s_para_extrair_dados_e_complementar_minhas_analises.
304. realizo_experimentos_e_estudos_utilizando_metodologias_estatisticas_como_teste_de_hipotese,_modelos_de_regressao_etc.
305. desenvolvo_cuido_da_manutencao_de_etl\s_utilizando_tecnologias_como_talend,_pentaho,_airflow,_dataflow_etc.
306. atuo_na_modelagem_dos_dados,_com_o_objetivo_de_criar_conjuntos_de_dados_como_data_warehouses,_data_marts_etc.
307. desenvolvo_cuido_da_manutencao_de_planilhas_para_atender_as_areas_de_negocio.
308. utilizo_ferramentas_avancadas_de_estatistica_como_sas,_spss,_stata_etc,_para_realizar_analises_de_dados.
309. nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.__2
310. ferramentas_etl_da
311. scripts_python__1
312. sql_&_stored_procedures__1
313. apache_airflow__1
314. apache_nifi__1
315. luigi__1
316. aws_glue__1
317. talend__1
318. pentaho__2
319. alteryx__2
320. stitch__1
321. fivetran__1
322. google_dataflow__1
323. oracle_data_integrator__1
324. ibm_datastage__1
325. sap_bw_etl__1
326. sql_server_integration_services_ssis__1
327. sas_data_integration__1
328. qlik_sense__1
329. knime__1
330. databricks__2
331. nao_utilizo_ferramentas_de_etl__1
332. ferramentas_autonomia_area_de_negocios
333. ferramentas_de_automl_como_h2o.ai,_data_robot,_bigml_etc.
334. point_and_click_analytics_como_alteryx,_knime,_rapidminer_etc.
335. product_metricts_&_insights_como_mixpanel,_amplitude,_adobe_analytics.
336. ferramentas_de_analise_dentro_de_ferramentas_de_crm_como_salesforce_einstein_anaytics_ou_zendesk_dashboards.
337. minha_empresa_nao_utiliza_essas_ferramentas.
338. nao_sei_informar.
339. maior_tempo_gasto_como_da
340. processando_e_analisando_dados_utilizando_linguagens_de_programacao_como_python,_r_etc.
341. realizando_construcoes_de_dashboards_em_ferramentas_de_bi_como_powerbi,_tableau,_looker,_qlik_etc.
342. criando_consultas_atraves_da_linguagem_sql_para_exportar_informacoes_e_compartilhar_com_as_areas_de_negocio.__1
343. utilizando_apis_para_extrair_dados_e_complementar_minhas_analises.
344. realizando_experimentos_e_estudos_utilizando_metodologias_estatisticas_como_teste_de_hipotese,_modelos_de_regressao_etc.
345. desenvolvendo_cuidando_da_manutencao_de_etls_utilizando_tecnologias_como_talend,_pentaho,_airflow,_dataflow_etc.
346. atuando_na_modelagem_dos_dados,_com_o_objetivo_de_criar_conjuntos_de_dados_como_data_warehouses,_data_marts,_datasets_etc.__1
347. desenvolvendo_cuidando_da_manutencao_de_planilhas_para_atender_as_areas_de_negocio.
348. utilizando_ferramentas_avancadas_de_estatistica_como_sas,_spss,_stata_etc,_para_realizar_analises_de_dados.
349. nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.__3
350. rotina_como_ds
351. estudos_ad_hoc_com_o_objetivo_de_confirmar_hipoteses,_realizar_modelos_preditivos,_forecasts,_analise_de_cluster_para_resolver_problemas_pontuais_e_responder_perguntas_das_areas_de_negocio.
352. sou_responsavel_pela_coleta_e_limpeza_dos_dados_que_uso_para_analise_e_modelagem.
353. sou_responsavel_por_entrar_em_contato_com_os_times_de_negocio_para_definicao_do_problema,_identificar_a_solucao_e_apresentacao_de_resultados.
354. desenvolvo_modelos_de_machine_learning_com_o_objetivo_de_colocar_em_producao_em_sistemas_produtos_de_dados.
355. sou_responsavel_por_colocar_modelos_em_producao,_criar_os_pipelines_de_dados,_apis_de_consumo_e_monitoramento.
356. cuido_da_manutencao_de_modelos_de_machine_learning_ja_em_producao,_atuando_no_monitoramento,_ajustes_e_refatoracao_quando_necessario.
357. realizo_construcoes_de_dashboards_em_ferramentas_de_bi_como_powerbi,_tableau,_looker,_qlik,_etc
358. utilizo_ferramentas_avancadas_de_estatistica_como_sas,_spss,_stata_etc,_para_realizar_analises.
359. crio_e_dou_manutencao_em_etls,_dags_e_automacoes_de_pipelines_de_dados.
360. crio_e_gerencio_solucoes_de_feature_store_e_cultura_de_mlops.
361. sou_responsavel_por_criar_e_manter_a_infra_que_meus_modelos_e_solucoes_rodam_clusters,_servidores,_api,_containers,_etc.
362. treino_e_aplico_llms_para_solucionar_problemas_de_negocio.
363. tecnicas_e_metodos_ds
364. utilizo_modelos_de_regressao_linear,_logistica,_glm.
365. utilizo_redes_neurais_ou_modelos_baseados_em_arvore_para_criar_modelos_de_classificacao.
366. desenvolvo_sistemas_de_recomendacao_recsys.
367. utilizo_metodos_estatisticos_bayesianos_para_analisar_dados.
368. utilizo_tecnicas_de_nlp_natural_language_processing_para_analisar_dados_nao_estruturados.
369. utilizo_metodos_estatisticos_classicos_testes_de_hipotese,_analise_multivariada,_sobrevivencia,_dados_longitudinais,_inferencia_estatistica_para_analisar_dados.
370. utilizo_cadeias_de_markov_ou_hmm\s_para_realizar_analises_de_dados.
371. desenvolvo_tecnicas_de_clusterizacao_k_means,_spectral,_dbscan_etc.
372. realizo_previsoes_atraves_de_modelos_de_series_temporais_time_series.
373. utilizo_modelos_de_reinforcement_learning_aprendizado_por_reforco.
374. utilizo_modelos_de_machine_learning_para_deteccao_de_fraude.
375. utilizo_metodos_de_visao_computacional.
376. utilizo_modelos_de_deteccao_de_churn.
377. utilizo_llms_para_solucionar_problemas_de_negocio.
378. tecnologias_ds
379. ferramentas_de_bi_powerbi,_looker,_tableau,_qlik_etc.
380. planilhas_excel,_google_sheets_etc.
381. ambientes_de_desenvolvimento_local_r_studio,_jupyterlab,_anaconda.
382. ambientes_de_desenvolvimento_na_nuvem_google_colab,_aws_sagemaker,_kaggle_notebooks_etc.
383. ferramentas_de_automl_datarobot,_h2o,_auto_keras_etc.
384. ferramentas_de_etl_apache_airflow,_nifi,_stitch,_fivetran,_pentaho_etc.
385. plataformas_de_machine_learning_tensorflow,_azure_machine_learning,_kubeflow_etc.
386. feature_store_feast,_hopsworks,_aws_feature_store,_databricks_feature_store_etc.
387. sistemas_de_controle_de_versao_github,_dvc,_neptune,_gitlab_etc.
388. plataformas_de_data_apps_streamlit,_shiny,_plotly_dash_etc.
389. ferramentas_de_estatistica_avancada_como_spss,_sas,_etc.
390. maior_tempo_gasto_como_ds
391. estudos_ad_hoc_com_o_objetivo_de_confirmar_hipoteses,_realizar_modelos_preditivos,_forecasts,_analise_de_cluster_para_resolver_problemas_pontuais_e_responder_perguntas_das_areas_de_negocio.__1
392. coletando_e_limpando_dos_dados_que_uso_para_analise_e_modelagem.
393. entrando_em_contato_com_os_times_de_negocio_para_definicao_do_problema,_identificar_a_solucao_e_apresentacao_de_resultados.
394. desenvolvendo_modelos_de_machine_learning_com_o_objetivo_de_colocar_em_producao_em_sistemas_produtos_de_dados.
395. colocando_modelos_em_producao,_criando_os_pipelines_de_dados,_apis_de_consumo_e_monitoramento.
396. cuidando_da_manutencao_de_modelos_de_machine_learning_ja_em_producao,_atuando_no_monitoramento,_ajustes_e_refatoracao_quando_necessario.
397. realizando_construcoes_de_dashboards_em_ferramentas_de_bi_como_powerbi,_tableau,_looker,_qlik,_etc.
398. utilizando_ferramentas_avancadas_de_estatistica_como_sas,_spss,_stata_etc,_para_realizar_analises.
399. criando_e_dando_manutencao_em_etls,_dags_e_automacoes_de_pipelines_de_dados.
400. criando_e_gerenciando_solucoes_de_feature_store_e_cultura_de_mlops.
401. criando_e_mantendo_a_infra_que_meus_modelos_e_solucoes_rodam_clusters,_servidores,_api,_containers,_etc.
402. treinando_e_aplicando_llms_para_solucionar_problemas_de_negocio.

In [38]:
colunas_2023 = df_silver_2023.columns.tolist()

coincidem = [c for c in colunas_2023 if c in df_2024.columns]
sumiram   = [c for c in colunas_2023 if c not in df_2024.columns]

print(f"✅ {len(coincidem)} colunas casaram sozinhas!")
print(f"🔴 {len(sumiram)} precisam de 'tradução':")
print(sumiram)

✅ 139 colunas casaram sozinhas!
🔴 53 precisam de 'tradução':
['id', 'experiencia_prejudicada_devido_a_minha_identidade_de_genero', 'experiencia_prejudicada_devido_a_minha_cor_raca_etnia', 'experiencia_prejudicada_devido_ao_fato_de_ser_pcd', 'qual_sua_situacao_atual_de_trabalho', 'quanto_tempo_de_experiencia_na_area_de_dados_voce_tem', 'quanto_tempo_de_experiencia_na_area_de_ti_engenharia_de_software_voce_teve_antes_de_comecar_a_trabalhar_na_area_de_dados', 'atualmente_qual_a_sua_forma_de_trabalho', 'qual_a_forma_de_trabalho_ideal_para_voce', 'caso_sua_empresa_decida_pelo_modelo_100pct_presencial_qual_sera_sua_atitude', 'voce_esta_satisfeito_na_sua_empresa_atual', 'qual_o_principal_motivo_da_sua_insatisfacao_com_a_empresa_atual', 'falta_de_oportunidade_de_crescimento_no_emprego_atual', 'salario_atual_nao_corresponde_ao_mercado', 'nao_tenho_uma_boa_relacao_com_meu_lider_gestor', 'gostaria_de_trabalhar_em_em_outra_area_de_atuacao', 'gostaria_de_receber_mais_beneficios', 'o_clima_de_trabalho_ambiente_nao_e_bom', 'falta_de_maturidade_analitica_na_empresa', 'oportunidade_de_aprendizado_e_trabalhar_com_referencias_na_area', 'plano_de_carreira_e_oportunidades_de_crescimento_profissional', 'a_contratar_novos_talentos', 'b_reter_talentos', 'c_convencer_a_empresa_a_aumentar_os_investimentos_na_area_de_dados', 'd_gestao_de_equipes_no_ambiente_remoto', 'e_gestao_de_projetos_envolvendo_areas_multidisciplinares_da_empresa', 'f_organizar_as_informacoes_e_garantir_a_qualidade_e_confiabilidade', 'g_conseguir_processar_e_armazenar_um_alto_volume_de_dados', 'h_conseguir_gerar_valor_para_as_areas_de_negocios_atraves_de_estudos_e_experimentos', 'i_desenvolver_e_manter_modelos_machine_learning_em_producao', 'j_gerenciar_a_expectativa_das_areas_de_negocio_em_relacao_as_entregas_das_equipes_de_dados', 'k_garantir_a_manutencao_dos_projetos_e_modelos_em_producao,_em_meio_ao_crescimento_da_empresa', 'conseguir_levar_inovacao_para_a_empresa_atraves_dos_dados', 'garantir_retorno_do_investimento_roi_em_projetos_de_dados', 'ai_generativa_e_uma_prioridade_em_sua_empresa', 'ai_generativa_e_llms_para_melhorar_produtos_externos', 'atuacao', 'nao_utilizo_nenhuma_linguagem', 'entre_as_linguagens_listadas_abaixo,_qual_e_a_que_voce_mais_utiliza_no_trabalho', 'ferramenta_de_bi_utilizada_no_dia_a_dia', 'mode', 'microstrategy', 'ibm_analytics_cognos', 'birst', 'tibco_spotfire', 'utiliza_chatgpt_ou_llms_no_trabalho', 'sua_organizacao_possui_um_data_lake', 'sua_organizacao_possui_um_data_warehouse', 'ambientes_de_desenvolvimento_na_nuvem_google_colab,_aws_sagemaker,_kaggle_notebooks_etc', 'plataformas_de_machine_learning_tensorflow,_azure_machine_learning,_kubeflow_etc', 'feature_store_feast,_hopsworks,_aws_feature_store,_databricks_feature_store_etc', 'sistemas_de_controle_de_versao_github,_dvc,_neptune,_gitlab_etc', 'plataformas_de_data_apps_streamlit,_shiny,_plotly_dash_etc']

In [39]:
# Tradução: nome_2023 -> nome_2024 (o código vai inverter para unificar os nomes!)
traducao = {
    # --- Certezas (vi no cabeçalho do 2024) ---
    'id': 'token',
    'experiencia_prejudicada_devido_a_minha_identidade_de_genero': 'sim,_devido_a_minha_identidade_de_genero',
    'experiencia_prejudicada_devido_a_minha_cor_raca_etnia': 'sim,_devido_a_minha_cor_raca_etnia',
    'experiencia_prejudicada_devido_ao_fato_de_ser_pcd': 'sim,_devido_ao_fato_de_ser_pcd',
    'qual_sua_situacao_atual_de_trabalho': 'situacao_de_trabalho',
    'quanto_tempo_de_experiencia_na_area_de_dados_voce_tem': 'tempo_de_experiencia_em_dados',
    'quanto_tempo_de_experiencia_na_area_de_ti_engenharia_de_software_voce_teve_antes_de_comecar_a_trabalhar_na_area_de_dados': 'tempo_de_experiencia_em_ti',
    'voce_esta_satisfeito_na_sua_empresa_atual': 'satisfeito_atualmente',
    'qual_o_principal_motivo_da_sua_insatisfacao_com_a_empresa_atual': 'motivo_insatisfacao',

    # --- testes ---
    'atualmente_qual_a_sua_forma_de_trabalho': 'forma_de_trabalho_atual',
    'qual_a_forma_de_trabalho_ideal_para_voce': 'forma_de_trabalho_ideal',
    'atuacao': 'atuacao_no_dia_a_dia',
    'nao_utilizo_nenhuma_linguagem': 'nenhuma_linguagem',
    'entre_as_linguagens_listadas_abaixo,_qual_e_a_que_voce_mais_utiliza_no_trabalho': 'linguagem_mais_utilizada',
    'ferramenta_de_bi_utilizada_no_dia_a_dia': 'ferramenta_de_bi_do_dia_a_dia',
    'utiliza_chatgpt_ou_llms_no_trabalho': 'usa_chatgpt_ou_llms_no_trabalho',
    'ai_generativa_e_uma_prioridade_em_sua_empresa': 'ia_generativa_e_uma_prioridade_em_sua_empresa',
    'ai_generativa_e_llms_para_melhorar_produtos_externos': 'ia_generativa_e_llms_para_melhorar_produtos_externos',
    'a_contratar_novos_talentos': 'contratar_novos_talentos',
    'b_reter_talentos': 'reter_talentos',
    'c_convencer_a_empresa_a_aumentar_os_investimentos_na_area_de_dados': 'convencer_a_empresa_a_aumentar_os_investimentos_na_area_de_dados',
}

# Aplicar SÓ as traduções que existem no 2024 (renomeia 2024 -> nome do 2023)
traducao_valida = {k: v for k, v in traducao.items() if v in df_2024.columns}
df_2024 = df_2024.rename(columns={v: k for k, v in traducao_valida.items()})
print(f" {len(traducao_valida)} traduções aplicadas!")

# --- Raio-X de novo ---
coincidem = [c for c in colunas_2023 if c in df_2024.columns]
sumiram   = [c for c in colunas_2023 if c not in df_2024.columns]
novas     = [c for c in df_2024.columns if c not in colunas_2023]

print(f"✅ {len(coincidem)} casaram!")
print(f"🔴 Ainda sumidas: {len(sumiram)}")
print(sumiram)
print(f"\n🟢 Novas no 2024 (para eu ver o que virou o quê):")
print(novas)

 10 traduções aplicadas!
✅ 149 casaram!
🔴 Ainda sumidas: 43
['atualmente_qual_a_sua_forma_de_trabalho', 'qual_a_forma_de_trabalho_ideal_para_voce', 'caso_sua_empresa_decida_pelo_modelo_100pct_presencial_qual_sera_sua_atitude', 'falta_de_oportunidade_de_crescimento_no_emprego_atual', 'salario_atual_nao_corresponde_ao_mercado', 'nao_tenho_uma_boa_relacao_com_meu_lider_gestor', 'gostaria_de_trabalhar_em_em_outra_area_de_atuacao', 'gostaria_de_receber_mais_beneficios', 'o_clima_de_trabalho_ambiente_nao_e_bom', 'falta_de_maturidade_analitica_na_empresa', 'oportunidade_de_aprendizado_e_trabalhar_com_referencias_na_area', 'plano_de_carreira_e_oportunidades_de_crescimento_profissional', 'a_contratar_novos_talentos', 'c_convencer_a_empresa_a_aumentar_os_investimentos_na_area_de_dados', 'd_gestao_de_equipes_no_ambiente_remoto', 'e_gestao_de_projetos_envolvendo_areas_multidisciplinares_da_empresa', 'f_organizar_as_informacoes_e_garantir_a_qualidade_e_confiabilidade', 'g_conseguir_processar_e_armazenar_um_alto_volume_de_dados', 'h_conseguir_gerar_valor_para_as_areas_de_negocios_atraves_de_estudos_e_experimentos', 'i_desenvolver_e_manter_modelos_machine_learning_em_producao', 'j_gerenciar_a_expectativa_das_areas_de_negocio_em_relacao_as_entregas_das_equipes_de_dados', 'k_garantir_a_manutencao_dos_projetos_e_modelos_em_producao,_em_meio_ao_crescimento_da_empresa', 'conseguir_levar_inovacao_para_a_empresa_atraves_dos_dados', 'garantir_retorno_do_investimento_roi_em_projetos_de_dados', 'ai_generativa_e_uma_prioridade_em_sua_empresa', 'ai_generativa_e_llms_para_melhorar_produtos_externos', 'atuacao', 'nao_utilizo_nenhuma_linguagem', 'entre_as_linguagens_listadas_abaixo,_qual_e_a_que_voce_mais_utiliza_no_trabalho', 'ferramenta_de_bi_utilizada_no_dia_a_dia', 'mode', 'microstrategy', 'ibm_analytics_cognos', 'birst', 'tibco_spotfire', 'utiliza_chatgpt_ou_llms_no_trabalho', 'sua_organizacao_possui_um_data_lake', 'sua_organizacao_possui_um_data_warehouse', 'ambientes_de_desenvolvimento_na_nuvem_google_colab,_aws_sagemaker,_kaggle_notebooks_etc', 'plataformas_de_machine_learning_tensorflow,_azure_machine_learning,_kubeflow_etc', 'feature_store_feast,_hopsworks,_aws_feature_store,_databricks_feature_store_etc', 'sistemas_de_controle_de_versao_github,_dvc,_neptune,_gitlab_etc', 'plataformas_de_data_apps_streamlit,_shiny,_plotly_dash_etc']

🟢 Novas no 2024 (para eu ver o que virou o quê):
['data_hora_envio', 'experiencia_profissional_prejudicada', 'nao_acredito_que_minha_experiencia_profissional_seja_afetada', 'velocidade_de_progressao_de_carreira', 'nivel_de_cobranca_no_trabalho_stress_no_trabalho', 'atencao_dada_pelas_pessoas_diante_das_minhas_opinioes_e_ideias', 'relacao_com_outras_pessoas_da_empresa,_em_momentos_de_trabalho', 'relacao_com_outras_pessoas_da_empresa,_em_momentos_de_integracao_e_outros_momentos_fora_do_trabalho', 'aspectos_prejudicados', 'uf_de_origem', 'regiao_de_origem', 'vive_no_brasil', 'pais_onde_mora', 'vive_no_estado_de_formacao', 'estado_de_origem', 'numero_de_funcionarios', 'atua_como_gestor', 'cargo_como_gestor', 'oportunidade_de_aprendizado_e_trabalhar_com_referencias', 'oportunidades_de_crescimento', 'relacao_com_os_gestores_e_lideres', 'gostaria_de_trabalhar_em_outra_area', 'participou_de_entrevistas_ultimos_6m', 'planos_de_mudar_de_emprego_6m', 'criterios_para_escolha_de_emprego', 'remuneracao_salario__1', 'beneficios__1', 'proposito_do_trabalho_e_da_empresa__1', 'flexibilidade_de_trabalho_remoto__1', 'ambiente_e_clima_de_trabalho__1', 'oportunidade_de_aprendizado_e_trabalhar_com_referencias__1', 'plano_de_carreira_e_oportunidades_de_crescimento', 'maturidade_da_empresa_em_termos_de_tecnologia_e_dados__1', 'reputacao_que_a_empresa_tem_no_mercado__1', 'empresa_passou_por_layoff_em_2024', 'modelo_de_trabalho_atual', 'modelo_de_trabalho_ideal', 'atitude_em_caso_de_retorno_presencial', 'numero_de_pessoas_em_dados', 'cargos_no_time_de_dados_da_empresa', 'analytics_engineer', 'engenharia_de_dados_data_engineer', 'analista_de_dados_data_analyst', 'cientista_de_dados_data_scientist', 'database_administrator_dba', 'analista_de_business_intelligence_bi', 'arquiteto_de_dados_data_architect', 'data_product_manager_dpm', 'business_analyst', 'ml_engineer_ai_engineer', 'responsabilidades_como_gestor', 'pensar_na_visao_de_longo_prazo_de_dados', 'organizacao_de_treinamentos_e_iniciativas', 'atracao,_selecao_e_contratacao', 'decisao_sobre_contratacao_de_ferramentas', 'gestor_da_equipe_de_engenharia_de_dados', 'gestor_da_equipe_de_estudos,_relatorios', 'gestor_da_equipe_de_inteligencia_artificial_e_machine_learning', 'apesar_de_ser_gestor_ainda_atuo_na_parte_tecnica', 'gestao_de_projetos_de_dados', 'gestao_de_produtos_de_dados', 'gestao_de_pessoas', 'desafios_como_gestor', 'contratar_talentos', 'convencer_a_empresa_a_aumentar_investimentos', 'gestao_de_equipes_no_ambiente_remoto', 'gestao_de_projetos_envolvendo_areas_multidisciplinares', 'organizar_as_informacoes_com_qualidade_e_confiabilidade', 'processar_e_armazenar_um_alto_volume_de_dados', 'gerar_valor_para_as_areas_de_negocios', 'desenvolver_e_manter_modelos_machine_learning_em_producao', 'gerenciar_a_expectativa_das_areas', 'garantir_a_manutencao_dos_projetos_e_modelos_em_producao', 'conseguir_levar_inovacao_para_a_empresa', 'garantir_roi_em_projetos_de_dados', 'ai_generativa_e_llm_e_uma_prioridade', 'tipo_de_uso_de_ai_generativa_e_llm_na_empresa', 'ai_generativa_e_llms_para_melhorar_produtos_externos_para_os_clientes_finais', 'motivos_para_nao_usar_ai_generativa_e_llm', 'funcao_de_atuacao', 'atuacao_em_dados', 'fontes_de_dados_dia_a_dia', 'dados_relacionais_estruturados_em_bancos_sql', 'dados_armazenados_em_bancos_nosql', 'imagens', 'textos_documentos', 'videos', 'audios', 'planilhas', 'dados_georeferenciados', 'fonte_de_dado_mais_usada', 'dados_relacionais_estruturados_em_bancos_sql__1', 'dados_armazenados_em_bancos_nosql__1', 'imagens__1', 'textos_documentos__1', 'videos__1', 'audios__1', 'planilhas__1', 'dados_georeferenciados__1', 'linguagem_de_programacao_dia_a_dia', 'nao_utilizo_nenhuma_das_linguagens_listadas', 'linguagem_mais_usada', 'linguagem_preferida', 'banco_de_dados_dia_a_dia', 'cloud_dia_a_dia', 'ferramenta_de_bi_dia_a_dia', 'ferramenta_de_bi_preferida', 'tipo_de_uso_de_ai_generativa_e_llm_na_empresa__1', 'colaboradores_usando_ai_generativa_de_forma_independente_e_descentralizada__1', 'direcionamento_centralizado_do_uso_de_ai_generativa__1', 'desenvolvedores_utilizando_copilots__1', 'ai_generativa_e_llms_para_melhorar_produtos_externos_para_os_clientes_finais__1', 'ai_generativa_e_llms_para_melhorar_produtos_internos_para_os_colaboradores__1', 'ia_generativa_e_llms_como_principal_frente_do_negocio__1', 'ia_generativa_e_llms_nao_e_prioridade__1', 'nao_sei_opinar_sobre_o_uso_de_ia_generativa_e_llms_na_empresa__1', 'usa_chatgpt_ou_copilot_no_trabalho', 'objetivo_na_area_de_dados', 'oportunidade_buscada', 'tempo_em_busca_de_oportunidade', 'experiencia_em_processos_seletivos', 'rotina_como_de', 'desenvolvo_pipelines_de_dados_utilizando_linguagens_de_programacao_como_python,_scala,_java_etc.', 'realizo_construcoes_de_etls_em_ferramentas_como_pentaho,_talend,_dataflow_etc.', 'crio_consultas_atraves_da_linguagem_sql_para_exportar_informacoes_e_compartilhar_com_as_areas_de_negocio.', 'atuo_na_integracao_de_diferentes_fontes_de_dados_atraves_de_plataformas_proprietarias_como_stitch_data,_fivetran_etc.', 'modelo_solucoes_de_arquitetura_de_dados,_criando_componentes_de_ingestao_de_dados,_transformacao_e_recuperacao_da_informacao.', 'desenvolvo_cuido_da_manutencao_de_repositorios_de_dados_baseados_em_streaming_de_eventos_como_data_lakes_e_data_lakehouses.', 'atuo_na_modelagem_dos_dados,_com_o_objetivo_de_criar_conjuntos_de_dados_como_data_warehouses,_data_marts,_datasets_etc.', 'cuido_da_qualidade_dos_dados,_metadados_e_dicionario_de_dados.', 'nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.', 'ferramentas_etl_de', 'pentaho__1', 'alteryx__1', 'databricks__1', 'possui_data_lake', 'tecnologia_data_lake', 'possui_data_warehouse', 'tecnologia_data_warehouse', 'ferramentas_de_qualidade_de_dados_dia_a_dia', 'maior_tempo_gasto_como_de', 'desenvolvendo_pipelines_de_dados_utilizando_linguagens_de_programacao_como_python,_scala,_java_etc.', 'realizando_construcoes_de_etl\\s_em_ferramentas_como_pentaho,_talend,_dataflow_etc.', 'criando_consultas_atraves_da_linguagem_sql_para_exportar_informacoes_e_compartilhar_com_as_areas_de_negocio.', 'atuando_na_integracao_de_diferentes_fontes_de_dados_atraves_de_plataformas_proprietarias_como_stitch_data,_fivetran_etc.', 'modelando_solucoes_de_arquitetura_de_dados,_criando_componentes_de_ingestao_de_dados,_transformacao_e_recuperacao_da_informacao.', 'desenvolvendo_cuidando_da_manutencao_de_repositorios_de_dados_baseados_em_streaming_de_eventos_como_data_lakes_e_data_lakehouses.', 'atuando_na_modelagem_dos_dados,_com_o_objetivo_de_criar_conjuntos_de_dados_como_data_warehouses,_data_marts,_datasets_etc.', 'cuidando_da_qualidade_dos_dados,_metadados_e_dicionario_de_dados.', 'nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.__1', 'rotina_como_da', 'processo_e_analiso_dados_utilizando_linguagens_de_programacao_como_python,_r_etc.', 'realizo_construcoes_de_dashboards_em_ferramentas_de_bi_como_powerbi,_tableau,_looker,_qlik_etc.', 'crio_consultas_atraves_da_linguagem_sql_para_exportar_informacoes_e_compartilhar_com_as_areas_de_negocio.__1', 'utilizo_api\\s_para_extrair_dados_e_complementar_minhas_analises.', 'realizo_experimentos_e_estudos_utilizando_metodologias_estatisticas_como_teste_de_hipotese,_modelos_de_regressao_etc.', 'desenvolvo_cuido_da_manutencao_de_etl\\s_utilizando_tecnologias_como_talend,_pentaho,_airflow,_dataflow_etc.', 'atuo_na_modelagem_dos_dados,_com_o_objetivo_de_criar_conjuntos_de_dados_como_data_warehouses,_data_marts_etc.', 'desenvolvo_cuido_da_manutencao_de_planilhas_para_atender_as_areas_de_negocio.', 'utilizo_ferramentas_avancadas_de_estatistica_como_sas,_spss,_stata_etc,_para_realizar_analises_de_dados.', 'nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.__2', 'ferramentas_etl_da', 'scripts_python__1', 'sql_&_stored_procedures__1', 'apache_airflow__1', 'apache_nifi__1', 'luigi__1', 'aws_glue__1', 'talend__1', 'pentaho__2', 'alteryx__2', 'stitch__1', 'fivetran__1', 'google_dataflow__1', 'oracle_data_integrator__1', 'ibm_datastage__1', 'sap_bw_etl__1', 'sql_server_integration_services_ssis__1', 'sas_data_integration__1', 'qlik_sense__1', 'knime__1', 'databricks__2', 'nao_utilizo_ferramentas_de_etl__1', 'ferramentas_autonomia_area_de_negocios', 'ferramentas_de_automl_como_h2o.ai,_data_robot,_bigml_etc.', 'point_and_click_analytics_como_alteryx,_knime,_rapidminer_etc.', 'product_metricts_&_insights_como_mixpanel,_amplitude,_adobe_analytics.', 'ferramentas_de_analise_dentro_de_ferramentas_de_crm_como_salesforce_einstein_anaytics_ou_zendesk_dashboards.', 'minha_empresa_nao_utiliza_essas_ferramentas.', 'nao_sei_informar.', 'maior_tempo_gasto_como_da', 'processando_e_analisando_dados_utilizando_linguagens_de_programacao_como_python,_r_etc.', 'realizando_construcoes_de_dashboards_em_ferramentas_de_bi_como_powerbi,_tableau,_looker,_qlik_etc.', 'criando_consultas_atraves_da_linguagem_sql_para_exportar_informacoes_e_compartilhar_com_as_areas_de_negocio.__1', 'utilizando_apis_para_extrair_dados_e_complementar_minhas_analises.', 'realizando_experimentos_e_estudos_utilizando_metodologias_estatisticas_como_teste_de_hipotese,_modelos_de_regressao_etc.', 'desenvolvendo_cuidando_da_manutencao_de_etls_utilizando_tecnologias_como_talend,_pentaho,_airflow,_dataflow_etc.', 'atuando_na_modelagem_dos_dados,_com_o_objetivo_de_criar_conjuntos_de_dados_como_data_warehouses,_data_marts,_datasets_etc.__1', 'desenvolvendo_cuidando_da_manutencao_de_planilhas_para_atender_as_areas_de_negocio.', 'utilizando_ferramentas_avancadas_de_estatistica_como_sas,_spss,_stata_etc,_para_realizar_analises_de_dados.', 'nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.__3', 'rotina_como_ds', 'estudos_ad_hoc_com_o_objetivo_de_confirmar_hipoteses,_realizar_modelos_preditivos,_forecasts,_analise_de_cluster_para_resolver_problemas_pontuais_e_responder_perguntas_das_areas_de_negocio.', 'sou_responsavel_pela_coleta_e_limpeza_dos_dados_que_uso_para_analise_e_modelagem.', 'sou_responsavel_por_entrar_em_contato_com_os_times_de_negocio_para_definicao_do_problema,_identificar_a_solucao_e_apresentacao_de_resultados.', 'desenvolvo_modelos_de_machine_learning_com_o_objetivo_de_colocar_em_producao_em_sistemas_produtos_de_dados.', 'sou_responsavel_por_colocar_modelos_em_producao,_criar_os_pipelines_de_dados,_apis_de_consumo_e_monitoramento.', 'cuido_da_manutencao_de_modelos_de_machine_learning_ja_em_producao,_atuando_no_monitoramento,_ajustes_e_refatoracao_quando_necessario.', 'realizo_construcoes_de_dashboards_em_ferramentas_de_bi_como_powerbi,_tableau,_looker,_qlik,_etc', 'utilizo_ferramentas_avancadas_de_estatistica_como_sas,_spss,_stata_etc,_para_realizar_analises.', 'crio_e_dou_manutencao_em_etls,_dags_e_automacoes_de_pipelines_de_dados.', 'crio_e_gerencio_solucoes_de_feature_store_e_cultura_de_mlops.', 'sou_responsavel_por_criar_e_manter_a_infra_que_meus_modelos_e_solucoes_rodam_clusters,_servidores,_api,_containers,_etc.', 'treino_e_aplico_llms_para_solucionar_problemas_de_negocio.', 'tecnicas_e_metodos_ds', 'utilizo_modelos_de_regressao_linear,_logistica,_glm.', 'utilizo_redes_neurais_ou_modelos_baseados_em_arvore_para_criar_modelos_de_classificacao.', 'desenvolvo_sistemas_de_recomendacao_recsys.', 'utilizo_metodos_estatisticos_bayesianos_para_analisar_dados.', 'utilizo_tecnicas_de_nlp_natural_language_processing_para_analisar_dados_nao_estruturados.', 'utilizo_metodos_estatisticos_classicos_testes_de_hipotese,_analise_multivariada,_sobrevivencia,_dados_longitudinais,_inferencia_estatistica_para_analisar_dados.', 'utilizo_cadeias_de_markov_ou_hmm\\s_para_realizar_analises_de_dados.', 'desenvolvo_tecnicas_de_clusterizacao_k_means,_spectral,_dbscan_etc.', 'realizo_previsoes_atraves_de_modelos_de_series_temporais_time_series.', 'utilizo_modelos_de_reinforcement_learning_aprendizado_por_reforco.', 'utilizo_modelos_de_machine_learning_para_deteccao_de_fraude.', 'utilizo_metodos_de_visao_computacional.', 'utilizo_modelos_de_deteccao_de_churn.', 'utilizo_llms_para_solucionar_problemas_de_negocio.', 'tecnologias_ds', 'ferramentas_de_bi_powerbi,_looker,_tableau,_qlik_etc.', 'planilhas_excel,_google_sheets_etc.', 'ambientes_de_desenvolvimento_local_r_studio,_jupyterlab,_anaconda.', 'ambientes_de_desenvolvimento_na_nuvem_google_colab,_aws_sagemaker,_kaggle_notebooks_etc.', 'ferramentas_de_automl_datarobot,_h2o,_auto_keras_etc.', 'ferramentas_de_etl_apache_airflow,_nifi,_stitch,_fivetran,_pentaho_etc.', 'plataformas_de_machine_learning_tensorflow,_azure_machine_learning,_kubeflow_etc.', 'feature_store_feast,_hopsworks,_aws_feature_store,_databricks_feature_store_etc.', 'sistemas_de_controle_de_versao_github,_dvc,_neptune,_gitlab_etc.', 'plataformas_de_data_apps_streamlit,_shiny,_plotly_dash_etc.', 'ferramentas_de_estatistica_avancada_como_spss,_sas,_etc.', 'maior_tempo_gasto_como_ds', 'estudos_ad_hoc_com_o_objetivo_de_confirmar_hipoteses,_realizar_modelos_preditivos,_forecasts,_analise_de_cluster_para_resolver_problemas_pontuais_e_responder_perguntas_das_areas_de_negocio.__1', 'coletando_e_limpando_dos_dados_que_uso_para_analise_e_modelagem.', 'entrando_em_contato_com_os_times_de_negocio_para_definicao_do_problema,_identificar_a_solucao_e_apresentacao_de_resultados.', 'desenvolvendo_modelos_de_machine_learning_com_o_objetivo_de_colocar_em_producao_em_sistemas_produtos_de_dados.', 'colocando_modelos_em_producao,_criando_os_pipelines_de_dados,_apis_de_consumo_e_monitoramento.', 'cuidando_da_manutencao_de_modelos_de_machine_learning_ja_em_producao,_atuando_no_monitoramento,_ajustes_e_refatoracao_quando_necessario.', 'realizando_construcoes_de_dashboards_em_ferramentas_de_bi_como_powerbi,_tableau,_looker,_qlik,_etc.', 'utilizando_ferramentas_avancadas_de_estatistica_como_sas,_spss,_stata_etc,_para_realizar_analises.', 'criando_e_dando_manutencao_em_etls,_dags_e_automacoes_de_pipelines_de_dados.', 'criando_e_gerenciando_solucoes_de_feature_store_e_cultura_de_mlops.', 'criando_e_mantendo_a_infra_que_meus_modelos_e_solucoes_rodam_clusters,_servidores,_api,_containers,_etc.', 'treinando_e_aplicando_llms_para_solucionar_problemas_de_negocio.']

In [40]:
# --- TRADUÇÃO DAS 43 COLUNAS RESTANTES ---
traducao_final = {
    # Modelo de Trabalho
    'atualmente_qual_a_sua_forma_de_trabalho': 'modelo_de_trabalho_atual',
    'qual_a_forma_de_trabalho_ideal_para_voce': 'modelo_de_trabalho_ideal',
    'caso_sua_empresa_decida_pelo_modelo_100pct_presencial_qual_sera_sua_atitude': 'atitude_em_caso_de_retorno_presencial',

    # Insatisfação (nomes encurtados)
    'gostaria_de_trabalhar_em_em_outra_area_de_atuacao': 'gostaria_de_trabalhar_em_outra_area',
    'oportunidade_de_aprendizado_e_trabalhar_com_referencias_na_area': 'oportunidade_de_aprendizado_e_trabalhar_com_referencias',
    'plano_de_carreira_e_oportunidades_de_crescimento_profissional': 'plano_de_carreira_e_oportunidades_de_crescimento',

    # Desafios do Gestor (sem as letras a, b, c...)
    'a_contratar_novos_talentos': 'contratar_talentos',
    'c_convencer_a_empresa_a_aumentar_os_investimentos_na_area_de_dados': 'convencer_a_empresa_a_aumentar_investimentos',
    'd_gestao_de_equipes_no_ambiente_remoto': 'gestao_de_equipes_no_ambiente_remoto',
    'e_gestao_de_projetos_envolvendo_areas_multidisciplinares_da_empresa': 'gestao_de_projetos_envolvendo_areas_multidisciplinares',
    'f_organizar_as_informacoes_e_garantir_a_qualidade_e_confiabilidade': 'organizar_as_informacoes_com_qualidade_e_confiabilidade',
    'g_conseguir_processar_e_armazenar_um_alto_volume_de_dados': 'processar_e_armazenar_um_alto_volume_de_dados',
    'h_conseguir_gerar_valor_para_as_areas_de_negocios_atraves_de_estudos_e_experimentos': 'gerar_valor_para_as_areas_de_negocios',
    'i_desenvolver_e_manter_modelos_machine_learning_em_producao': 'desenvolver_e_manter_modelos_machine_learning_em_producao',
    'j_gerenciar_a_expectativa_das_areas_de_negocio_em_relacao_as_entregas_das_equipes_de_dados': 'gerenciar_a_expectativa_das_areas',
    'k_garantir_a_manutencao_dos_projetos_e_modelos_em_producao,_em_meio_ao_crescimento_da_empresa': 'garantir_a_manutencao_dos_projetos_e_modelos_em_producao',
    'conseguir_levar_inovacao_para_a_empresa_atraves_dos_dados': 'conseguir_levar_inovacao_para_a_empresa',
    'garantir_retorno_do_investimento_roi_em_projetos_de_dados': 'garantir_roi_em_projetos_de_dados',

    # IA e Atuação
    'ai_generativa_e_uma_prioridade_em_sua_empresa': 'ai_generativa_e_llm_e_uma_prioridade',
    'ai_generativa_e_llms_para_melhorar_produtos_externos': 'ai_generativa_e_llms_para_melhorar_produtos_externos_para_os_clientes_finais',
    'atuacao': 'atuacao_em_dados',
    'nao_utilizo_nenhuma_linguagem': 'nao_utilizo_nenhuma_das_linguagens_listadas',
    'entre_as_linguagens_listadas_abaixo,_qual_e_a_que_voce_mais_utiliza_no_trabalho': 'linguagem_mais_usada',
    'ferramenta_de_bi_utilizada_no_dia_a_dia': 'ferramenta_de_bi_dia_a_dia',
    'utiliza_chatgpt_ou_llms_no_trabalho': 'usa_chatgpt_ou_copilot_no_trabalho',

    # Maturidade (Data Lake / DW)
    'sua_organizacao_possui_um_data_lake': 'possui_data_lake',
    'sua_organizacao_possui_um_data_warehouse': 'possui_data_warehouse',

    # MLOps (a pesquisa de 2024 adicionou um PONTO no final do nome)
    'ambientes_de_desenvolvimento_na_nuvem_google_colab,_aws_sagemaker,_kaggle_notebooks_etc': 'ambientes_de_desenvolvimento_na_nuvem_google_colab,_aws_sagemaker,_kaggle_notebooks_etc.',
    'plataformas_de_machine_learning_tensorflow,_azure_machine_learning,_kubeflow_etc': 'plataformas_de_machine_learning_tensorflow,_azure_machine_learning,_kubeflow_etc.',
    'feature_store_feast,_hopsworks,_aws_feature_store,_databricks_feature_store_etc': 'feature_store_feast,_hopsworks,_aws_feature_store,_databricks_feature_store_etc.',
    'sistemas_de_controle_de_versao_github,_dvc,_neptune,_gitlab_etc': 'sistemas_de_controle_de_versao_github,_dvc,_neptune,_gitlab_etc.',
    'plataformas_de_data_apps_streamlit,_shiny,_plotly_dash_etc': 'plataformas_de_data_apps_streamlit,_shiny,_plotly_dash_etc.',
}

# Aplica as traduções finais
traducao_valida_final = {k: v for k, v in traducao_final.items() if v in df_2024.columns}
df_2024 = df_2024.rename(columns={v: k for k, v in traducao_valida_final.items()})
print(f" Mais {len(traducao_valida_final)} traduções aplicadas!")

# --- Seleciona APENAS as colunas da Silver (para ficar igual a 2023) ---
colunas_2023 = df_silver_2023.columns.tolist()

# Pega só as colunas que existem no 2024 (as que "morreram" ficam de fora)
colunas_existentes_no_2024 = [c for c in colunas_2023 if c in df_2024.columns]

df_silver_2024 = df_2024[colunas_existentes_no_2024].copy()

# Limpa nomes perigosos (igual foi feito em 2023)
renomear = {}
for c in df_silver_2024.columns:
    limpo = c.replace('%', 'pct').replace('?', '').rstrip('.')
    if limpo != c:
        renomear[c] = limpo
df_silver_2024 = df_silver_2024.rename(columns=renomear)

print(f"\n Shape final do 2024: {df_silver_2024.shape}")
print(f"(O 2023 tinha {df_silver_2023.shape[1]} colunas.)")

 Mais 32 traduções aplicadas!

 Shape final do 2024: (5217, 181)
(O 2023 tinha 192 colunas.)

In [41]:
faltam_2024 = [c for c in colunas_2023 if c not in df_silver_2024.columns]
print(faltam_2024)

['falta_de_oportunidade_de_crescimento_no_emprego_atual', 'salario_atual_nao_corresponde_ao_mercado', 'nao_tenho_uma_boa_relacao_com_meu_lider_gestor', 'gostaria_de_receber_mais_beneficios', 'o_clima_de_trabalho_ambiente_nao_e_bom', 'falta_de_maturidade_analitica_na_empresa', 'mode', 'microstrategy', 'ibm_analytics_cognos', 'birst', 'tibco_spotfire']

Algumas colunas na lista de 2023 não existem mais em 2024.

In [42]:
df_silver_2024

,id,idade,faixa_idade,genero,cor_raca_etnia,pcd,experiencia_prejudicada_devido_a_minha_identidade_de_genero,experiencia_prejudicada_devido_a_minha_cor_raca_etnia,experiencia_prejudicada_devido_ao_fato_de_ser_pcd,quantidade_de_oportunidades_de_emprego_vagas_recebidas,...,qlik_sense,knime,nao_utilizo_ferramentas_de_etl,sua_organizacao_possui_um_data_lake,sua_organizacao_possui_um_data_warehouse,"ambientes_de_desenvolvimento_na_nuvem_google_colab,_aws_sagemaker,_kaggle_notebooks_etc","plataformas_de_machine_learning_tensorflow,_azure_machine_learning,_kubeflow_etc","feature_store_feast,_hopsworks,_aws_feature_store,_databricks_feature_store_etc","sistemas_de_controle_de_versao_github,_dvc,_neptune,_gitlab_etc","plataformas_de_data_apps_streamlit,_shiny,_plotly_dash_etc"
0,reb94rv0msth7q4nreb94riaq80iz3yi,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1zc66g69jjt49y32l1zc66g8wqj79m4e,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,uu99wmam4n5kc2uu99wmydf0rk7l58f7,18,17-21,Masculino,Parda,Não,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3ynsw7z0hl5hhpbfvaeqk73ynsw7z04l,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,v6bji2ct5xckpl1uouv6bjiotkrf3b4f,18,17-21,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5212,veww9tlgwe9y7hytd0c3vveww9t59ax8,66,55+,Feminino,Branca,Não,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5213,3hjvbhcxbidqvxvp9f2nfvgv3hjvbhcx,66,55+,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0
5214,tq6orpcm1xrea9ffmq9fxtq6orpwurr4,68,55+,Feminino,Parda,Não,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5215,lei4nn214phk0e14zlei4nt7aiqcdf4l,68,55+,Masculino,Parda,Não,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5216,ohp2uvrfl21srlyo7cohp2u57sox2mdi,68,55+,Feminino,Parda,Não,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
df_silver_2024[df_silver_2024.duplicated()]

,id,idade,faixa_idade,genero,cor_raca_etnia,pcd,experiencia_prejudicada_devido_a_minha_identidade_de_genero,experiencia_prejudicada_devido_a_minha_cor_raca_etnia,experiencia_prejudicada_devido_ao_fato_de_ser_pcd,quantidade_de_oportunidades_de_emprego_vagas_recebidas,...,qlik_sense,knime,nao_utilizo_ferramentas_de_etl,sua_organizacao_possui_um_data_lake,sua_organizacao_possui_um_data_warehouse,"ambientes_de_desenvolvimento_na_nuvem_google_colab,_aws_sagemaker,_kaggle_notebooks_etc","plataformas_de_machine_learning_tensorflow,_azure_machine_learning,_kubeflow_etc","feature_store_feast,_hopsworks,_aws_feature_store,_databricks_feature_store_etc","sistemas_de_controle_de_versao_github,_dvc,_neptune,_gitlab_etc","plataformas_de_data_apps_streamlit,_shiny,_plotly_dash_etc"
546,ald49tabosnu0wald4e57zebr5v7146b,24,22-24,Feminino,Parda,Não,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1043,lb7gt5hdqqxuguv2lb7gto44mpk3ejha,26,25-29,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN

In [44]:
# --- PARTE 1: traduções que faltavam (nomes novos do 2024) ---
traducao_restante = {
    'modelo_de_trabalho_atual': 'atualmente_qual_a_sua_forma_de_trabalho',
    'modelo_de_trabalho_ideal': 'qual_a_forma_de_trabalho_ideal_para_voce',
    'atitude_em_caso_de_retorno_presencial': 'caso_sua_empresa_decida_pelo_modelo_100pct_presencial_qual_sera_sua_atitude',
    'contratar_talentos': 'a_contratar_novos_talentos',
    'convencer_a_empresa_a_aumentar_investimentos': 'c_convencer_a_empresa_a_aumentar_os_investimentos_na_area_de_dados',
    'gestao_de_equipes_no_ambiente_remoto': 'd_gestao_de_equipes_no_ambiente_remoto',
    'gestao_de_projetos_envolvendo_areas_multidisciplinares': 'e_gestao_de_projetos_envolvendo_areas_multidisciplinares_da_empresa',
    'organizar_as_informacoes_com_qualidade_e_confiabilidade': 'f_organizar_as_informacoes_e_garantir_a_qualidade_e_confiabilidade',
    'processar_e_armazenar_um_alto_volume_de_dados': 'g_conseguir_processar_e_armazenar_um_alto_volume_de_dados',
    'gerar_valor_para_as_areas_de_negocios': 'h_conseguir_gerar_valor_para_as_areas_de_negocios_atraves_de_estudos_e_experimentos',
    'desenvolver_e_manter_modelos_machine_learning_em_producao': 'i_desenvolver_e_manter_modelos_machine_learning_em_producao',
    'gerenciar_a_expectativa_das_areas': 'j_gerenciar_a_expectativa_das_areas_de_negocio_em_relacao_as_entregas_das_equipes_de_dados',
    'garantir_a_manutencao_dos_projetos_e_modelos_em_producao': 'k_garantir_a_manutencao_dos_projetos_e_modelos_em_producao,_em_meio_ao_crescimento_da_empresa',
    'conseguir_levar_inovacao_para_a_empresa': 'conseguir_levar_inovacao_para_a_empresa_atraves_dos_dados',
    'garantir_roi_em_projetos_de_dados': 'garantir_retorno_do_investimento_roi_em_projetos_de_dados',
    'ai_generativa_e_llm_e_uma_prioridade': 'ai_generativa_e_uma_prioridade_em_sua_empresa',
    'ai_generativa_e_llms_para_melhorar_produtos_externos_para_os_clientes_finais': 'ai_generativa_e_llms_para_melhorar_produtos_externos',
    'atuacao_em_dados': 'atuacao',
    'nao_utilizo_nenhuma_das_linguagens_listadas': 'nao_utilizo_nenhuma_linguagem',
    'linguagem_mais_usada': 'entre_as_linguagens_listadas_abaixo,_qual_e_a_que_voce_mais_utiliza_no_trabalho',
    'ferramenta_de_bi_dia_a_dia': 'ferramenta_de_bi_utilizada_no_dia_a_dia',
    'usa_chatgpt_ou_copilot_no_trabalho': 'utiliza_chatgpt_ou_llms_no_trabalho',
    'possui_data_lake': 'sua_organizacao_possui_um_data_lake',
    'possui_data_warehouse': 'sua_organizacao_possui_um_data_warehouse',
    'plano_de_carreira_e_oportunidades_de_crescimento': 'plano_de_carreira_e_oportunidades_de_crescimento_profissional',
}

# --- PARTE 2: a CORREÇÃO DA TROCA (insatisfação x critérios) ---
correcao_troca = {
    # insatisfação (estava com nome "puro") -> nome 2023 de insatisfação
    'remuneracao_salario': 'salario_atual_nao_corresponde_ao_mercado',
    'beneficios': 'gostaria_de_receber_mais_beneficios',
    'ambiente_e_clima_de_trabalho': 'o_clima_de_trabalho_ambiente_nao_e_bom',
    'maturidade_da_empresa_em_termos_de_tecnologia_e_dados': 'falta_de_maturidade_analitica_na_empresa',
    'oportunidades_de_crescimento': 'falta_de_oportunidade_de_crescimento_no_emprego_atual',
    'relacao_com_os_gestores_e_lideres': 'nao_tenho_uma_boa_relacao_com_meu_lider_gestor',
    'gostaria_de_trabalhar_em_outra_area': 'gostaria_de_trabalhar_em_em_outra_area_de_atuacao',
    # critérios (estavam com __1) -> nome 2023 "puro"
    'remuneracao_salario__1': 'remuneracao_salario',
    'beneficios__1': 'beneficios',
    'proposito_do_trabalho_e_da_empresa__1': 'proposito_do_trabalho_e_da_empresa',
    'flexibilidade_de_trabalho_remoto__1': 'flexibilidade_de_trabalho_remoto',
    'ambiente_e_clima_de_trabalho__1': 'ambiente_e_clima_de_trabalho',
    'oportunidade_de_aprendizado_e_trabalhar_com_referencias__1': 'oportunidade_de_aprendizado_e_trabalhar_com_referencias_na_area',
    'maturidade_da_empresa_em_termos_de_tecnologia_e_dados__1': 'maturidade_da_empresa_em_termos_de_tecnologia_e_dados',
    'reputacao_que_a_empresa_tem_no_mercado__1': 'reputacao_que_a_empresa_tem_no_mercado',
    'relacao_com_os_gestores_e_lideres__1': 'qualidade_dos_gestores_e_lideres',
}

# Aplica os dois dicionários (só o que existir, sem quebrar)
for dicionario in [traducao_restante, correcao_troca]:
    valida = {k: v for k, v in dicionario.items() if k in df_2024.columns}
    df_2024 = df_2024.rename(columns=valida)
    print(f"{len(valida)} ajustes aplicados")

# --- Remonta a Silver 2024 e confere o que sobrou ---
colunas_existentes = [c for c in colunas_2023 if c in df_2024.columns]
df_silver_2024 = df_2024[colunas_existentes].copy()

faltam = [c for c in colunas_2023 if c not in df_2024.columns]
print(f"\n🎉 Shape final: {df_silver_2024.shape}")
print(f"Colunas mortas em 2024: {len(faltam)}")
print(faltam)

0 ajustes aplicados
14 ajustes aplicados

🎉 Shape final: (5217, 191)
Colunas mortas em 2024: 5
['mode', 'microstrategy', 'ibm_analytics_cognos', 'birst', 'tibco_spotfire']

"Em 2024, propósito e flexibilidade entraram para a lista de dores dos profissionais de dados" 📈

In [45]:
# 1) Shape final
print(df_silver_2024.shape)

# 2) O que ficou de fora (esperado: SÓ as 5 BIs mortas)
print([c for c in colunas_2023 if c not in df_silver_2024.columns])

(5217, 191)
['mode', 'microstrategy', 'ibm_analytics_cognos', 'birst', 'tibco_spotfire']

## **2025**

### Conhecendo o DF

In [46]:
df_2025.head()

,0.a_token,0.d_data/hora_envio,1.a_idade,1.a.1_faixa_idade,1.b_genero,1.c_cor/raca/etnia,1.d_pcd,1.e_experiencia_profissional_prejudicada,1.e.1_Não acredito que minha experiência profissional seja afetada,"1.e.2_Sim, devido a minha Cor/Raça/Etnia",...,8.d.4_Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).,"8.d.5_Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.","8.d.6_Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.","8.d.7_Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc.","8.d.8_Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.","8.d.9_Criando e dando manutenção em ETLs, DAGs e automações de pipelines de dados.",8.d.10_Criando e gerenciando soluções de Feature Store e cultura de MLOps.,"8.d.11_Criando e mantendo a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)",8.d.12_Treinando e aplicando LLM's para solucionar problemas de negócio.,8.d_maior_tempo_gasto_como_ds
0,apeczcwvds75ba5hml4apec2pb35hflw,20/10/2025 10:20:11,35,35-39,Masculino,Branca,Não,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,a27c74vkj7n8vmib88ca27c74sepwcpa,20/10/2025 10:27:09,20,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7xpkv4qj7mzvsxemhpjy7xpkv4qu61oi,20/10/2025 10:28:59,35,35-39,Masculino,Branca,Não,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ugzyokw0p1or7axwzugzyz4ombwfgzoo,20/10/2025 10:30:24,29,25-29,Masculino,Parda,Não,Não acredito que minha experiência profissiona...,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,n7aiatzlzonity0sn7aiat75y36iuqni,20/10/2025 10:33:11,18,17-21,Masculino,Preta,Não,Não acredito que minha experiência profissiona...,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
print('Dimensões da Dataset:')
print(f'Linhas: {df_2025.shape[0]}')
print(f'Colunas: {df_2025.shape[1]}')

Dimensões da Dataset:
Linhas: 3495
Colunas: 388

In [48]:
print('Informações Gerais:')
print(df_2025.info())

Informações Gerais:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3495 entries, 0 to 3494
Columns: 388 entries, 0.a_token to 8.d_maior_tempo_gasto_como_ds
dtypes: float64(315), int64(2), object(71)
memory usage: 10.3+ MB
None

In [49]:
print(df_2025.duplicated().sum())

1

In [50]:
df_2025.isnull().sum()

0.a_token                                                                                                               0
0.d_data/hora_envio                                                                                                     0
1.a_idade                                                                                                               0
1.a.1_faixa_idade                                                                                                       0
1.b_genero                                                                                                              0
                                                                                                                     ...
8.d.9_Criando e dando manutenção em ETLs, DAGs e automações de pipelines de dados.                                   3005
8.d.10_Criando e gerenciando soluções de Feature Store e cultura de MLOps.                                           3005
8.d.11_Criando e mantendo a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)    3005
8.d.12_Treinando e aplicando LLM's para solucionar problemas de negócio.                                             3005
8.d_maior_tempo_gasto_como_ds                                                                                        3005
Length: 388, dtype: int64

In [51]:
for i, coluna in enumerate(df_2025.columns):
    print(f'{i}. {coluna}')

0. 0.a_token
1. 0.d_data/hora_envio
2. 1.a_idade
3. 1.a.1_faixa_idade
4. 1.b_genero
5. 1.c_cor/raca/etnia
6. 1.d_pcd
7. 1.e_experiencia_profissional_prejudicada
8. 1.e.1_Não acredito que minha experiência profissional seja afetada
9. 1.e.2_Sim, devido a minha Cor/Raça/Etnia
10. 1.e.3_Sim, devido a minha identidade de gênero
11. 1.e.4_Sim, devido ao fato de ser PCD
12. 1.f_aspectos_prejudicados
13. 1.f.1_Quantidade de oportunidades de emprego/vagas recebidas
14. 1.f.2_Senioridade das vagas recebidas em relação à sua experiência
15. 1.f.3_Aprovação em processos seletivos/entrevistas
16. 1.f.4_Oportunidades de progressão de carreira
17. 1.f.5_Velocidade de progressão de carreira
18. 1.f.6_Nível de cobrança no trabalho/Stress no trabalho
19. 1.f.7_Atenção dada pelas pessoas diante das minhas opiniões e ideias
20. 1.f.8_Relação com outras pessoas da empresa, em momentos de trabalho
21. 1.f.9_Relação com outras pessoas da empresa, em momentos de integração e outros momentos fora do trabalho
22. 1.g_vive_no_brasil
23. 1.h_pais_onde_mora
24. 1.i_estado_onde_mora
25. 1.i.1_uf_onde_mora
26. 1.i.2_regiao_onde_mora
27. 1.j_vive_no_estado_de_formacao
28. 1.k_estado_de_origem
29. 1.k.1_uf_de_origem
30. 1.k.2_regiao_de_origem
31. 1.l_nivel_de_ensino
32. 1.m_área_de_formação
33. 2.a_situação_de_trabalho
34. 2.b_setor
35. 2.c_numero_de_funcionarios
36. 2.d_atua_como_gestor
37. 2.e_cargo_como_gestor
38. 2.f_cargo_atual
39. 2.g_nivel
40. 2.h_faixa_salarial
41. 2.i_tempo_de_experiencia_em_dados
42. 2.j_tempo_de_experiencia_em_ti
43. 2.k_satisfeito_atualmente
44. 2.l.1_Remuneração/Salário
45. 2.l.2_Benefícios
46. 2.l.3_Propósito do trabalho e da empresa
47. 2.l.4_Flexibilidade de trabalho remoto
48. 2.l.5_Ambiente e clima de trabalho
49. 2.l.6_Oportunidade de aprendizado e trabalhar com referências
50. 2.l.7_Oportunidades de crescimento
51. 2.l.8_Maturidade da empresa em termos de tecnologia e dados
52. 2.l.9_Relação com os gestores e líderes
53. 2.l.10_Reputação que a empresa tem no mercado
54. 2.l.11_Gostaria de trabalhar em outra área
55. 2.l_motivo_insatisfacao
56. 2.m_participou_de_entrevistas_ultimos_6m
57. 2.n_planos_de_mudar_de_emprego_6m
58. 2.o_criterios_para_escolha_de_emprego
59. 2.o.1_Remuneração/Salário
60. 2.o.2_Benefícios
61. 2.o.3_Propósito do trabalho e da empresa
62. 2.o.4_Flexibilidade de trabalho remoto
63. 2.o.5_Ambiente e clima de trabalho
64. 2.o.6_Oportunidade de aprendizado e trabalhar com referências
65. 2.o.7_Plano de carreira e oportunidades de crescimento
66. 2.o.8_Maturidade da empresa em termos de tecnologia e dados
67. 2.o.9_Qualidade dos gestores e líderes
68. 2.o.10_Reputação que a empresa tem no mercado
69. 2.p_empresa_passou_por_layoff_em_2025
70. 2.q_modelo_de_trabalho_atual
71. 2.r_modelo_de_trabalho_ideal
72. 2.s_atitude_em_caso_de_retorno_presencial
73. 3.a_numero_de_pessoas_em_dados
74. 3.b_cargos_no_time_de_dados_da_empresa
75. 3.b.1_Analytics Engineer
76. 3.b.2_Engenharia de Dados/Data Engineer
77. 3.b.3_Analista de Dados/Data Analyst
78. 3.b.4_Cientista de Dados/Data Scientist
79. 3.b.5_Database Administrator/DBA
80. 3.b.6_Analista de Business Intelligence/BI
81. 3.b.7_Arquiteto de Dados/Data Architect
82. 3.b.8_Data Product Manager/DPM
83. 3.b.9_Business Analyst
84. 3.b.10_ML Engineer/AI Engineer
85. 3.c_responsabilidades_como_gestor
86. 3.c.1_Pensar na visão de longo prazo de dados
87. 3.c.2_Organização de treinamentos e iniciativas
88. 3.c.3_Atração, seleção e contratação
89. 3.c.4_Decisão sobre contratação de ferramentas
90. 3.c.5_gestor da equipe de engenharia de dados
91. 3.c.6_gestor da equipe de estudos, relatórios
92. 3.c.7_gestor da equipe de Inteligência Artificial e Machine Learning
93. 3.c.8_Apesar de ser gestor ainda atuo na parte técnica
94. 3.c.9_Gestão de projetos de dados
95. 3.c.10_Gestão de produtos de dados
96. 3.c.11_Gestão de pessoas
97. 3.d_desafios_como_gestor
98. 3.d.1_Contratar talentos
99. 3.d.2_Reter talentos
100. 3.d.3_Convencer a empresa a aumentar investimentos
101. 3.d.4_Gestão de equipes no ambiente remoto
102. 3.d.5_Gestão de projetos envolvendo áreas multidisciplinares
103. 3.d.6_Organizar as informações com qualidade e confiabilidade
104. 3.d.7_Processar e armazenar um alto volume de dados
105. 3.d.8_Gerar valor para as áreas de negócios
106. 3.d.9_Desenvolver e manter modelos Machine Learning em produção
107. 3.d.10_Gerenciar a expectativa das áreas
108. 3.d.11_Garantir a manutenção dos projetos e modelos em produção
109. 3.d.12_Conseguir levar inovação para a empresa
110. 3.d.13_Garantir (ROI) em projetos de dados
111. 3.d.14_Dividir o tempo entre entregas técnicas e gestão
112. 3.e_ai_generativa_e_llm_é_uma_prioridade?
113. 3.f_tipo_de_uso_de_ai_generativa_e_llm_na_empresa
114. 3.f.1 Colaboradores usando AI generativa de forma independente e descentralizada
115. 3.f.2 Direcionamento centralizado do uso de AI generativa
116. 3.f.3 Desenvolvedores utilizando Copilots
117. 3.f.4 AI Generativa e LLMs para melhorar produtos externos para os clientes finais
118. 3.f.5 AI Generativa e LLMs para melhorar produtos internos para os colaboradores
119. 3.f.6 IA Generativa e LLMs como principal frente do negócio
120. 3.f.7 IA Generativa e LLMs não é prioridade
121. 3.f.8 Não sei opinar sobre o uso de IA Generativa e LLMs na empresa
122. 3.g_empresa_está_conseguindo_ter_bons_resultados_com_llms
123. 3.h_motivos_para_não_usar_ai_generativa_e_llm
124. 3.h.1 Falta de compreensão dos casos de uso
125. 3.h.2 Falta de confiabilidade das saídas (alucinação dos modelos)
126. 3.h.3 Incerteza em relação a regulamentação
127. 3.h.4 Preocupações com segurança e privacidade de dados
128. 3.h.5 Retorno sobre investimento (ROI) não comprovado de IA Generativa
129. 3.h.6 Dados da empresa não estão prontos para uso de IA Generativa
130. 3.h.7 Falta de expertise ou falta de recursos
131. 3.h.8 Alta direção da empresa não vê valor ou não vê como prioridade
132. 3.h.9 Preocupações com propriedade intelectual
133. 4.a.1_atuacao_em_dados
134. 4.a_funcao_de_atuacao
135. 4.b_fontes_de_dados_(dia_a_dia)
136. 4.b.1_Dados relacionais (estruturados em bancos SQL)
137. 4.b.2_Dados armazenados em bancos NoSQL
138. 4.b.3_Imagens
139. 4.b.4_Textos/Documentos
140. 4.b.5_Vídeos
141. 4.b.6_Áudios
142. 4.b.7_Planilhas
143. 4.b.8_Dados georeferenciados
144. 4.c_linguagem_preferida
145. 4.c.1_SQL
146. 4.c.2_R
147. 4.c.3_Python
148. 4.c.4_C/C++/C#
149. 4.c.5_Julia
150. 4.c.6_Visual Basic/VBA
151. 4.c.7_Scala
152. 4.c.8_DAX
153. 4.c.9_Rust
154. 4.c.10_Não utilizo nenhuma das linguagens listadas
155. 4.d_banco_de_dados_(dia_a_dia)
156. 4.d.1_MySQL
157. 4.d.2_Oracle
158. 4.d.3_SQL SERVER
159. 4.d.4_Amazon Aurora ou RDS
160. 4.d.5_DynamoDB
161. 4.d.6_CoachDB
162. 4.d.7_Cassandra
163. 4.d.8_MongoDB
164. 4.d.9_MariaDB
165. 4.d.10_Datomic
166. 4.d.11_S3
167. 4.d.12_PostgreSQL
168. 4.d.13_ElasticSearch
169. 4.d.14_DB2
170. 4.d.15_Microsoft Access
171. 4.d.16_SQLite
172. 4.d.17_Sybase
173. 4.d.18_Firebase
174. 4.d.19_Vertica
175. 4.d.20_Redis
176. 4.d.21_Neo4J
177. 4.d.22_Google BigQuery
178. 4.d.23_Google Firestore
179. 4.d.24_Amazon Redshift
180. 4.d.25_Amazon Athena
181. 4.d.26_Snowflake
182. 4.d.27_Databricks
183. 4.d.28_HBase
184. 4.d.29_Presto
185. 4.d.30_Splunk
186. 4.d.31_SAP HANA
187. 4.d.32_Hive
188. 4.d.33_Firebird
189. 4.e_cloud_(dia_a_dia)
190. 4.e.1_Amazon Web Services (AWS)
191. 4.e.2_Google Cloud (GCP)
192. 4.e.3_Azure (Microsoft)
193. 4.e.4_Oracle Cloud
194. 4.e.5_IBM
195. 4.e.6_Servidores On Premise/Não utilizamos Cloud
196. 4.e.7_Cloud Própria
197. 4.f_cloud_preferida
198. 4.g_ferramenta_de_bi_(dia_a_dia)
199. 4.g.1_Microsoft PowerBI
200. 4.g.2_Qlik View/Qlik Sense
201. 4.g.3_Tableau
202. 4.g.4_Metabase
203. 4.g.5_Superset
204. 4.g.6_Redash
205. 4.g.7_Looker
206. 4.g.8_Looker Studio(Google Data Studio)
207. 4.g.9_Amazon Quicksight
208. 4.g.10_Alteryx
209. 4.g.11_SAP Business Objects/SAP Analytics
210. 4.g.12_Oracle Business Intelligence
211. 4.g.13_Salesforce/Einstein Analytics
212. 4.g.14_SAS Visual Analytics
213. 4.g.15_Grafana
214. 4.g.16_Pentaho
215. 4.g.17_Fazemos todas as análises utilizando apenas Excel ou planilhas do google
216. 4.g.18_Não utilizo nenhuma ferramenta de BI no trabalho
217. 4.h_ferramenta_de_bi_preferida
218. 4.i_tipo_de_uso_de_ai_generativa_e_llm_na_empresa
219. 4.i.1 Colaboradores usando AI generativa de forma independente e descentralizada
220. 4.i.2 Direcionamento centralizado do uso de AI generativa
221. 4.i.3 Desenvolvedores utilizando Copilots
222. 4.i.4 AI Generativa e LLMs para melhorar produtos externos para os clientes finais
223. 4.i.5 AI Generativa e LLMs para melhorar produtos internos para os colaboradores
224. 4.i.6 IA Generativa e LLMs como principal frente do negócio
225. 4.i.7 IA Generativa e LLMs não é prioridade
226. 4.i.8 Não sei opinar sobre o uso de IA Generativa e LLMs na empresa
227. 4.j_usa_chatgpt_ou_copilot_no_trabalho?
228. 4.j.1 Não uso soluções de AI Generativa com foco em produtividade
229. 4.j.2 Uso soluções gratuitas de AI Generativa com foco em produtividade
230. 4.j.3 Uso e pago pelas soluções de AI Generativa com foco em produtividade
231. 4.j.4 A empresa que trabalho paga pelas soluções de AI Generativa com foco em produtividade
232. 4.j.5 Uso soluções do tipo Copilot
233. 5.a_objetivo_na_area_de_dados
234. 5.b_oportunidade_buscada
235. 5.c_tempo_em_busca_de_oportunidade
236. 5.d_experiencia_em_processos_seletivos
237. 6.a_rotina_como_de
238. 6.a.1_Desenvolvo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.
239. 6.a.2_Realizo construções de ETL's em ferramentas como Pentaho, Talend, Dataflow etc.
240. 6.a.3_Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.
241. 6.a.4_Atuo na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.
242. 6.a.5_Modelo soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.
243. 6.a.6_Desenvolvo/cuido da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.
244. 6.a.7_Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.
245. 6.a.8_Cuido da qualidade dos dados, metadados e dicionário de dados.
246. 6.a.9_Nenhuma das opções listadas refletem meu dia a dia.
247. 6.b_ferramentas_etl_de
248. 6.b.1_Scripts Python
249. 6.b.2_SQL & Stored Procedures
250. 6.b.3_Apache Airflow
251. 6.b.4_Apache NiFi
252. 6.b.5_Luigi
253. 6.b.6_AWS Glue
254. 6.b.7_Talend
255. 6.b.8_Pentaho
256. 6.b.9_Alteryx
257. 6.b.10_Stitch
258. 6.b.11_Fivetran
259. 6.b.12_Google Dataflow
260. 6.b.13_Oracle Data Integrator
261. 6.b.14_IBM DataStage
262. 6.b.15_SAP BW ETL
263. 6.b.16_SQL Server Integration Services (SSIS)
264. 6.b.17_SAS Data Integration
265. 6.b.18_Qlik Sense
266. 6.b.19_Knime
267. 6.b.20_Databricks
268. 6.b.21_Não utilizo ferramentas de ETL
269. 6.c_possui_data_lake
270. 6.d_tecnologia_data_lake
271. 6.e_possui_data_warehouse
272. 6.f_tecnologia_data_warehouse
273. 6.g_ferramentas_de_qualidade_de_dados_(dia_a_dia)
274. 6.h.1_Desenvolvendo pipelines de dados utilizando linguagens de programação como Python, Scala, Java etc.
275. 6.h.2_Realizando construções de ETL\s em ferramentas como Pentaho, Talend, Dataflow etc.
276. 6.h.3_Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.
277. 6.h.4_Atuando na integração de diferentes fontes de dados através de plataformas proprietárias como Stitch Data, Fivetran etc.
278. 6.h.5_Modelando soluções de arquitetura de dados, criando componentes de ingestão de dados, transformação e recuperação da informação.
279. 6.h.6_Desenvolvendo/cuidando da manutenção de repositórios de dados baseados em streaming de eventos como Data Lakes e Data Lakehouses.
280. 6.h.7_Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.
281. 6.h.8_Cuidando da qualidade dos dados, metadados e dicionário de dados.
282. 6.h.9_Nenhuma das opções listadas refletem meu dia a dia.
283. 6.h_maior_tempo_gasto_como_de
284. 7.a.1_Processo e analiso dados utilizando linguagens de programação como Python, R etc.
285. 7.a.2_Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.
286. 7.a.3_Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.
287. 7.a.4_Utilizo API\s para extrair dados e complementar minhas análises.
288. 7.a.5_Realizo experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.
289. 7.a.6_Desenvolvo/cuido da manutenção de ETL\s utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.
290. 7.a.7_Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts etc.
291. 7.a.8_Desenvolvo/cuido da manutenção de planilhas para atender as áreas de negócio.
292. 7.a.9_Utilizo ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises de dados.
293. 7.a.10_Nenhuma das opções listadas refletem meu dia a dia.
294. 7.a_rotina_como_da
295. 7.b.1_Scripts Python
296. 7.b.2_SQL & Stored Procedures
297. 7.b.3_Apache Airflow
298. 7.b.4_Apache NiFi
299. 7.b.5_Luigi
300. 7.b.6_AWS Glue
301. 7.b.7_Talend
302. 7.b.8_Pentaho
303. 7.b.9_Alteryx
304. 7.b.10_Stitch
305. 7.b.11_Fivetran
306. 7.b.12_Google Dataflow
307. 7.b.13_Oracle Data Integrator
308. 7.b.14_IBM DataStage
309. 7.b.15_SAP BW ETL
310. 7.b.16_SQL Server Integration Services (SSIS)
311. 7.b.17_SAS Data Integration
312. 7.b.18_Qlik Sense
313. 7.b.19_Knime
314. 7.b.20_Databricks
315. 7.b.21_Não utilizo ferramentas de ETL
316. 7.b_ferramentas_etl_da
317. 7.c.1_Ferramentas de AutoML como H2O.ai, Data Robot, BigML etc.
318. 7.c.2_"Point and Click" Analytics como Alteryx, Knime, Rapidminer etc.
319. 7.c.3_Product metricts & Insights como Mixpanel, Amplitude, Adobe Analytics.
320. 7.c.4_Ferramentas de análise dentro de ferramentas de CRM como Salesforce Einstein Anaytics ou Zendesk dashboards.
321. 7.c.5_Minha empresa não utiliza essas ferramentas.
322. 7.c.6_Não sei informar.
323. 7.c_ferramentas_autonomia_area_de_negocios
324. 7.d.1_Processando e analisando dados utilizando linguagens de programação como Python, R etc.
325. 7.d.2_Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.
326. 7.d.3_Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.
327. 7.d.4_Utilizando API's para extrair dados e complementar minhas análises.
328. 7.d.5_Realizando experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.
329. 7.d.6_Desenvolvendo/cuidando da manutenção de ETL's utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.
330. 7.d.7_Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados como Data Warehouses, Data Marts, Datasets etc.
331. 7.d.8_Desenvolvendo/cuidando da manutenção de planilhas para atender as áreas de negócio.
332. 7.d.9_Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises de dados.
333. 7.d.10_Nenhuma das opções listadas refletem meu dia a dia.
334. 7.d_maior_tempo_gasto_como_da
335. 8.a.1_Estudos Ad-hoc com o objetivo de confirmar hipóteses, realizar modelos preditivos, forecasts, análise de cluster para resolver problemas pontuais e responder perguntas das áreas de negócio.
336. 8.a.2_Sou responsável pela coleta e limpeza dos dados que uso para análise e modelagem.
337. 8.a.3_Sou responsável por entrar em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.
338. 8.a.4_Desenvolvo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).
339. 8.a.5_Sou responsável por colocar modelos em produção, criar os pipelines de dados, APIs de consumo e monitoramento.
340. 8.a.6_Cuido da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.
341. 8.a.7_Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc
342. 8.a.8_Utilizo ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.
343. 8.a.9_Crio e dou manutenção em ETLs, DAGs e automações de pipelines de dados.
344. 8.a.10_Crio e gerencio soluções de Feature Store e cultura de MLOps.
345. 8.a.11_Sou responsável por criar e manter a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)
346. 8.a.12_Treino e aplico LLM's para solucionar problemas de negócio.
347. 8.a_rotina_como_ds
348. 8.b.1_Utilizo modelos de regressão (linear, logística, GLM).
349. 8.b.2_Utilizo redes neurais ou modelos baseados em árvore para criar modelos de classificação.
350. 8.b.3_Desenvolvo sistemas de recomendação (RecSys).
351. 8.b.4_Utilizo métodos estatísticos Bayesianos para analisar dados.
352. 8.b.5_Utilizo técnicas de NLP (Natural Language Processing) para análisar dados não-estruturados.
353. 8.b.6_Utilizo métodos estatísticos clássicos (Testes de hipótese, análise multivariada, sobrevivência, dados longitudinais, inferência estatistica) para analisar dados.
354. 8.b.7_Utilizo cadeias de Markov ou HMM\s para realizar análises de dados.
355. 8.b.8_Desenvolvo técnicas de Clusterização (K-means, Spectral, DBScan etc).
356. 8.b.9_Realizo previsões através de modelos de Séries Temporais (Time Series).
357. 8.b.10_Utilizo modelos de Reinforcement Learning (aprendizado por reforço).
358. 8.b.11_Utilizo modelos de Machine Learning para detecção de fraude.
359. 8.b.12_Utilizo métodos de Visão Computacional.
360. 8.b.13_Utilizo modelos de Detecção de Churn.
361. 8.b.14_Utilizo LLM's para solucionar problemas de negócio.
362. 8.b_tecnicas_e_metodos_ds
363. 8.c.1_Ferramentas de BI (PowerBI, Looker, Tableau, Qlik etc).
364. 8.c.2_Planilhas (Excel, Google Sheets etc).
365. 8.c.3_Ambientes de desenvolvimento local (R-studio, JupyterLab, Anaconda).
366. 8.c.4_Ambientes de desenvolvimento na nuvem (Google Colab, AWS Sagemaker, Kaggle Notebooks etc).
367. 8.c.5_Ferramentas de AutoML (Datarobot, H2O, Auto-Keras etc).
368. 8.c.6_Ferramentas de ETL (Apache Airflow, NiFi, Stitch, Fivetran, Pentaho etc).
369. 8.c.7_Plataformas de Machine Learning (TensorFlow, Azure Machine Learning, Kubeflow etc).
370. 8.c.8_Feature Store (Feast, Hopsworks, AWS Feature Store, Databricks Feature Store etc).
371. 8.c.9_Sistemas de controle de versão (Github, DVC, Neptune, Gitlab etc).
372. 8.c.10_Plataformas de Data Apps (Streamlit, Shiny, Plotly Dash etc).
373. 8.c.11_Ferramentas de estatística avançada como SPSS, SAS, etc.
374. 8.c_tecnologias_ds
375. 8.d.1_Estudos Ad-hoc com o objetivo de confirmar hipóteses, realizar modelos preditivos, forecasts, análise de cluster para resolver problemas pontuais e responder perguntas das áreas de negócio.
376. 8.d.2_Coletando e limpando dos dados que uso para análise e modelagem.
377. 8.d.3_Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.
378. 8.d.4_Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).
379. 8.d.5_Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.
380. 8.d.6_Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.
381. 8.d.7_Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc.
382. 8.d.8_Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.
383. 8.d.9_Criando e dando manutenção em ETLs, DAGs e automações de pipelines de dados.

### Limpando

In [52]:
# 1. Função de limpeza (igual a do 2024)
def limpar_nomes(col):
    col = str(col).strip()
    col = re.sub(r'^\d+(\.[a-zA-Z0-9]+)*[_\s]+', '', col) # Tira o código do início
    col = col.lower()
    col = ''.join(c for c in unicodedata.normalize('NFD', col) if unicodedata.category(c) != 'Mn') # Tira acentos
    col = col.replace(' ', '_').replace('/', '_').replace('-', '_')
    col = col.replace('?', '').replace('(', '').replace(')', '').replace("'", '').replace('"', '')
    return col

df_2025.columns = [limpar_nomes(c) for c in df_2025.columns]
df_2025 = df_2025.replace({True: 1, False: 0, 'TRUE': 1, 'FALSE': 0}) # Padroniza booleanos

# 2. Deduplicar gêmeas (ETL de Engenheiro vs Analista, etc.)
cols = df_2025.columns.tolist()
contador = {}
for i, nome in enumerate(cols):
    if nome in contador:
        contador[nome] += 1
        cols[i] = f"{nome}__{contador[nome]}"
    else:
        contador[nome] = 0
df_2025.columns = cols

# 3. Dicionários de Tradução (Reutilizando a de 2024)
traducao_restante = {
    'modelo_de_trabalho_atual': 'atualmente_qual_a_sua_forma_de_trabalho',
    'modelo_de_trabalho_ideal': 'qual_a_forma_de_trabalho_ideal_para_voce',
    'atitude_em_caso_de_retorno_presencial': 'caso_sua_empresa_decida_pelo_modelo_100pct_presencial_qual_sera_sua_atitude',
    'contratar_talentos': 'a_contratar_novos_talentos',
    'convencer_a_empresa_a_aumentar_investimentos': 'c_convencer_a_empresa_a_aumentar_os_investimentos_na_area_de_dados',
    'gestao_de_equipes_no_ambiente_remoto': 'd_gestao_de_equipes_no_ambiente_remoto',
    'gestao_de_projetos_envolvendo_areas_multidisciplinares': 'e_gestao_de_projetos_envolvendo_areas_multidisciplinares_da_empresa',
    'organizar_as_informacoes_com_qualidade_e_confiabilidade': 'f_organizar_as_informacoes_e_garantir_a_qualidade_e_confiabilidade',
    'processar_e_armazenar_um_alto_volume_de_dados': 'g_conseguir_processar_e_armazenar_um_alto_volume_de_dados',
    'gerar_valor_para_as_areas_de_negocios': 'h_conseguir_gerar_valor_para_as_areas_de_negocios_atraves_de_estudos_e_experimentos',
    'desenvolver_e_manter_modelos_machine_learning_em_producao': 'i_desenvolver_e_manter_modelos_machine_learning_em_producao',
    'gerenciar_a_expectativa_das_areas': 'j_gerenciar_a_expectativa_das_areas_de_negocio_em_relacao_as_entregas_das_equipes_de_dados',
    'garantir_a_manutencao_dos_projetos_e_modelos_em_producao': 'k_garantir_a_manutencao_dos_projetos_e_modelos_em_producao,_em_meio_ao_crescimento_da_empresa',
    'conseguir_levar_inovacao_para_a_empresa': 'conseguir_levar_inovacao_para_a_empresa_atraves_dos_dados',
    'garantir_roi_em_projetos_de_dados': 'garantir_retorno_do_investimento_roi_em_projetos_de_dados',
    'ai_generativa_e_llm_e_uma_prioridade': 'ai_generativa_e_uma_prioridade_em_sua_empresa',
    'ai_generativa_e_llms_para_melhorar_produtos_externos_para_os_clientes_finais': 'ai_generativa_e_llms_para_melhorar_produtos_externos',
    'atuacao_em_dados': 'atuacao',
    'nao_utilizo_nenhuma_das_linguagens_listadas': 'nao_utilizo_nenhuma_linguagem',
    'linguagem_mais_usada': 'entre_as_linguagens_listadas_abaixo,_qual_e_a_que_voce_mais_utiliza_no_trabalho',
    'ferramenta_de_bi_dia_a_dia': 'ferramenta_de_bi_utilizada_no_dia_a_dia',
    'usa_chatgpt_ou_copilot_no_trabalho': 'utiliza_chatgpt_ou_llms_no_trabalho',
    'possui_data_lake': 'sua_organizacao_possui_um_data_lake',
    'possui_data_warehouse': 'sua_organizacao_possui_um_data_warehouse',
    'plano_de_carreira_e_oportunidades_de_crescimento': 'plano_de_carreira_e_oportunidades_de_crescimento_profissional',
}

correcao_troca = {
    'remuneracao_salario': 'salario_atual_nao_corresponde_ao_mercado',
    'beneficios': 'gostaria_de_receber_mais_beneficios',
    'ambiente_e_clima_de_trabalho': 'o_clima_de_trabalho_ambiente_nao_e_bom',
    'maturidade_da_empresa_em_termos_de_tecnologia_e_dados': 'falta_de_maturidade_analitica_na_empresa',
    'oportunidades_de_crescimento': 'falta_de_oportunidade_de_crescimento_no_emprego_atual',
    'relacao_com_os_gestores_e_lideres': 'nao_tenho_uma_boa_relacao_com_meu_lider_gestor',
    'gostaria_de_trabalhar_em_outra_area': 'gostaria_de_trabalhar_em_em_outra_area_de_atuacao',
    'remuneracao_salario__1': 'remuneracao_salario',
    'beneficios__1': 'beneficios',
    'proposito_do_trabalho_e_da_empresa__1': 'proposito_do_trabalho_e_da_empresa',
    'flexibilidade_de_trabalho_remoto__1': 'flexibilidade_de_trabalho_remoto',
    'ambiente_e_clima_de_trabalho__1': 'ambiente_e_clima_de_trabalho',
    'oportunidade_de_aprendizado_e_trabalhar_com_referencias__1': 'oportunidade_de_aprendizado_e_trabalhar_com_referencias_na_area',
    'maturidade_da_empresa_em_termos_de_tecnologia_e_dados__1': 'maturidade_da_empresa_em_termos_de_tecnologia_e_dados',
    'reputacao_que_a_empresa_tem_no_mercado__1': 'reputacao_que_a_empresa_tem_no_mercado',
    'relacao_com_os_gestores_e_lideres__1': 'qualidade_dos_gestores_e_lideres',
}

# Aplica as traduções (só o que existir no 2025)
for dicionario in [traducao_restante, correcao_troca]:
    valida = {k: v for k, v in dicionario.items() if k in df_2025.columns}
    df_2025 = df_2025.rename(columns=valida)

# 4. Filtrar apenas as colunas que a minha Silver 2023 tem!
colunas_2023 = df_silver_2023.columns.tolist()
colunas_existentes = [c for c in colunas_2023 if c in df_2025.columns]
df_silver_2025 = df_2025[colunas_existentes].copy()

# 5. Limpar nomes perigosos (%, ?, .) para o Athena não reclamar
renomear = {}
for c in df_silver_2025.columns:
    limpo = c.replace('%', 'pct').replace('?', '').rstrip('.')
    if limpo != c:
        renomear[c] = limpo
df_silver_2025 = df_silver_2025.rename(columns=renomear)

# 6. Resultado
print(f"Shape final 2025: {df_silver_2025.shape}")
print(f"Colunas que o 2025 não tem em relação ao 2023: {len(colunas_2023) - len(colunas_existentes)}")

Shape final 2025: (3495, 168)
Colunas que o 2025 não tem em relação ao 2023: 27

In [53]:
for i, coluna in enumerate(df_silver_2025.columns):
    print(f'{i}. {coluna}')

0. idade
1. faixa_idade
2. genero
3. cor_raca_etnia
4. pcd
5. quantidade_de_oportunidades_de_emprego_vagas_recebidas
6. senioridade_das_vagas_recebidas_em_relacao_a_sua_experiencia
7. aprovacao_em_processos_seletivos_entrevistas
8. oportunidades_de_progressao_de_carreira
9. estado_onde_mora
10. uf_onde_mora
11. regiao_onde_mora
12. nivel_de_ensino
13. area_de_formacao
14. setor
15. cargo_atual
16. nivel
17. faixa_salarial
18. atualmente_qual_a_sua_forma_de_trabalho
19. qual_a_forma_de_trabalho_ideal_para_voce
20. caso_sua_empresa_decida_pelo_modelo_100pct_presencial_qual_sera_sua_atitude
21. falta_de_oportunidade_de_crescimento_no_emprego_atual
22. salario_atual_nao_corresponde_ao_mercado
23. nao_tenho_uma_boa_relacao_com_meu_lider_gestor
24. gostaria_de_trabalhar_em_em_outra_area_de_atuacao
25. gostaria_de_receber_mais_beneficios
26. o_clima_de_trabalho_ambiente_nao_e_bom
27. falta_de_maturidade_analitica_na_empresa
28. remuneracao_salario
29. beneficios
30. proposito_do_trabalho_e_da_empresa
31. proposito_do_trabalho_e_da_empresa
32. flexibilidade_de_trabalho_remoto
33. flexibilidade_de_trabalho_remoto
34. ambiente_e_clima_de_trabalho
35. oportunidade_de_aprendizado_e_trabalhar_com_referencias_na_area
36. plano_de_carreira_e_oportunidades_de_crescimento_profissional
37. maturidade_da_empresa_em_termos_de_tecnologia_e_dados
38. qualidade_dos_gestores_e_lideres
39. reputacao_que_a_empresa_tem_no_mercado
40. reputacao_que_a_empresa_tem_no_mercado
41. a_contratar_novos_talentos
42. c_convencer_a_empresa_a_aumentar_os_investimentos_na_area_de_dados
43. d_gestao_de_equipes_no_ambiente_remoto
44. e_gestao_de_projetos_envolvendo_areas_multidisciplinares_da_empresa
45. f_organizar_as_informacoes_e_garantir_a_qualidade_e_confiabilidade
46. g_conseguir_processar_e_armazenar_um_alto_volume_de_dados
47. h_conseguir_gerar_valor_para_as_areas_de_negocios_atraves_de_estudos_e_experimentos
48. i_desenvolver_e_manter_modelos_machine_learning_em_producao
49. j_gerenciar_a_expectativa_das_areas_de_negocio_em_relacao_as_entregas_das_equipes_de_dados
50. k_garantir_a_manutencao_dos_projetos_e_modelos_em_producao,_em_meio_ao_crescimento_da_empresa
51. conseguir_levar_inovacao_para_a_empresa_atraves_dos_dados
52. garantir_retorno_do_investimento_roi_em_projetos_de_dados
53. dividir_o_tempo_entre_entregas_tecnicas_e_gestao
54. ai_generativa_e_uma_prioridade_em_sua_empresa
55. colaboradores_usando_ai_generativa_de_forma_independente_e_descentralizada
56. direcionamento_centralizado_do_uso_de_ai_generativa
57. desenvolvedores_utilizando_copilots
58. ai_generativa_e_llms_para_melhorar_produtos_externos
59. ai_generativa_e_llms_para_melhorar_produtos_internos_para_os_colaboradores
60. ia_generativa_e_llms_como_principal_frente_do_negocio
61. ia_generativa_e_llms_nao_e_prioridade
62. nao_sei_opinar_sobre_o_uso_de_ia_generativa_e_llms_na_empresa
63. falta_de_compreensao_dos_casos_de_uso
64. falta_de_confiabilidade_das_saidas_alucinacao_dos_modelos
65. incerteza_em_relacao_a_regulamentacao
66. preocupacoes_com_seguranca_e_privacidade_de_dados
67. retorno_sobre_investimento_roi_nao_comprovado_de_ia_generativa
68. dados_da_empresa_nao_estao_prontos_para_uso_de_ia_generativa
69. falta_de_expertise_ou_falta_de_recursos
70. alta_direcao_da_empresa_nao_ve_valor_ou_nao_ve_como_prioridade
71. preocupacoes_com_propriedade_intelectual
72. atuacao
73. sql
74. r
75. python
76. c_c++_c#
77. julia
78. visual_basic_vba
79. scala
80. rust
81. nao_utilizo_nenhuma_linguagem
82. mysql
83. oracle
84. sql_server
85. amazon_aurora_ou_rds
86. dynamodb
87. coachdb
88. cassandra
89. mongodb
90. mariadb
91. datomic
92. s3
93. postgresql
94. elasticsearch
95. db2
96. microsoft_access
97. sqlite
98. sybase
99. firebase
100. vertica
101. redis
102. neo4j
103. google_bigquery
104. google_firestore
105. amazon_redshift
106. amazon_athena
107. snowflake
108. databricks
109. hbase
110. presto
111. splunk
112. sap_hana
113. hive
114. firebird
115. azure_microsoft
116. amazon_web_services_aws
117. google_cloud_gcp
118. oracle_cloud
119. ibm
120. servidores_on_premise_nao_utilizamos_cloud
121. cloud_propria
122. cloud_preferida
123. ferramenta_de_bi_utilizada_no_dia_a_dia
124. microsoft_powerbi
125. qlik_view_qlik_sense
126. tableau
127. metabase
128. superset
129. redash
130. looker
131. looker_studiogoogle_data_studio
132. amazon_quicksight
133. alteryx
134. sap_business_objects_sap_analytics
135. oracle_business_intelligence
136. salesforce_einstein_analytics
137. sas_visual_analytics
138. grafana
139. pentaho
140. fazemos_todas_as_analises_utilizando_apenas_excel_ou_planilhas_do_google
141. nao_utilizo_nenhuma_ferramenta_de_bi_no_trabalho
142. utiliza_chatgpt_ou_llms_no_trabalho
143. nao_uso_solucoes_de_ai_generativa_com_foco_em_produtividade
144. uso_solucoes_gratuitas_de_ai_generativa_com_foco_em_produtividade
145. uso_e_pago_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade
146. a_empresa_que_trabalho_paga_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade
147. uso_solucoes_do_tipo_copilot
148. scripts_python
149. sql_&_stored_procedures
150. apache_airflow
151. apache_nifi
152. luigi
153. aws_glue
154. talend
155. stitch
156. fivetran
157. google_dataflow
158. oracle_data_integrator
159. ibm_datastage
160. sap_bw_etl
161. sql_server_integration_services_ssis
162. sas_data_integration
163. qlik_sense
164. knime
165. nao_utilizo_ferramentas_de_etl
166. sua_organizacao_possui_um_data_lake
167. sua_organizacao_possui_um_data_warehouse

In [54]:
faltam_2025 = [c for c in colunas_2023 if c not in df_silver_2025.columns]
print(faltam_2025)

['id', 'experiencia_prejudicada_devido_a_minha_identidade_de_genero', 'experiencia_prejudicada_devido_a_minha_cor_raca_etnia', 'experiencia_prejudicada_devido_ao_fato_de_ser_pcd', 'qual_sua_situacao_atual_de_trabalho', 'quanto_tempo_de_experiencia_na_area_de_dados_voce_tem', 'quanto_tempo_de_experiencia_na_area_de_ti_engenharia_de_software_voce_teve_antes_de_comecar_a_trabalhar_na_area_de_dados', 'voce_esta_satisfeito_na_sua_empresa_atual', 'qual_o_principal_motivo_da_sua_insatisfacao_com_a_empresa_atual', 'b_reter_talentos', '.net', 'java', 'sas_stata', 'matlab', 'php', 'javascript', 'entre_as_linguagens_listadas_abaixo,_qual_e_a_que_voce_mais_utiliza_no_trabalho', 'mode', 'microstrategy', 'ibm_analytics_cognos', 'birst', 'tibco_spotfire', 'ambientes_de_desenvolvimento_na_nuvem_google_colab,_aws_sagemaker,_kaggle_notebooks_etc', 'plataformas_de_machine_learning_tensorflow,_azure_machine_learning,_kubeflow_etc', 'feature_store_feast,_hopsworks,_aws_feature_store,_databricks_feature_store_etc', 'sistemas_de_controle_de_versao_github,_dvc,_neptune,_gitlab_etc', 'plataformas_de_data_apps_streamlit,_shiny,_plotly_dash_etc']

In [55]:
# --- Dicionário das correções esquecidas ---
traducao_esquecida = {
    'token': 'id',  # o id do 2025!
    'sim,_devido_a_minha_identidade_de_genero': 'experiencia_prejudicada_devido_a_minha_identidade_de_genero',
    'sim,_devido_a_minha_cor_raca_etnia': 'experiencia_prejudicada_devido_a_minha_cor_raca_etnia',
    'sim,_devido_ao_fato_de_ser_pcd': 'experiencia_prejudicada_devido_ao_fato_de_ser_pcd',
}

# Aplica (só o que existir)
valida = {k: v for k, v in traducao_esquecida.items() if k in df_2025.columns}
df_2025 = df_2025.rename(columns=valida)
print(f"{len(valida)} correções aplicadas!")

# --- Remonta a Silver 2025 ---
colunas_existentes = [c for c in colunas_2023 if c in df_2025.columns]
df_silver_2025 = df_2025[colunas_existentes].copy()

# --- Confere ---
faltam = [c for c in colunas_2023 if c not in df_silver_2025.columns]
print(f"Novo shape: {df_silver_2025.shape}")
print(f"Ainda faltam: {len(faltam)}")
print(faltam[:10])

4 correções aplicadas!
Novo shape: (3495, 172)
Ainda faltam: 23
['qual_sua_situacao_atual_de_trabalho', 'quanto_tempo_de_experiencia_na_area_de_dados_voce_tem', 'quanto_tempo_de_experiencia_na_area_de_ti_engenharia_de_software_voce_teve_antes_de_comecar_a_trabalhar_na_area_de_dados', 'voce_esta_satisfeito_na_sua_empresa_atual', 'qual_o_principal_motivo_da_sua_insatisfacao_com_a_empresa_atual', 'b_reter_talentos', '.net', 'java', 'sas_stata', 'matlab']

In [56]:
#DROPAR DUAS COLUNAS MANUALMENTE
# Mantém a ÚLTIMA ocorrência  e descarta a gêmea de insatisfação
df_silver_2025 = df_silver_2025.loc[:, ~df_silver_2025.columns.duplicated(keep='last')]

# O MESMO bug aconteceu no 2024! Corrige ele também:
df_silver_2024 = df_silver_2024.loc[:, ~df_silver_2024.columns.duplicated(keep='last')]

# Confere que zerou nos dois:
print(df_silver_2025.columns[df_silver_2025.columns.duplicated()].tolist())  # []
print(df_silver_2024.columns[df_silver_2024.columns.duplicated()].tolist())  # []

print(df_silver_2025.shape, df_silver_2024.shape)

[]
[]
(3495, 169) (5217, 187)

In [57]:
# --- Confere ---
faltam = [c for c in colunas_2023 if c not in df_silver_2025.columns]
print(f"Novo shape: {df_silver_2025.shape}")
print(f"Ainda faltam: {len(faltam)}")
print(faltam[:10])

Novo shape: (3495, 169)
Ainda faltam: 23
['qual_sua_situacao_atual_de_trabalho', 'quanto_tempo_de_experiencia_na_area_de_dados_voce_tem', 'quanto_tempo_de_experiencia_na_area_de_ti_engenharia_de_software_voce_teve_antes_de_comecar_a_trabalhar_na_area_de_dados', 'voce_esta_satisfeito_na_sua_empresa_atual', 'qual_o_principal_motivo_da_sua_insatisfacao_com_a_empresa_atual', 'b_reter_talentos', '.net', 'java', 'sas_stata', 'matlab']

In [58]:
# --- Traduções esquecidas no script principal ---
traducao_extra_2025 = {
    'situacao_de_trabalho': 'qual_sua_situacao_atual_de_trabalho',
    'tempo_de_experiencia_em_dados': 'quanto_tempo_de_experiencia_na_area_de_dados_voce_tem',
    'tempo_de_experiencia_em_ti': 'quanto_tempo_de_experiencia_na_area_de_ti_engenharia_de_software_voce_teve_antes_de_comecar_a_trabalhar_na_area_de_dados',
    'satisfeito_atualmente': 'voce_esta_satisfeito_na_sua_empresa_atual',
    'motivo_insatisfacao': 'qual_o_principal_motivo_da_sua_insatisfacao_com_a_empresa_atual',
    'reter_talentos': 'b_reter_talentos',
}

valida = {k: v for k, v in traducao_extra_2025.items() if k in df_2025.columns}
df_2025 = df_2025.rename(columns=valida)
print(f"{len(valida)} traduções aplicadas!")

# --- Procurar às linguagens sumidas (existem com outro nome?) ---
print("\nProcurando .net/java/sas/matlab no 2025:")
print([c for c in df_2025.columns if any(x in c.lower() for x in ['java', 'net', 'matlab', 'sas'])])

# --- Remonta a Silver 2025 (com dedup de gêmeas de novo!) ---
colunas_existentes = [c for c in colunas_2023 if c in df_2025.columns]
df_silver_2025 = df_2025[colunas_existentes].copy()
df_silver_2025 = df_silver_2025.loc[:, ~df_silver_2025.columns.duplicated(keep='last')]

faltam = [c for c in colunas_2023 if c not in df_silver_2025.columns]
print(f"\n Shape final: {df_silver_2025.shape}")
print(f"Mortas de verdade: {len(faltam)}")
print(faltam)

6 traduções aplicadas!

Procurando .net/java/sas/matlab no 2025:
['sas_visual_analytics', 'desenvolvo_pipelines_de_dados_utilizando_linguagens_de_programacao_como_python,_scala,_java_etc.', 'sas_data_integration', 'desenvolvendo_pipelines_de_dados_utilizando_linguagens_de_programacao_como_python,_scala,_java_etc.', 'utilizo_ferramentas_avancadas_de_estatistica_como_sas,_spss,_stata_etc,_para_realizar_analises_de_dados.', 'sas_data_integration__1', 'minha_empresa_nao_utiliza_essas_ferramentas.', 'utilizando_ferramentas_avancadas_de_estatistica_como_sas,_spss,_stata_etc,_para_realizar_analises_de_dados.', 'utilizo_ferramentas_avancadas_de_estatistica_como_sas,_spss,_stata_etc,_para_realizar_analises.', 'ferramentas_de_estatistica_avancada_como_spss,_sas,_etc.', 'utilizando_ferramentas_avancadas_de_estatistica_como_sas,_spss,_stata_etc,_para_realizar_analises.']

 Shape final: (3495, 175)
Mortas de verdade: 17
['.net', 'java', 'sas_stata', 'matlab', 'php', 'javascript', 'entre_as_linguagens_listadas_abaixo,_qual_e_a_que_voce_mais_utiliza_no_trabalho', 'mode', 'microstrategy', 'ibm_analytics_cognos', 'birst', 'tibco_spotfire', 'ambientes_de_desenvolvimento_na_nuvem_google_colab,_aws_sagemaker,_kaggle_notebooks_etc', 'plataformas_de_machine_learning_tensorflow,_azure_machine_learning,_kubeflow_etc', 'feature_store_feast,_hopsworks,_aws_feature_store,_databricks_feature_store_etc', 'sistemas_de_controle_de_versao_github,_dvc,_neptune,_gitlab_etc', 'plataformas_de_data_apps_streamlit,_shiny,_plotly_dash_etc']

In [59]:
df_silver_2025

,id,idade,faixa_idade,genero,cor_raca_etnia,pcd,experiencia_prejudicada_devido_a_minha_identidade_de_genero,experiencia_prejudicada_devido_a_minha_cor_raca_etnia,experiencia_prejudicada_devido_ao_fato_de_ser_pcd,quantidade_de_oportunidades_de_emprego_vagas_recebidas,...,oracle_data_integrator,ibm_datastage,sap_bw_etl,sql_server_integration_services_ssis,sas_data_integration,qlik_sense,knime,nao_utilizo_ferramentas_de_etl,sua_organizacao_possui_um_data_lake,sua_organizacao_possui_um_data_warehouse
0,apeczcwvds75ba5hml4apec2pb35hflw,35,35-39,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,a27c74vkj7n8vmib88ca27c74sepwcpa,20,17-21,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7xpkv4qj7mzvsxemhpjy7xpkv4qu61oi,35,35-39,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ugzyokw0p1or7axwzugzyz4ombwfgzoo,29,25-29,Masculino,Parda,Não,0.0,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,n7aiatzlzonity0sn7aiat75y36iuqni,18,17-21,Masculino,Preta,Não,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3490,i0j62lwhuwodn4mppi0jxpd62jwc2u2r,21,17-21,Masculino,Parda,Não,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3491,hc0ek239suz0o5368o6hc0ek23q30ymn,22,22-24,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3492,y2bva0w5olmxvo4wy2bva6n4gt9uxhyy,31,30-34,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3493,lxsjvi0uhm1qlxqnxqglxsjvim5rydhv,37,35-39,Masculino,Parda,Não,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3494,omjm897gpg57dhomjmmgr25w3gq49pmm,41,40-44,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
faltam = [c for c in colunas_2023 if c not in df_silver_2025.columns]
print(faltam)          # esperado: ['.net', 'java', 'sas_stata', 'matlab']
print(df_silver_2025.shape)  # esperado: ~(3495, 176-178)

['.net', 'java', 'sas_stata', 'matlab', 'php', 'javascript', 'entre_as_linguagens_listadas_abaixo,_qual_e_a_que_voce_mais_utiliza_no_trabalho', 'mode', 'microstrategy', 'ibm_analytics_cognos', 'birst', 'tibco_spotfire', 'ambientes_de_desenvolvimento_na_nuvem_google_colab,_aws_sagemaker,_kaggle_notebooks_etc', 'plataformas_de_machine_learning_tensorflow,_azure_machine_learning,_kubeflow_etc', 'feature_store_feast,_hopsworks,_aws_feature_store,_databricks_feature_store_etc', 'sistemas_de_controle_de_versao_github,_dvc,_neptune,_gitlab_etc', 'plataformas_de_data_apps_streamlit,_shiny,_plotly_dash_etc']
(3495, 175)

## os 3 anos

In [61]:
def finalizar_silver(df, ano):
    print(f"\n===== {ano} =====")

    # --- 1) Checar linhas duplicadas (pelo id) ---
    dup = df['id'].duplicated().sum()
    print(f"IDs duplicados: {dup} | IDs nulos: {df['id'].isnull().sum()}")
    if dup > 0:
        df = df.drop_duplicates(subset=['id'])   # mesma pessoa 2x → mantém 1
        print("✔ Duplicatas removidas pelo id")

    # --- 2) Binárias (0/1): nulo vira 0 ("não marcou / não usa") ---
    binarias = [c for c in df.columns if set(df[c].dropna().unique()) <= {0, 1}]
    df[binarias] = df[binarias].fillna(0).astype(int)

    # --- 3) Texto/categoria: nulo vira 'Nao_informado' (ninguém some dos gráficos!) ---
    texto = [c for c in df.select_dtypes(include='object').columns if c != 'id']
    df[texto] = df[texto].fillna('Nao_informado')

    # --- 4) Tag do ano (para análise temporal!) ---
    df['ano'] = ano

    print(f"Shape final: {df.shape} | NaNs restantes: {df.isnull().sum().sum()}")
    return df

df_silver_2023 = finalizar_silver(df_silver_2023, 2023)
df_silver_2024 = finalizar_silver(df_silver_2024, 2024)
df_silver_2025 = finalizar_silver(df_silver_2025, 2025)

===== 2023 =====
IDs duplicados: 0 | IDs nulos: 0
Shape final: (5293, 193) | NaNs restantes: 0

===== 2024 =====
IDs duplicados: 2 | IDs nulos: 0
✔ Duplicatas removidas pelo id
Shape final: (5215, 188) | NaNs restantes: 0

===== 2025 =====
IDs duplicados: 1 | IDs nulos: 0
✔ Duplicatas removidas pelo id
Shape final: (3494, 176) | NaNs restantes: 0

In [62]:
df_silver_2024['id'].duplicated().sum()

np.int64(0)

In [63]:
for nome, df in [('2023', df_silver_2023), ('2024', df_silver_2024), ('2025', df_silver_2025)]:
    print(f"--- {nome} ---")
    print(f"Shape: {df.shape}")
    print(f"Tem id? {'id' in df.columns} | Tem ano? {'ano' in df.columns}")
    print(f"IDs duplicados: {df['id'].duplicated().sum()}")
    print(f"Colunas duplicadas: {df.columns.duplicated().sum()}")
    print(f"NaNs restantes: {df.isnull().sum().sum()}")

--- 2023 ---
Shape: (5293, 193)
Tem id? True | Tem ano? True
IDs duplicados: 0
Colunas duplicadas: 0
NaNs restantes: 0
--- 2024 ---
Shape: (5215, 188)
Tem id? True | Tem ano? True
IDs duplicados: 0
Colunas duplicadas: 0
NaNs restantes: 0
--- 2025 ---
Shape: (3494, 176)
Tem id? True | Tem ano? True
IDs duplicados: 0
Colunas duplicadas: 0
NaNs restantes: 0

### Unificando os anos

In [64]:
# Interseção das colunas dos 3 anos
comuns = sorted(set(df_silver_2023.columns) & set(df_silver_2024.columns) & set(df_silver_2025.columns))

df_unificado = pd.concat([
    df_silver_2023[comuns],
    df_silver_2024[comuns],
    df_silver_2025[comuns]
], ignore_index=True)

print(df_unificado.shape)   # ~14.000 linhas x ~176 colunas
df_unificado.to_parquet('silver_unificado.parquet', index=False)

(14002, 176)

In [65]:
for i, coluna in enumerate(df_unificado.columns):
    print(f'{i}. {coluna}')

0. a_contratar_novos_talentos
1. a_empresa_que_trabalho_paga_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade
2. ai_generativa_e_llms_para_melhorar_produtos_externos
3. ai_generativa_e_llms_para_melhorar_produtos_internos_para_os_colaboradores
4. ai_generativa_e_uma_prioridade_em_sua_empresa
5. alta_direcao_da_empresa_nao_ve_valor_ou_nao_ve_como_prioridade
6. alteryx
7. amazon_athena
8. amazon_aurora_ou_rds
9. amazon_quicksight
10. amazon_redshift
11. amazon_web_services_aws
12. ambiente_e_clima_de_trabalho
13. ano
14. apache_airflow
15. apache_nifi
16. aprovacao_em_processos_seletivos_entrevistas
17. area_de_formacao
18. atuacao
19. atualmente_qual_a_sua_forma_de_trabalho
20. aws_glue
21. azure_microsoft
22. b_reter_talentos
23. beneficios
24. c_c++_c#
25. c_convencer_a_empresa_a_aumentar_os_investimentos_na_area_de_dados
26. cargo_atual
27. caso_sua_empresa_decida_pelo_modelo_100pct_presencial_qual_sera_sua_atitude
28. cassandra
29. cloud_preferida
30. cloud_propria
31. coachdb
32. colaboradores_usando_ai_generativa_de_forma_independente_e_descentralizada
33. conseguir_levar_inovacao_para_a_empresa_atraves_dos_dados
34. cor_raca_etnia
35. d_gestao_de_equipes_no_ambiente_remoto
36. dados_da_empresa_nao_estao_prontos_para_uso_de_ia_generativa
37. databricks
38. datomic
39. db2
40. desenvolvedores_utilizando_copilots
41. direcionamento_centralizado_do_uso_de_ai_generativa
42. dividir_o_tempo_entre_entregas_tecnicas_e_gestao
43. dynamodb
44. e_gestao_de_projetos_envolvendo_areas_multidisciplinares_da_empresa
45. elasticsearch
46. estado_onde_mora
47. experiencia_prejudicada_devido_a_minha_cor_raca_etnia
48. experiencia_prejudicada_devido_a_minha_identidade_de_genero
49. experiencia_prejudicada_devido_ao_fato_de_ser_pcd
50. f_organizar_as_informacoes_e_garantir_a_qualidade_e_confiabilidade
51. faixa_idade
52. faixa_salarial
53. falta_de_compreensao_dos_casos_de_uso
54. falta_de_confiabilidade_das_saidas_alucinacao_dos_modelos
55. falta_de_expertise_ou_falta_de_recursos
56. falta_de_maturidade_analitica_na_empresa
57. falta_de_oportunidade_de_crescimento_no_emprego_atual
58. fazemos_todas_as_analises_utilizando_apenas_excel_ou_planilhas_do_google
59. ferramenta_de_bi_utilizada_no_dia_a_dia
60. firebase
61. firebird
62. fivetran
63. flexibilidade_de_trabalho_remoto
64. g_conseguir_processar_e_armazenar_um_alto_volume_de_dados
65. garantir_retorno_do_investimento_roi_em_projetos_de_dados
66. genero
67. google_bigquery
68. google_cloud_gcp
69. google_dataflow
70. google_firestore
71. gostaria_de_receber_mais_beneficios
72. gostaria_de_trabalhar_em_em_outra_area_de_atuacao
73. grafana
74. h_conseguir_gerar_valor_para_as_areas_de_negocios_atraves_de_estudos_e_experimentos
75. hbase
76. hive
77. i_desenvolver_e_manter_modelos_machine_learning_em_producao
78. ia_generativa_e_llms_como_principal_frente_do_negocio
79. ia_generativa_e_llms_nao_e_prioridade
80. ibm
81. ibm_datastage
82. id
83. idade
84. incerteza_em_relacao_a_regulamentacao
85. j_gerenciar_a_expectativa_das_areas_de_negocio_em_relacao_as_entregas_das_equipes_de_dados
86. julia
87. k_garantir_a_manutencao_dos_projetos_e_modelos_em_producao,_em_meio_ao_crescimento_da_empresa
88. knime
89. looker
90. looker_studiogoogle_data_studio
91. luigi
92. mariadb
93. maturidade_da_empresa_em_termos_de_tecnologia_e_dados
94. metabase
95. microsoft_access
96. microsoft_powerbi
97. mongodb
98. mysql
99. nao_sei_opinar_sobre_o_uso_de_ia_generativa_e_llms_na_empresa
100. nao_tenho_uma_boa_relacao_com_meu_lider_gestor
101. nao_uso_solucoes_de_ai_generativa_com_foco_em_produtividade
102. nao_utilizo_ferramentas_de_etl
103. nao_utilizo_nenhuma_ferramenta_de_bi_no_trabalho
104. nao_utilizo_nenhuma_linguagem
105. neo4j
106. nivel
107. nivel_de_ensino
108. o_clima_de_trabalho_ambiente_nao_e_bom
109. oportunidade_de_aprendizado_e_trabalhar_com_referencias_na_area
110. oportunidades_de_progressao_de_carreira
111. oracle
112. oracle_business_intelligence
113. oracle_cloud
114. oracle_data_integrator
115. pcd
116. pentaho
117. plano_de_carreira_e_oportunidades_de_crescimento_profissional
118. postgresql
119. preocupacoes_com_propriedade_intelectual
120. preocupacoes_com_seguranca_e_privacidade_de_dados
121. presto
122. proposito_do_trabalho_e_da_empresa
123. python
124. qlik_sense
125. qlik_view_qlik_sense
126. qual_a_forma_de_trabalho_ideal_para_voce
127. qual_o_principal_motivo_da_sua_insatisfacao_com_a_empresa_atual
128. qual_sua_situacao_atual_de_trabalho
129. qualidade_dos_gestores_e_lideres
130. quantidade_de_oportunidades_de_emprego_vagas_recebidas
131. quanto_tempo_de_experiencia_na_area_de_dados_voce_tem
132. quanto_tempo_de_experiencia_na_area_de_ti_engenharia_de_software_voce_teve_antes_de_comecar_a_trabalhar_na_area_de_dados
133. r
134. redash
135. redis
136. regiao_onde_mora
137. remuneracao_salario
138. reputacao_que_a_empresa_tem_no_mercado
139. retorno_sobre_investimento_roi_nao_comprovado_de_ia_generativa
140. rust
141. s3
142. salario_atual_nao_corresponde_ao_mercado
143. salesforce_einstein_analytics
144. sap_business_objects_sap_analytics
145. sap_bw_etl
146. sap_hana
147. sas_data_integration
148. sas_visual_analytics
149. scala
150. scripts_python
151. senioridade_das_vagas_recebidas_em_relacao_a_sua_experiencia
152. servidores_on_premise_nao_utilizamos_cloud
153. setor
154. snowflake
155. splunk
156. sql
157. sql_&_stored_procedures
158. sql_server
159. sql_server_integration_services_ssis
160. sqlite
161. stitch
162. sua_organizacao_possui_um_data_lake
163. sua_organizacao_possui_um_data_warehouse
164. superset
165. sybase
166. tableau
167. talend
168. uf_onde_mora
169. uso_e_pago_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade
170. uso_solucoes_do_tipo_copilot
171. uso_solucoes_gratuitas_de_ai_generativa_com_foco_em_produtividade
172. utiliza_chatgpt_ou_llms_no_trabalho
173. vertica
174. visual_basic_vba
175. voce_esta_satisfeito_na_sua_empresa_atual

In [66]:
tem_duplicadas_id = df['id'].duplicated().any()
print(tem_duplicadas_id)

False

In [67]:
quantidade_id = df['id'].duplicated().sum()
print(quantidade_id)

0

In [68]:
primeiras = ['id', 'ano']
resto = [c for c in df_unificado.columns if c not in primeiras]
df_unificado = df_unificado[primeiras + resto]

In [69]:
df_unificado

,id,ano,a_contratar_novos_talentos,a_empresa_que_trabalho_paga_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade,ai_generativa_e_llms_para_melhorar_produtos_externos,ai_generativa_e_llms_para_melhorar_produtos_internos_para_os_colaboradores,ai_generativa_e_uma_prioridade_em_sua_empresa,alta_direcao_da_empresa_nao_ve_valor_ou_nao_ve_como_prioridade,alteryx,amazon_athena,...,tableau,talend,uf_onde_mora,uso_e_pago_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade,uso_solucoes_do_tipo_copilot,uso_solucoes_gratuitas_de_ai_generativa_com_foco_em_produtividade,utiliza_chatgpt_ou_llms_no_trabalho,vertica,visual_basic_vba,voce_esta_satisfeito_na_sua_empresa_atual
0,001b2d1qtli8t9z7oqgdhj001b2d4i0g,2023,0,0,0,0,Nao_informado,0,0,0,...,0,0,MG,0,0,0,Não utilizo nenhum tipo de solução de IA Gener...,0,0,0
1,0026aa3fwd78u0026asg7456tfkjg2cs,2023,0,0,0,0,Nao_informado,0,0,0,...,0,0,ES,1,0,0,Utilizo soluções pagas de AI Generativa (como ...,0,0,1
2,00r21rb9pusd1b0v7ew00r21rw3dy69w,2023,0,0,0,0,Nao_informado,0,1,1,...,1,0,SP,0,0,1,Utilizo apenas soluções gratuitas (como por ex...,0,0,1
3,00urm3jf2cek12w6ygue00urm3jzd17j,2023,0,0,0,0,Nao_informado,0,0,0,...,0,0,SP,0,0,0,Nao_informado,0,0,0
4,00v0az4g792svil00vn6y1kfm9hq8vy9,2023,0,0,0,0,Nao_informado,0,0,0,...,0,0,MG,0,0,1,Utilizo apenas soluções gratuitas (como por ex...,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13997,i0j62lwhuwodn4mppi0jxpd62jwc2u2r,2025,0,0,0,0,Nao_informado,0,0,0,...,0,0,SP,0,0,0,Nao_informado,0,0,1
13998,hc0ek239suz0o5368o6hc0ek23q30ymn,2025,0,0,0,0,Nao_informado,0,0,0,...,0,0,SP,0,0,0,Nao_informado,0,0,1
13999,y2bva0w5olmxvo4wy2bva6n4gt9uxhyy,2025,0,0,0,0,Nao_informado,0,0,0,...,0,0,SP,0,0,0,Nao_informado,0,0,1
14000,lxsjvi0uhm1qlxqnxqglxsjvim5rydhv,2025,0,0,0,0,Nao_informado,0,0,0,...,0,0,PI,0,0,0,Nao_informado,0,0,1
14001,omjm897gpg57dhomjmmgr25w3gq49pmm,2025,0,0,0,0,Nao_informado,0,0,0,...,0,0,PR,0,0,0,Nao_informado,0,0,1

In [70]:
ordem_2023 = [c for c in df_silver_2023.columns if c in df_unificado.columns]
df_unificado = df_unificado[ordem_2023]

In [71]:
for i, coluna in enumerate(df_unificado.columns):
    print(f'{i}. {coluna}')

0. id
1. idade
2. faixa_idade
3. genero
4. cor_raca_etnia
5. pcd
6. experiencia_prejudicada_devido_a_minha_identidade_de_genero
7. experiencia_prejudicada_devido_a_minha_cor_raca_etnia
8. experiencia_prejudicada_devido_ao_fato_de_ser_pcd
9. quantidade_de_oportunidades_de_emprego_vagas_recebidas
10. senioridade_das_vagas_recebidas_em_relacao_a_sua_experiencia
11. aprovacao_em_processos_seletivos_entrevistas
12. oportunidades_de_progressao_de_carreira
13. estado_onde_mora
14. uf_onde_mora
15. regiao_onde_mora
16. nivel_de_ensino
17. area_de_formacao
18. qual_sua_situacao_atual_de_trabalho
19. setor
20. cargo_atual
21. nivel
22. faixa_salarial
23. quanto_tempo_de_experiencia_na_area_de_dados_voce_tem
24. quanto_tempo_de_experiencia_na_area_de_ti_engenharia_de_software_voce_teve_antes_de_comecar_a_trabalhar_na_area_de_dados
25. atualmente_qual_a_sua_forma_de_trabalho
26. qual_a_forma_de_trabalho_ideal_para_voce
27. caso_sua_empresa_decida_pelo_modelo_100pct_presencial_qual_sera_sua_atitude
28. voce_esta_satisfeito_na_sua_empresa_atual
29. qual_o_principal_motivo_da_sua_insatisfacao_com_a_empresa_atual
30. falta_de_oportunidade_de_crescimento_no_emprego_atual
31. salario_atual_nao_corresponde_ao_mercado
32. nao_tenho_uma_boa_relacao_com_meu_lider_gestor
33. gostaria_de_trabalhar_em_em_outra_area_de_atuacao
34. gostaria_de_receber_mais_beneficios
35. o_clima_de_trabalho_ambiente_nao_e_bom
36. falta_de_maturidade_analitica_na_empresa
37. remuneracao_salario
38. beneficios
39. proposito_do_trabalho_e_da_empresa
40. flexibilidade_de_trabalho_remoto
41. ambiente_e_clima_de_trabalho
42. oportunidade_de_aprendizado_e_trabalhar_com_referencias_na_area
43. plano_de_carreira_e_oportunidades_de_crescimento_profissional
44. maturidade_da_empresa_em_termos_de_tecnologia_e_dados
45. qualidade_dos_gestores_e_lideres
46. reputacao_que_a_empresa_tem_no_mercado
47. a_contratar_novos_talentos
48. b_reter_talentos
49. c_convencer_a_empresa_a_aumentar_os_investimentos_na_area_de_dados
50. d_gestao_de_equipes_no_ambiente_remoto
51. e_gestao_de_projetos_envolvendo_areas_multidisciplinares_da_empresa
52. f_organizar_as_informacoes_e_garantir_a_qualidade_e_confiabilidade
53. g_conseguir_processar_e_armazenar_um_alto_volume_de_dados
54. h_conseguir_gerar_valor_para_as_areas_de_negocios_atraves_de_estudos_e_experimentos
55. i_desenvolver_e_manter_modelos_machine_learning_em_producao
56. j_gerenciar_a_expectativa_das_areas_de_negocio_em_relacao_as_entregas_das_equipes_de_dados
57. k_garantir_a_manutencao_dos_projetos_e_modelos_em_producao,_em_meio_ao_crescimento_da_empresa
58. conseguir_levar_inovacao_para_a_empresa_atraves_dos_dados
59. garantir_retorno_do_investimento_roi_em_projetos_de_dados
60. dividir_o_tempo_entre_entregas_tecnicas_e_gestao
61. ai_generativa_e_uma_prioridade_em_sua_empresa
62. colaboradores_usando_ai_generativa_de_forma_independente_e_descentralizada
63. direcionamento_centralizado_do_uso_de_ai_generativa
64. desenvolvedores_utilizando_copilots
65. ai_generativa_e_llms_para_melhorar_produtos_externos
66. ai_generativa_e_llms_para_melhorar_produtos_internos_para_os_colaboradores
67. ia_generativa_e_llms_como_principal_frente_do_negocio
68. ia_generativa_e_llms_nao_e_prioridade
69. nao_sei_opinar_sobre_o_uso_de_ia_generativa_e_llms_na_empresa
70. falta_de_compreensao_dos_casos_de_uso
71. falta_de_confiabilidade_das_saidas_alucinacao_dos_modelos
72. incerteza_em_relacao_a_regulamentacao
73. preocupacoes_com_seguranca_e_privacidade_de_dados
74. retorno_sobre_investimento_roi_nao_comprovado_de_ia_generativa
75. dados_da_empresa_nao_estao_prontos_para_uso_de_ia_generativa
76. falta_de_expertise_ou_falta_de_recursos
77. alta_direcao_da_empresa_nao_ve_valor_ou_nao_ve_como_prioridade
78. preocupacoes_com_propriedade_intelectual
79. atuacao
80. sql
81. r
82. python
83. c_c++_c#
84. julia
85. visual_basic_vba
86. scala
87. rust
88. nao_utilizo_nenhuma_linguagem
89. mysql
90. oracle
91. sql_server
92. amazon_aurora_ou_rds
93. dynamodb
94. coachdb
95. cassandra
96. mongodb
97. mariadb
98. datomic
99. s3
100. postgresql
101. elasticsearch
102. db2
103. microsoft_access
104. sqlite
105. sybase
106. firebase
107. vertica
108. redis
109. neo4j
110. google_bigquery
111. google_firestore
112. amazon_redshift
113. amazon_athena
114. snowflake
115. databricks
116. hbase
117. presto
118. splunk
119. sap_hana
120. hive
121. firebird
122. azure_microsoft
123. amazon_web_services_aws
124. google_cloud_gcp
125. oracle_cloud
126. ibm
127. servidores_on_premise_nao_utilizamos_cloud
128. cloud_propria
129. cloud_preferida
130. ferramenta_de_bi_utilizada_no_dia_a_dia
131. microsoft_powerbi
132. qlik_view_qlik_sense
133. tableau
134. metabase
135. superset
136. redash
137. looker
138. looker_studiogoogle_data_studio
139. amazon_quicksight
140. alteryx
141. sap_business_objects_sap_analytics
142. oracle_business_intelligence
143. salesforce_einstein_analytics
144. sas_visual_analytics
145. grafana
146. pentaho
147. fazemos_todas_as_analises_utilizando_apenas_excel_ou_planilhas_do_google
148. nao_utilizo_nenhuma_ferramenta_de_bi_no_trabalho
149. utiliza_chatgpt_ou_llms_no_trabalho
150. nao_uso_solucoes_de_ai_generativa_com_foco_em_produtividade
151. uso_solucoes_gratuitas_de_ai_generativa_com_foco_em_produtividade
152. uso_e_pago_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade
153. a_empresa_que_trabalho_paga_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade
154. uso_solucoes_do_tipo_copilot
155. scripts_python
156. sql_&_stored_procedures
157. apache_airflow
158. apache_nifi
159. luigi
160. aws_glue
161. talend
162. stitch
163. fivetran
164. google_dataflow
165. oracle_data_integrator
166. ibm_datastage
167. sap_bw_etl
168. sql_server_integration_services_ssis
169. sas_data_integration
170. qlik_sense
171. knime
172. nao_utilizo_ferramentas_de_etl
173. sua_organizacao_possui_um_data_lake
174. sua_organizacao_possui_um_data_warehouse
175. ano

In [72]:
df_unificado.isna().sum()

id                                          0
idade                                       0
faixa_idade                                 0
genero                                      0
cor_raca_etnia                              0
                                           ..
knime                                       0
nao_utilizo_ferramentas_de_etl              0
sua_organizacao_possui_um_data_lake         0
sua_organizacao_possui_um_data_warehouse    0
ano                                         0
Length: 176, dtype: int64

In [73]:
df.to_excel('silver_unificado_ano.xlsx', index=False)

# **Camada Gold**

## Configurações iniciais

In [74]:
!pip install duckdb -q
import duckdb

In [75]:
conn = duckdb.connect()                      # banco na memória
conn.register('state_of_data', df_unificado) # registra o DataFrame como "tabela"

# VIEW com a tag top_tier (R$ 12k+) — sua melhor amiga daqui pra frente!
conn.execute("""
CREATE OR REPLACE VIEW vw AS
SELECT *,
  CASE WHEN faixa_salarial LIKE '%12.001%' OR faixa_salarial LIKE '%16.001%'
         OR faixa_salarial LIKE '%20.001%' OR faixa_salarial LIKE '%24.001%'
         OR faixa_salarial LIKE '%30.001%' OR faixa_salarial LIKE '%40.001%'
         OR faixa_salarial LIKE 'Acima%'
       THEN 1 ELSE 0 END AS top_tier
FROM state_of_data
""")
print("View pronta! ✔")

View pronta! ✔

In [76]:
# --- Tratamento do unificado (mesma lógica da finalizar_silver) ---
binarias = [c for c in df_unificado.columns if set(df_unificado[c].dropna().unique()) <= {0, 1}]
df_unificado[binarias] = df_unificado[binarias].fillna(0).astype(int)

texto = [c for c in df_unificado.select_dtypes(include='object').columns if c != 'id']
df_unificado[texto] = df_unificado[texto].fillna('Nao_informado')

print("NaNs no unificado:", df_unificado.isnull().sum().sum())  # esperado: 0

NaNs no unificado: 0

## P1 — Estrutura do mercado

In [77]:
# Cargos por ano (%)
conn.sql("""
SELECT ano, atuacao, COUNT(*) AS total,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (PARTITION BY ano), 1) AS pct
FROM vw GROUP BY ano, atuacao
ORDER BY ano, total DESC
""").show()

┌───────┬────────────────────────────────────────┬───────┬────────┐
│  ano  │                atuacao                 │ total │  pct   │
│ int64 │                varchar                 │ int64 │ double │
├───────┼────────────────────────────────────────┼───────┼────────┤
│  2023 │ Análise de Dados                       │  1795 │   33.9 │
│  2023 │ Engenharia de Dados                    │   912 │   17.2 │
│  2023 │ Gestor                                 │   874 │   16.5 │
│  2023 │ Ciência de Dados                       │   748 │   14.1 │
│  2023 │ Outra atuação                          │   526 │    9.9 │
│  2023 │ Buscando oportunidade na área de dados │   438 │    8.3 │
│  2024 │ Análise de Dados                       │  1668 │   32.0 │
│  2024 │ Gestor                                 │  1045 │   20.0 │
│  2024 │ Engenharia de Dados                    │   928 │   17.8 │
│  2024 │ Ciência de Dados                       │   773 │   14.8 │
│  2024 │ Buscando oportunidade na área de dados │   439 │    8.4 │
│  2024 │ Outra atuação                          │   362 │    6.9 │
│  2025 │ Outra atuação                          │   952 │   27.2 │
│  2025 │ Análise de Dados                       │   929 │   26.6 │
│  2025 │ Gestor                                 │   727 │   20.8 │
│  2025 │ Engenharia de Dados                    │   566 │   16.2 │
│  2025 │ Buscando oportunidade na área de dados │   320 │    9.2 │
├───────┴────────────────────────────────────────┴───────┴────────┤
│ 17 rows                                               4 columns │
└─────────────────────────────────────────────────────────────────┘

In [78]:
# Senioridade por ano + Top 10 setores
conn.sql("SELECT ano, nivel, COUNT(*) total FROM vw GROUP BY ano, nivel ORDER BY ano, total DESC").show()
conn.sql("SELECT setor, COUNT(*) total FROM vw GROUP BY setor ORDER BY total DESC LIMIT 10").show()

┌───────┬─────────────────────┬───────┐
│  ano  │        nivel        │ total │
│ int64 │       varchar       │ int64 │
├───────┼─────────────────────┼───────┤
│  2023 │ Nao_informado       │  1436 │
│  2023 │ Sênior              │  1419 │
│  2023 │ Pleno               │  1392 │
│  2023 │ Júnior              │  1046 │
│  2024 │ Sênior              │  1572 │
│  2024 │ Nao_informado       │  1399 │
│  2024 │ Pleno               │  1376 │
│  2024 │ Júnior              │   868 │
│  2025 │ Nao_informado       │   994 │
│  2025 │ Sênior              │   858 │
│  2025 │ Pleno               │   775 │
│  2025 │ Júnior              │   518 │
│  2025 │ Especialista/Staff+ │   349 │
├───────┴─────────────────────┴───────┤
│ 13 rows                   3 columns │
└─────────────────────────────────────┘

┌────────────────────────────────┬───────┐
│             setor              │ total │
│            varchar             │ int64 │
├────────────────────────────────┼───────┤
│ Finanças ou Bancos             │  2560 │
│ Tecnologia/Fábrica de Software │  2361 │
│ Nao_informado                  │  1161 │
│ Área de Consultoria            │  1027 │
│ Varejo                         │   953 │
│ Outra Opção                    │   919 │
│ Indústria                      │   878 │
│ Educação                       │   566 │
│ Área da Saúde                  │   524 │
│ Setor Público                  │   452 │
├────────────────────────────────┴───────┤
│ 10 rows                      2 columns │
└────────────────────────────────────────┘

## P2 — Perfis mais valorizados

In [79]:
# % de Top Tier por cargo e por senioridade
conn.sql("""
SELECT atuacao, COUNT(*) total, ROUND(100.0*SUM(top_tier)/COUNT(*),1) AS pct_top
FROM vw GROUP BY atuacao ORDER BY pct_top DESC
""").show()

┌────────────────────────────────────────┬───────┬─────────┐
│                atuacao                 │ total │ pct_top │
│                varchar                 │ int64 │ double  │
├────────────────────────────────────────┼───────┼─────────┤
│ Gestor                                 │  2646 │    64.7 │
│ Engenharia de Dados                    │  2406 │    36.9 │
│ Ciência de Dados                       │  1521 │    35.4 │
│ Outra atuação                          │  1840 │    26.8 │
│ Análise de Dados                       │  4392 │    13.8 │
│ Buscando oportunidade na área de dados │  1197 │     2.0 │
└────────────────────────────────────────┴───────┴─────────┘

In [80]:
conn.sql("""
SELECT nivel, COUNT(*) total, ROUND(100.0*SUM(top_tier)/COUNT(*),1) AS pct_top
FROM vw GROUP BY nivel ORDER BY pct_top DESC
""").show()

┌─────────────────────┬───────┬─────────┐
│        nivel        │ total │ pct_top │
│       varchar       │ int64 │ double  │
├─────────────────────┼───────┼─────────┤
│ Especialista/Staff+ │   349 │    77.1 │
│ Sênior              │  3849 │    49.9 │
│ Nao_informado       │  3829 │    45.1 │
│ Pleno               │  3543 │     8.9 │
│ Júnior              │  2432 │     1.1 │
└─────────────────────┴───────┴─────────┘

In [81]:
conn.sql("""
SELECT nivel_de_ensino,
       COUNT(*) AS total,
       ROUND(100.0 * SUM(top_tier) / COUNT(*), 1) AS pct_top_tier,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 1) AS pct_mercado
FROM vw
WHERE nivel_de_ensino != 'Nao_informado'
GROUP BY nivel_de_ensino
ORDER BY pct_top_tier DESC
""").show()

┌────────────────────────────┬───────┬──────────────┬─────────────┐
│      nivel_de_ensino       │ total │ pct_top_tier │ pct_mercado │
│          varchar           │ int64 │    double    │   double    │
├────────────────────────────┼───────┼──────────────┼─────────────┤
│ Doutorado ou Phd           │   578 │         49.0 │         4.1 │
│ Mestrado                   │  1781 │         48.4 │        12.7 │
│ Pós-graduação              │  5164 │         36.9 │        36.9 │
│ Prefiro não informar       │    27 │         29.6 │         0.2 │
│ Graduação/Bacharelado      │  4577 │         23.7 │        32.7 │
│ Não tenho graduação formal │   252 │         21.8 │         1.8 │
│ Estudante de Graduação     │  1623 │          3.7 │        11.6 │
└────────────────────────────┴───────┴──────────────┴─────────────┘

## P3 — Diversidade de gênero

In [86]:
# Evolução da participação por gênero
conn.sql("""
SELECT ano, genero, COUNT(*) total,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (PARTITION BY ano), 1) AS pct
FROM vw GROUP BY ano, genero
ORDER BY ano, total DESC
""").show()

┌───────┬──────────────────────┬───────┬────────┐
│  ano  │        genero        │ total │  pct   │
│ int64 │       varchar        │ int64 │ double │
├───────┼──────────────────────┼───────┼────────┤
│  2023 │ Masculino            │  3975 │   75.1 │
│  2023 │ Feminino             │  1293 │   24.4 │
│  2023 │ Prefiro não informar │    16 │    0.3 │
│  2023 │ Outro                │     9 │    0.2 │
│  2024 │ Masculino            │  3967 │   76.1 │
│  2024 │ Feminino             │  1225 │   23.5 │
│  2024 │ Prefiro não informar │    15 │    0.3 │
│  2024 │ Outro                │     8 │    0.2 │
│  2025 │ Masculino            │  2707 │   77.5 │
│  2025 │ Feminino             │   767 │   22.0 │
│  2025 │ Prefiro não informar │    13 │    0.4 │
│  2025 │ Outro                │     7 │    0.2 │
├───────┴──────────────────────┴───────┴────────┤
│ 12 rows                             4 columns │
└───────────────────────────────────────────────┘

In [87]:
# Gap salarial: % Top Tier por gênero
conn.sql("""
SELECT genero, ROUND(100.0*SUM(top_tier)/COUNT(*),1) AS pct_top
FROM vw WHERE genero IN ('Masculino','Feminino')
GROUP BY genero
""").show()

┌───────────┬─────────┐
│  genero   │ pct_top │
│  varchar  │ double  │
├───────────┼─────────┤
│ Feminino  │    24.1 │
│ Masculino │    32.4 │
└───────────┴─────────┘

In [88]:
# Vivência de preconceito (gênero e raça)
conn.sql("""
SELECT genero,
       SUM(experiencia_prejudicada_devido_a_minha_identidade_de_genero) AS preconceito_genero
FROM vw GROUP BY genero ORDER BY preconceito_genero DESC
""").show()

conn.sql("""
SELECT cor_raca_etnia, COUNT(*) total,
       SUM(experiencia_prejudicada_devido_a_minha_cor_raca_etnia) AS preconceito_raca
FROM vw GROUP BY cor_raca_etnia ORDER BY total DESC
""").show()

┌──────────────────────┬────────────────────┐
│        genero        │ preconceito_genero │
│       varchar        │       int128       │
├──────────────────────┼────────────────────┤
│ Feminino             │               1986 │
│ Masculino            │                144 │
│ Prefiro não informar │                 17 │
│ Outro                │                 13 │
└──────────────────────┴────────────────────┘

┌──────────────────────┬───────┬──────────────────┐
│    cor_raca_etnia    │ total │ preconceito_raca │
│       varchar        │ int64 │      int128      │
├──────────────────────┼───────┼──────────────────┤
│ Branca               │  9163 │              164 │
│ Parda                │  3302 │              731 │
│ Preta                │   956 │              533 │
│ Amarela              │   419 │               74 │
│ Prefiro não informar │    99 │               14 │
│ Outra                │    35 │               10 │
│ Indígena             │    26 │                4 │
│ Nao_informado        │     2 │                0 │
└──────────────────────┴───────┴──────────────────┘

## P4 — Tecnologias com maior adoção

In [89]:
conn.sql("""
SELECT ano,
  ROUND(100.0*SUM(python)/COUNT(*),1) AS python,
  ROUND(100.0*SUM(sql)/COUNT(*),1)    AS sql,
  ROUND(100.0*SUM(r)/COUNT(*),1)      AS r,
  ROUND(100.0*SUM(scala)/COUNT(*),1)  AS scala,
  ROUND(100.0*SUM(julia)/COUNT(*),1)  AS julia,
  ROUND(100.0*SUM(rust)/COUNT(*),1)   AS rust,
  ROUND(100.0*SUM("c_c++_c#")/COUNT(*),1) AS c_cpp_csharp,
  ROUND(100.0*SUM(visual_basic_vba)/COUNT(*),1) AS vba,
  ROUND(100.0*SUM(nao_utilizo_nenhuma_linguagem)/COUNT(*),1) AS nenhuma
FROM vw GROUP BY ano ORDER BY ano
""").show()

┌───────┬────────┬────────┬────────┬────────┬────────┬────────┬──────────────┬────────┬─────────┐
│  ano  │ python │  sql   │   r    │ scala  │ julia  │  rust  │ c_cpp_csharp │  vba   │ nenhuma │
│ int64 │ double │ double │ double │ double │ double │ double │    double    │ double │ double  │
├───────┼────────┼────────┼────────┼────────┼────────┼────────┼──────────────┼────────┼─────────┤
│  2023 │   53.4 │   59.6 │    7.7 │    2.5 │    0.2 │    0.1 │          1.3 │    5.4 │     5.8 │
│  2024 │   56.3 │   60.3 │    6.7 │    2.4 │    0.1 │    0.2 │          0.9 │    4.1 │     0.0 │
│  2025 │   55.2 │   50.5 │    9.4 │    2.0 │    0.5 │    1.0 │          1.4 │    0.0 │     0.0 │
└───────┴────────┴────────┴────────┴────────┴────────┴────────┴──────────────┴────────┴─────────┘

In [90]:
# Ranking de bancos
conn.sql("""
SELECT 'PostgreSQL' t, SUM(CASE WHEN postgresql IS NULL THEN 0 ELSE postgresql END) v FROM state_of_data
UNION ALL SELECT 'MySQL', SUM(CASE WHEN mysql IS NULL THEN 0 ELSE mysql END) FROM state_of_data
UNION ALL SELECT 'BigQuery', SUM(CASE WHEN google_bigquery IS NULL THEN 0 ELSE google_bigquery END) FROM state_of_data
UNION ALL SELECT 'Redshift', SUM(CASE WHEN amazon_redshift IS NULL THEN 0 ELSE amazon_redshift END) FROM state_of_data
UNION ALL SELECT 'Snowflake', SUM(CASE WHEN snowflake IS NULL THEN 0 ELSE snowflake END) FROM state_of_data
UNION ALL SELECT 'Databricks', SUM(CASE WHEN databricks IS NULL THEN 0 ELSE databricks END) FROM state_of_data
ORDER BY v DESC
""").show();

# Cloud por ano (%)
conn.sql("""
SELECT ano,
  ROUND(100.0*SUM(CASE WHEN amazon_web_services_aws IS NULL THEN 0 ELSE amazon_web_services_aws END)/COUNT(*),1) AS aws,
  ROUND(100.0*SUM(CASE WHEN azure_microsoft IS NULL THEN 0 ELSE azure_microsoft END)/COUNT(*),1) AS azure,
  ROUND(100.0*SUM(CASE WHEN google_cloud_gcp IS NULL THEN 0 ELSE google_cloud_gcp END)/COUNT(*),1) AS gcp,
  ROUND(100.0*SUM(CASE WHEN servidores_on_premise_nao_utilizamos_cloud IS NULL THEN 0 ELSE servidores_on_premise_nao_utilizamos_cloud END)/COUNT(*),1) AS on_premise
FROM state_of_data GROUP BY ano ORDER BY ano
""").show();

# Ranking de BI
conn.sql("""
SELECT 'PowerBI' t, SUM(CASE WHEN microsoft_powerbi IS NULL THEN 0 ELSE microsoft_powerbi END) v FROM state_of_data
UNION ALL SELECT 'Tableau', SUM(CASE WHEN tableau IS NULL THEN 0 ELSE tableau END) FROM state_of_data
UNION ALL SELECT 'Looker', SUM(CASE WHEN looker IS NULL THEN 0 ELSE looker END) FROM state_of_data
UNION ALL SELECT 'Grafana', SUM(CASE WHEN grafana IS NULL THEN 0 ELSE grafana END) FROM state_of_data
UNION ALL SELECT 'Só Excel', SUM(CASE WHEN fazemos_todas_as_analises_utilizando_apenas_excel_ou_planilhas_do_google IS NULL THEN 0 ELSE fazemos_todas_as_analises_utilizando_apenas_excel_ou_planilhas_do_google END) FROM state_of_data
ORDER BY v DESC
""").show()

┌────────────┬────────┐
│     t      │   v    │
│  varchar   │ int128 │
├────────────┼────────┤
│ PostgreSQL │   2965 │
│ Databricks │   2612 │
│ BigQuery   │   2490 │
│ MySQL      │   2357 │
│ Redshift   │   1008 │
│ Snowflake  │    634 │
└────────────┴────────┘

┌───────┬────────┬────────┬────────┬────────────┐
│  ano  │  aws   │ azure  │  gcp   │ on_premise │
│ int64 │ double │ double │ double │   double   │
├───────┼────────┼────────┼────────┼────────────┤
│  2023 │   20.9 │   28.9 │   21.6 │       11.0 │
│  2024 │   30.4 │   21.2 │   20.1 │        8.9 │
│  2025 │   28.9 │   20.9 │   18.5 │        8.6 │
└───────┴────────┴────────┴────────┴────────────┘

┌──────────┬────────┐
│    t     │   v    │
│ varchar  │ int128 │
├──────────┼────────┤
│ PowerBI  │   5392 │
│ Looker   │   2204 │
│ Tableau  │   1687 │
│ Só Excel │    992 │
│ Grafana  │    749 │
└──────────┴────────┘

## P5 — Adoção de IA e impacto

In [91]:
# Quem paga a conta da IA? (evolução) 💥
conn.sql("""
SELECT ano,
  ROUND(100.0*SUM(nao_uso_solucoes_de_ai_generativa_com_foco_em_produtividade)/COUNT(*),1) AS nao_usa,
  ROUND(100.0*SUM(uso_solucoes_gratuitas_de_ai_generativa_com_foco_em_produtividade)/COUNT(*),1) AS gratis,
  ROUND(100.0*SUM(uso_e_pago_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade)/COUNT(*),1) AS proprio_bolso,
  ROUND(100.0*SUM(a_empresa_que_trabalho_paga_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade)/COUNT(*),1) AS empresa_paga
FROM vw GROUP BY ano ORDER BY ano
""").show()

┌───────┬─────────┬────────┬───────────────┬──────────────┐
│  ano  │ nao_usa │ gratis │ proprio_bolso │ empresa_paga │
│ int64 │ double  │ double │    double     │    double    │
├───────┼─────────┼────────┼───────────────┼──────────────┤
│  2023 │    14.1 │   45.4 │           4.9 │          4.5 │
│  2024 │     4.5 │   37.3 │          10.8 │         13.4 │
│  2025 │     1.3 │   18.4 │          16.2 │         25.5 │
└───────┴─────────┴────────┴───────────────┴──────────────┘

In [92]:
# IA nas empresas + barreiras de adoção
conn.sql("""
SELECT ano,
  ROUND(100.0*SUM(colaboradores_usando_ai_generativa_de_forma_independente_e_descentralizada)/COUNT(*),1) AS uso_independente,
  ROUND(100.0*SUM(direcionamento_centralizado_do_uso_de_ai_generativa)/COUNT(*),1) AS centralizado,
  ROUND(100.0*SUM(desenvolvedores_utilizando_copilots)/COUNT(*),1) AS copilots,
  ROUND(100.0*SUM(ia_generativa_e_llms_nao_e_prioridade)/COUNT(*),1) AS nao_prioridade
FROM vw GROUP BY ano ORDER BY ano
""").show()

┌───────┬──────────────────┬──────────────┬──────────┬────────────────┐
│  ano  │ uso_independente │ centralizado │ copilots │ nao_prioridade │
│ int64 │      double      │    double    │  double  │     double     │
├───────┼──────────────────┼──────────────┼──────────┼────────────────┤
│  2023 │              5.7 │          2.1 │      3.5 │            3.4 │
│  2024 │              7.6 │          4.4 │      6.9 │            2.3 │
│  2025 │              8.9 │          6.8 │      7.6 │            1.2 │
└───────┴──────────────────┴──────────────┴──────────┴────────────────┘

In [93]:
conn.sql("""
SELECT 'Dados não prontos' t, SUM(COALESCE(dados_da_empresa_nao_estao_prontos_para_uso_de_ia_generativa, 0)) v FROM state_of_data
UNION ALL SELECT 'Segurança/privacidade', SUM(COALESCE(preocupacoes_com_seguranca_e_privacidade_de_dados, 0)) FROM state_of_data
UNION ALL SELECT 'ROI não comprovado', SUM(COALESCE(retorno_sobre_investimento_roi_nao_comprovado_de_ia_generativa, 0)) FROM state_of_data
UNION ALL SELECT 'Direção não vê valor', SUM(COALESCE(alta_direcao_da_empresa_nao_ve_valor_ou_nao_ve_como_prioridade, 0)) FROM state_of_data
UNION ALL SELECT 'Falta de expertise', SUM(COALESCE(falta_de_expertise_ou_falta_de_recursos, 0)) FROM state_of_data
UNION ALL SELECT 'Alucinação', SUM(COALESCE(falta_de_confiabilidade_das_saidas_alucinacao_dos_modelos, 0)) FROM state_of_data
ORDER BY v DESC
""").show()

┌───────────────────────┬────────┐
│           t           │   v    │
│        varchar        │ int128 │
├───────────────────────┼────────┤
│ Falta de expertise    │    842 │
│ Dados não prontos     │    757 │
│ Segurança/privacidade │    739 │
│ ROI não comprovado    │    542 │
│ Alucinação            │    402 │
│ Direção não vê valor  │    221 │
└───────────────────────┴────────┘

## P6 — Regiões, senioridade e modelo de trabalho

In [94]:
# O Mito do Remoto: qual modelo paga mais? 💥
conn.sql("""
SELECT atualmente_qual_a_sua_forma_de_trabalho AS modelo,
       COUNT(*) total, ROUND(100.0*SUM(top_tier)/COUNT(*),1) AS pct_top
FROM vw GROUP BY modelo ORDER BY pct_top DESC
""").show()

# Top Tier por região
conn.sql("""
SELECT regiao_onde_mora, COUNT(*) total, ROUND(100.0*SUM(top_tier)/COUNT(*),1) AS pct_top
FROM vw GROUP BY regiao_onde_mora ORDER BY pct_top DESC
""").show()

┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────┬─────────┐
│                                                     modelo                                                     │ total │ pct_top │
│                                                    varchar                                                     │ int64 │ double  │
├────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────┼─────────┤
│ Modelo híbrido flexível (o funcionário tem liberdade para escolher quando estar no escritório presencialmente) │  2601 │    39.3 │
│ Modelo 100% remoto                                                                                             │  5703 │    38.1 │
│ Modelo híbrido com dias fixos de trabalho presencial                                                           │  2285 │    30.8 │
│ Modelo 100% presencial                                                                                         │  2252 │    16.2 │
│ Nao_informado                                                                                                  │  1161 │     0.0 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────┴─────────┘

┌──────────────────┬───────┬─────────┐
│ regiao_onde_mora │ total │ pct_top │
│     varchar      │ int64 │ double  │
├──────────────────┼───────┼─────────┤
│ Nao_informado    │   391 │    52.7 │
│ Sudeste          │  8474 │    32.9 │
│ Centro-oeste     │   907 │    27.0 │
│ Sul              │  2531 │    26.9 │
│ Nordeste         │  1504 │    20.4 │
│ Norte            │   195 │    16.9 │
└──────────────────┴───────┴─────────┘

In [95]:
# Realidade x Desejo (modelo atual vs ideal)
conn.sql("SELECT atualmente_qual_a_sua_forma_de_trabalho atual, COUNT(*) total FROM vw GROUP BY atual ORDER BY total DESC").show()
conn.sql("SELECT qual_a_forma_de_trabalho_ideal_para_voce ideal, COUNT(*) total FROM vw GROUP BY ideal ORDER BY total DESC").show()

┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────┐
│                                                     atual                                                      │ total │
│                                                    varchar                                                     │ int64 │
├────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────┤
│ Modelo 100% remoto                                                                                             │  5703 │
│ Modelo híbrido flexível (o funcionário tem liberdade para escolher quando estar no escritório presencialmente) │  2601 │
│ Modelo híbrido com dias fixos de trabalho presencial                                                           │  2285 │
│ Modelo 100% presencial                                                                                         │  2252 │
│ Nao_informado                                                                                                  │  1161 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────┘

┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────┐
│                                                     ideal                                                      │ total │
│                                                    varchar                                                     │ int64 │
├────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────┤
│ Modelo 100% remoto                                                                                             │  5720 │
│ Modelo híbrido flexível (o funcionário tem liberdade para escolher quando estar no escritório presencialmente) │  5633 │
│ Modelo híbrido com dias fixos de trabalho presencial                                                           │  1241 │
│ Nao_informado                                                                                                  │  1161 │
│ Modelo 100% presencial                                                                                         │   247 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────┘

In [96]:
col_atual = 'atualmente_qual_a_sua_forma_de_trabalho'
col_ideal = 'qual_a_forma_de_trabalho_ideal_para_voce'

mapa_forma = {
    'Modelo híbrido flexível (o funcionário tem liberdade para escolher quando estar no escritório presencialmente)': 'Híbrido flexível',
    'Modelo 100% remoto': '100% remoto',
    'Modelo híbrido com dias fixos de trabalho presencial': 'Híbrido fixo',
    'Modelo 100% presencial': '100% presencial',
}

pedacos = []
for df in [df_2023, df_2024, df_2025]:
    if col_atual in df.columns and col_ideal in df.columns:
        a = df[[col_atual]].copy(); a.columns = ['modelo']; a['situacao'] = 'Atual'
        i = df[[col_ideal]].copy(); i.columns = ['modelo']; i['situacao'] = 'Ideal'
        pedacos += [a, i]

atual_vs_ideal = pd.concat(pedacos, ignore_index=True)
atual_vs_ideal = atual_vs_ideal[atual_vs_ideal['modelo'].notna()]
atual_vs_ideal['modelo'] = atual_vs_ideal['modelo'].map(mapa_forma).fillna(atual_vs_ideal['modelo'])

print(atual_vs_ideal.groupby(['modelo', 'situacao']).size())  # prova real!
atual_vs_ideal.to_parquet('atual_vs_ideal.parquet', index=False)

modelo            situacao
100% presencial   Atual       2252
                  Ideal        247
100% remoto       Atual       5705
                  Ideal       5722
Híbrido fixo      Atual       2285
                  Ideal       1241
Híbrido flexível  Atual       2602
                  Ideal       5634
dtype: int64

## P7 — Oportunidades e desafios p/ empresas

In [97]:
conn.sql("""
SELECT 'Contratar talentos' t, SUM(COALESCE(a_contratar_novos_talentos, 0)) v FROM vw
UNION ALL SELECT 'Reter talentos', SUM(COALESCE(b_reter_talentos, 0)) FROM vw
UNION ALL SELECT 'Convencer a investir', SUM(COALESCE(c_convencer_a_empresa_a_aumentar_os_investimentos_na_area_de_dados, 0)) FROM vw
UNION ALL SELECT 'Gerar valor p/ negócio', SUM(COALESCE(h_conseguir_gerar_valor_para_as_areas_de_negocios_atraves_de_estudos_e_experimentos, 0)) FROM vw
UNION ALL SELECT 'Provar ROI', SUM(COALESCE(garantir_retorno_do_investimento_roi_em_projetos_de_dados, 0)) FROM vw
ORDER BY v DESC
""").show()

┌────────────────────────┬────────┐
│           t            │   v    │
│        varchar         │ int128 │
├────────────────────────┼────────┤
│ Gerar valor p/ negócio │    704 │
│ Provar ROI             │    549 │
│ Convencer a investir   │    418 │
│ Contratar talentos     │    369 │
│ Reter talentos         │    343 │
└────────────────────────┴────────┘

In [98]:
conn.sql("""
SELECT 'Remuneração' t, SUM(COALESCE(remuneracao_salario, 0)) v FROM vw
UNION ALL SELECT 'Flexibilidade remota', SUM(COALESCE(flexibilidade_de_trabalho_remoto, 0)) FROM vw
UNION ALL SELECT 'Plano de carreira', SUM(COALESCE(plano_de_carreira_e_oportunidades_de_crescimento_profissional, 0)) FROM vw
UNION ALL SELECT 'Aprendizado', SUM(COALESCE(oportunidade_de_aprendizado_e_trabalhar_com_referencias_na_area, 0)) FROM vw
UNION ALL SELECT 'Maturidade em dados', SUM(COALESCE(maturidade_da_empresa_em_termos_de_tecnologia_e_dados, 0)) FROM vw
UNION ALL SELECT 'Propósito', SUM(COALESCE(proposito_do_trabalho_e_da_empresa, 0)) FROM vw
ORDER BY v DESC
""").show()

┌──────────────────────┬────────┐
│          t           │   v    │
│       varchar        │ int128 │
├──────────────────────┼────────┤
│ Remuneração          │  10470 │
│ Flexibilidade remota │   7390 │
│ Plano de carreira    │   4172 │
│ Aprendizado          │   3103 │
│ Propósito            │   2025 │
│ Maturidade em dados  │   1574 │
└──────────────────────┴────────┘

In [99]:
# Maturidade das empresas (Data Lake/DW por ano)
conn.sql("""
SELECT ano,
  ROUND(100.0*SUM(sua_organizacao_possui_um_data_lake)/COUNT(*),1) AS pct_lake,
  ROUND(100.0*SUM(sua_organizacao_possui_um_data_warehouse)/COUNT(*),1) AS pct_dw
FROM vw GROUP BY ano ORDER BY ano
""").show()

┌───────┬──────────┬────────┐
│  ano  │ pct_lake │ pct_dw │
│ int64 │  double  │ double │
├───────┼──────────┼────────┤
│  2023 │     14.2 │   14.3 │
│  2024 │     14.6 │   14.2 │
│  2025 │     13.2 │   12.9 │
└───────┴──────────┴────────┘

## codigos extras para o **Power BI**

In [101]:
colunas_desafios = {
    'a_contratar_novos_talentos': 'Contratar talentos',
    'b_reter_talentos': 'Reter talentos',
    'c_convencer_a_empresa_a_aumentar_os_investimentos_na_area_de_dados': 'Convencer a investir',
    'h_conseguir_gerar_valor_para_as_areas_de_negocios_atraves_de_estudos_e_experimentos': 'Gerar valor p/ negócio',
    'garantir_retorno_do_investimento_roi_em_projetos_de_dados': 'Provar ROI',
}

resultados = []
for col, nome in colunas_desafios.items():
    total = 0
    for df in [df_2023, df_2024, df_2025]:
        if col in df.columns:
            serie = df[col]
            if isinstance(serie, pd.DataFrame):   # coluna duplicada → pega a 1ª
                serie = serie.iloc[:, 0]
            total += pd.to_numeric(serie, errors='coerce').fillna(0).sum()
    resultados.append({'desafio': nome, 'contagem': int(total)})

df_desafios = pd.DataFrame(resultados).sort_values('contagem', ascending=False)
df_desafios.to_csv('desafios_dados.csv', index=False)
print(df_desafios)

                  desafio  contagem
3  Gerar valor p/ negócio       437
4              Provar ROI       350
2    Convencer a investir       270
0      Contratar talentos       227
1          Reter talentos       227

In [102]:
# ===== TABELA 2: VALORES PROFISSIONAIS  =====
valores_busca = {
    'Remuneração': ['remuneração', 'remuneracao', 'salário', 'salario', 'benefício'],
    'Flexibilidade remota': ['flexibilidade', 'remoto', 'híbrido'],
    'Plano de carreira': ['plano de carreira', 'crescimento', 'oportunidade'],
    'Aprendizado': ['aprendizado', 'referência', 'capacitação'],
    'Maturidade em dados': ['maturidade', 'tecnologia', 'dados'],
    'Propósito': ['propósito', 'proposito'],
}

# Primeiro, identifica a coluna CERTA de valores
candidatas = [c for c in df_2025.columns
              if any(p in c.lower() for p in ['valoriza', 'importante', 'prioridade', 'motiva'])]
print('Colunas candidatas:', candidatas[:5])  # me manda isso!

Colunas candidatas: ['ai_generativa_e_uma_prioridade_em_sua_empresa', 'ia_generativa_e_llms_nao_e_prioridade', 'alta_direcao_da_empresa_nao_ve_valor_ou_nao_ve_como_prioridade', 'ia_generativa_e_llms_nao_e_prioridade__1']

In [103]:
def soma_col(df, col):
    serie = df[col]
    if isinstance(serie, pd.DataFrame):          # duplicada! → pega a maior soma
        return max(pd.to_numeric(serie.iloc[:, i], errors='coerce').fillna(0).sum()
                   for i in range(serie.shape[1]))
    return pd.to_numeric(serie, errors='coerce').fillna(0).sum()

colunas_valores = {
    'remuneracao_salario': 'Remuneração',
    'flexibilidade_de_trabalho_remoto': 'Flexibilidade remota',
    'plano_de_carreira_e_oportunidades_de_crescimento_profissional': 'Plano de carreira',
    'oportunidade_de_aprendizado_e_trabalhar_com_referencias_na_area': 'Aprendizado',
    'maturidade_da_empresa_em_termos_de_tecnologia_e_dados': 'Maturidade em dados',
    'proposito_do_trabalho_e_da_empresa': 'Propósito',
}

resultados = []
for nome_col, nome_bonito in colunas_valores.items():
    total = sum(soma_col(df, nome_col) for df in [df_2023, df_2024, df_2025]
                if nome_col in df.columns)
    resultados.append({'valor': nome_bonito, 'contagem': int(total)})

df_valores = pd.DataFrame(resultados).sort_values('contagem', ascending=False)
df_valores.to_csv('valores_profissionais.csv', index=False)
print(df_valores)

                  valor  contagem
0           Remuneração     10473
1  Flexibilidade remota      7393
2     Plano de carreira      4172
3           Aprendizado      3105
5             Propósito      2025
4   Maturidade em dados      1574

In [104]:
linhas = []
for ano, df in [(2023, df_2023), (2024, df_2024), (2025, df_2025)]:
    lake = pd.to_numeric(df['sua_organizacao_possui_um_data_lake'], errors='coerce')
    dw = pd.to_numeric(df['sua_organizacao_possui_um_data_warehouse'], errors='coerce')
    linhas.append({
        'ano': ano,
        'pct_lake': round(100.0 * lake.sum() / len(df), 1),
        'pct_dw': round(100.0 * dw.sum() / len(df), 1),
    })

maturidade_dw = pd.DataFrame(linhas)
maturidade_dw.to_csv('maturidade_lake_dw.csv', index=False)
print(maturidade_dw)

    ano  pct_lake  pct_dw
0  2023      14.2    14.3
1  2024      14.6    14.2
2  2025      13.2    12.9

questao7

In [105]:
print('=== MATURIDADE (2025) ===')
print(df_2025['maturidade_da_empresa_em_termos_de_tecnologia_e_dados'].value_counts(dropna=False))

=== MATURIDADE (2025) ===
maturidade_da_empresa_em_termos_de_tecnologia_e_dados
0.0    2878
1.0     350
NaN     267
Name: count, dtype: int64

In [106]:
colunas_barreiras = [
    'retorno_sobre_investimento_roi_nao_comprovado_de_ia_generativa',
    'dados_da_empresa_nao_estao_prontos_para_uso_de_ia_generativa',
]

nomes_bar = {
    'retorno_sobre_investimento_roi_nao_comprovado_de_ia_generativa': 'ROI não comprovado',
    'dados_da_empresa_nao_estao_prontos_para_uso_de_ia_generativa': 'Dados não prontos',
}

dfs = []
for ano, df in [(2023, df_2023), (2024, df_2024), (2025, df_2025)]:
    cols = [c for c in colunas_barreiras if c in df.columns]
    t = df[['id'] + cols].copy()
    t['ano'] = ano
    t = t.melt(id_vars=['id', 'ano'], value_vars=cols,
               var_name='barreira', value_name='marca')
    t = t[t['marca'] == 1]
    dfs.append(t)

barreiras_ia = pd.concat(dfs, ignore_index=True)
barreiras_ia['barreira'] = barreiras_ia['barreira'].map(nomes_bar)
barreiras_ia.to_parquet('barreiras_ia.parquet', index=False)
print(barreiras_ia['barreira'].value_counts())

barreira
Dados não prontos     757
ROI não comprovado    542
Name: count, dtype: int64

In [107]:
print('=== MATURIDADE ===')
print(df_2025['maturidade_da_empresa_em_termos_de_tecnologia_e_dados'].value_counts(dropna=False))

print('=== FALTA ===')
print(df_2025['falta_de_maturidade_analitica_na_empresa'].value_counts(dropna=False))

=== MATURIDADE ===
maturidade_da_empresa_em_termos_de_tecnologia_e_dados
0.0    2878
1.0     350
NaN     267
Name: count, dtype: int64
=== FALTA ===
falta_de_maturidade_analitica_na_empresa
NaN    2493
0.0     743
1.0     259
Name: count, dtype: int64

In [108]:
# 1) BARREIRA no pódio de desafios
colunas_barreiras = [
    'retorno_sobre_investimento_roi_nao_comprovado_de_ia_generativa',
    'dados_da_empresa_nao_estao_prontos_para_uso_de_ia_generativa',
    'falta_de_maturidade_analitica_na_empresa',                      #
]
nomes_bar = {
    'retorno_sobre_investimento_roi_nao_comprovado_de_ia_generativa': 'ROI não comprovado',
    'dados_da_empresa_nao_estao_prontos_para_uso_de_ia_generativa': 'Dados não prontos',
    'falta_de_maturidade_analitica_na_empresa': 'Falta de maturidade analítica',  #
}

dfs = []
for ano, df in [(2023, df_2023), (2024, df_2024), (2025, df_2025)]:
    cols = [c for c in colunas_barreiras if c in df.columns]
    t = df[['id'] + cols].copy()
    t['ano'] = ano
    t = t.melt(id_vars=['id', 'ano'], value_vars=cols,
               var_name='barreira', value_name='marca')
    t = t[t['marca'] == 1]
    dfs.append(t)

barreiras_ia1 = pd.concat(dfs, ignore_index=True)
barreiras_ia1['barreira'] = barreiras_ia1['barreira'].map(nomes_bar)
barreiras_ia1.to_parquet('barreiras_ia1.parquet', index=False)
print(barreiras_ia1['barreira'].value_counts())

barreira
Falta de maturidade analítica    1219
Dados não prontos                 757
ROI não comprovado                542
Name: count, dtype: int64

### Questao 5

In [109]:
palavras = ['inteligencia', 'llm', 'chatgpt', 'copilot', 'generativa', 'ia_', 'impacto', 'automat']

for nome, df in [('2023', df_2023), ('2024', df_2024), ('2025', df_2025)]:
    achadas = [c for c in df.columns if any(p in c.lower() for p in palavras)]
    print(f'--- {nome}: {len(achadas)} colunas de IA ---')
    for c in achadas:
        print('  ', c)

--- 2023: 56 colunas de IA ---
   experiencia_profissional_prejudicada
   nao_acredito_que_minha_experiencia_profissional_seja_afetada
   experiencia_prejudicada_devido_a_minha_cor_raca_etnia
   experiencia_prejudicada_devido_a_minha_identidade_de_genero
   experiencia_prejudicada_devido_ao_fato_de_ser_pcd
   quanto_tempo_de_experiencia_na_area_de_dados_voce_tem
   quanto_tempo_de_experiencia_na_area_de_ti_engenharia_de_software_voce_teve_antes_de_comecar_a_trabalhar_na_area_de_dados
   gostaria_de_trabalhar_em_em_outra_area_de_atuacao
   gostaria_de_receber_mais_beneficios
   maturidade_da_empresa_em_termos_de_tecnologia_e_dados
   engenharia_de_dados_data_engineer
   sou_gestor_da_equipe_responsavel_pela_engenharia_de_dados_e_por_manter_o_data_lake_da_empresa_como_fonte_unica_dos_dados,_garantindo_a_qualidade_e_confiabilidade_da_informacao.
   sou_gestor_da_equipe_responsavel_por_iniciativas_e_projetos_envolvendo_inteligencia_artificial_e_machine_learning.
   ai_generativa_e_uma_prioridade_em_sua_empresa
   tipos_de_uso_de_ai_generativa_e_llms_na_empresa
   colaboradores_usando_ai_generativa_de_forma_independente_e_descentralizada
   direcionamento_centralizado_do_uso_de_ai_generativa
   desenvolvedores_utilizando_copilots
   ai_generativa_e_llms_para_melhorar_produtos_externos
   ai_generativa_e_llms_para_melhorar_produtos_internos_para_os_colaboradores
   ia_generativa_e_llms_como_principal_frente_do_negocio
   ia_generativa_e_llms_nao_e_prioridade
   nao_sei_opinar_sobre_o_uso_de_ia_generativa_e_llms_na_empresa
   motivos_que_levam_a_empresa_a_nao_usar_ai_genrativa_e_llms
   retorno_sobre_investimento_roi_nao_comprovado_de_ia_generativa
   dados_da_empresa_nao_estao_prontos_para_uso_de_ia_generativa
   mesmo_que_esse_nao_seja_seu_cargo_formal,_voce_considera_que_sua_atuacao_no_dia_a_dia,_reflete_alguma_das_opcoes_listadas_abaixo
   ferramenta_de_bi_utilizada_no_dia_a_dia
   qual_o_tipo_de_uso_de_ai_generativa_e_llms_na_empresa
   colaboradores_usando_ai_generativa_de_forma_independente_e_descentralizada__1
   direcionamento_centralizado_do_uso_de_ai_generativa__1
   desenvolvedores_utilizando_copilots__1
   ai_generativa_e_llms_para_melhorar_produtos_externos_para_os_clientes_finais
   ai_generativa_e_llms_para_melhorar_produtos_internos_para_os_colaboradores__1
   ia_generativa_e_llms_como_principal_frente_do_negocio__1
   ia_generativa_e_llms_nao_e_prioridade__1
   nao_sei_opinar_sobre_o_uso_de_ia_generativa_e_llms_na_empresa__1
   utiliza_chatgpt_ou_llms_no_trabalho
   nao_uso_solucoes_de_ai_generativa_com_foco_em_produtividade
   uso_solucoes_gratuitas_de_ai_generativa_com_foco_em_produtividade
   uso_e_pago_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade
   a_empresa_que_trabalho_paga_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade
   uso_solucoes_do_tipo_copilot
   nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.
   qual_tecnologia_utilizada_como_plataforma_do_data_lake
   qual_tecnologia_utilizada_como_plataforma_do_data_warehouse
   nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.__1
   nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.__2
   sua_empresa_utiliza_alguma_das_ferramentas_listadas_para_dar_mais_autonomia_em_analise_de_dados_para_as_areas_de_negocio
   nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.__3
   quais_das_opcoes_abaixo_fazem_parte_da_sua_rotina_no_trabalho_atual_com_ciencia_de_dados
   treino_e_aplico_llms_para_solucionar_problemas_de_negocio.
   utilizo_metodos_estatisticos_classicos_testes_de_hipotese,_analise_multivariada,_sobrevivencia,_dados_longitudinais,_inferencia_estatistica_para_analisar_dados
   utilizo_llms_para_solucionar_problemas_de_negocio
   quais_dessas_tecnologias_fazem_parte_do_seu_dia_a_dia_como_cientista_de_dados
   treinando_e_aplicando_llms_para_solucionar_problemas_de_negocio.
--- 2024: 59 colunas de IA ---
   experiencia_profissional_prejudicada
   nao_acredito_que_minha_experiencia_profissional_seja_afetada
   experiencia_prejudicada_devido_a_minha_cor_raca_etnia
   experiencia_prejudicada_devido_a_minha_identidade_de_genero
   experiencia_prejudicada_devido_ao_fato_de_ser_pcd
   quanto_tempo_de_experiencia_na_area_de_dados_voce_tem
   quanto_tempo_de_experiencia_na_area_de_ti_engenharia_de_software_voce_teve_antes_de_comecar_a_trabalhar_na_area_de_dados
   gostaria_de_receber_mais_beneficios
   gostaria_de_trabalhar_em_em_outra_area_de_atuacao
   maturidade_da_empresa_em_termos_de_tecnologia_e_dados
   engenharia_de_dados_data_engineer
   gestor_da_equipe_de_engenharia_de_dados
   gestor_da_equipe_de_inteligencia_artificial_e_machine_learning
   ai_generativa_e_uma_prioridade_em_sua_empresa
   tipo_de_uso_de_ai_generativa_e_llm_na_empresa
   colaboradores_usando_ai_generativa_de_forma_independente_e_descentralizada
   direcionamento_centralizado_do_uso_de_ai_generativa
   desenvolvedores_utilizando_copilots
   ai_generativa_e_llms_para_melhorar_produtos_externos
   ai_generativa_e_llms_para_melhorar_produtos_internos_para_os_colaboradores
   ia_generativa_e_llms_como_principal_frente_do_negocio
   ia_generativa_e_llms_nao_e_prioridade
   nao_sei_opinar_sobre_o_uso_de_ia_generativa_e_llms_na_empresa
   motivos_para_nao_usar_ai_generativa_e_llm
   retorno_sobre_investimento_roi_nao_comprovado_de_ia_generativa
   dados_da_empresa_nao_estao_prontos_para_uso_de_ia_generativa
   fontes_de_dados_dia_a_dia
   linguagem_de_programacao_dia_a_dia
   banco_de_dados_dia_a_dia
   cloud_dia_a_dia
   ferramenta_de_bi_utilizada_no_dia_a_dia
   tipo_de_uso_de_ai_generativa_e_llm_na_empresa__1
   colaboradores_usando_ai_generativa_de_forma_independente_e_descentralizada__1
   direcionamento_centralizado_do_uso_de_ai_generativa__1
   desenvolvedores_utilizando_copilots__1
   ai_generativa_e_llms_para_melhorar_produtos_externos_para_os_clientes_finais__1
   ai_generativa_e_llms_para_melhorar_produtos_internos_para_os_colaboradores__1
   ia_generativa_e_llms_como_principal_frente_do_negocio__1
   ia_generativa_e_llms_nao_e_prioridade__1
   nao_sei_opinar_sobre_o_uso_de_ia_generativa_e_llms_na_empresa__1
   utiliza_chatgpt_ou_llms_no_trabalho
   nao_uso_solucoes_de_ai_generativa_com_foco_em_produtividade
   uso_solucoes_gratuitas_de_ai_generativa_com_foco_em_produtividade
   uso_e_pago_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade
   a_empresa_que_trabalho_paga_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade
   uso_solucoes_do_tipo_copilot
   experiencia_em_processos_seletivos
   nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.
   tecnologia_data_lake
   tecnologia_data_warehouse
   ferramentas_de_qualidade_de_dados_dia_a_dia
   nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.__1
   nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.__2
   ferramentas_autonomia_area_de_negocios
   nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.__3
   treino_e_aplico_llms_para_solucionar_problemas_de_negocio.
   utilizo_metodos_estatisticos_classicos_testes_de_hipotese,_analise_multivariada,_sobrevivencia,_dados_longitudinais,_inferencia_estatistica_para_analisar_dados.
   utilizo_llms_para_solucionar_problemas_de_negocio.
   treinando_e_aplicando_llms_para_solucionar_problemas_de_negocio.
--- 2025: 59 colunas de IA ---
   experiencia_profissional_prejudicada
   nao_acredito_que_minha_experiencia_profissional_seja_afetada
   experiencia_prejudicada_devido_a_minha_cor_raca_etnia
   experiencia_prejudicada_devido_a_minha_identidade_de_genero
   experiencia_prejudicada_devido_ao_fato_de_ser_pcd
   quanto_tempo_de_experiencia_na_area_de_dados_voce_tem
   quanto_tempo_de_experiencia_na_area_de_ti_engenharia_de_software_voce_teve_antes_de_comecar_a_trabalhar_na_area_de_dados
   gostaria_de_receber_mais_beneficios
   gostaria_de_trabalhar_em_em_outra_area_de_atuacao
   maturidade_da_empresa_em_termos_de_tecnologia_e_dados
   engenharia_de_dados_data_engineer
   gestor_da_equipe_de_engenharia_de_dados
   gestor_da_equipe_de_inteligencia_artificial_e_machine_learning
   ai_generativa_e_uma_prioridade_em_sua_empresa
   tipo_de_uso_de_ai_generativa_e_llm_na_empresa
   colaboradores_usando_ai_generativa_de_forma_independente_e_descentralizada
   direcionamento_centralizado_do_uso_de_ai_generativa
   desenvolvedores_utilizando_copilots
   ai_generativa_e_llms_para_melhorar_produtos_externos
   ai_generativa_e_llms_para_melhorar_produtos_internos_para_os_colaboradores
   ia_generativa_e_llms_como_principal_frente_do_negocio
   ia_generativa_e_llms_nao_e_prioridade
   nao_sei_opinar_sobre_o_uso_de_ia_generativa_e_llms_na_empresa
   empresa_esta_conseguindo_ter_bons_resultados_com_llms
   motivos_para_nao_usar_ai_generativa_e_llm
   retorno_sobre_investimento_roi_nao_comprovado_de_ia_generativa
   dados_da_empresa_nao_estao_prontos_para_uso_de_ia_generativa
   fontes_de_dados_dia_a_dia
   banco_de_dados_dia_a_dia
   cloud_dia_a_dia
   ferramenta_de_bi_utilizada_no_dia_a_dia
   tipo_de_uso_de_ai_generativa_e_llm_na_empresa__1
   colaboradores_usando_ai_generativa_de_forma_independente_e_descentralizada__1
   direcionamento_centralizado_do_uso_de_ai_generativa__1
   desenvolvedores_utilizando_copilots__1
   ai_generativa_e_llms_para_melhorar_produtos_externos_para_os_clientes_finais__1
   ai_generativa_e_llms_para_melhorar_produtos_internos_para_os_colaboradores__1
   ia_generativa_e_llms_como_principal_frente_do_negocio__1
   ia_generativa_e_llms_nao_e_prioridade__1
   nao_sei_opinar_sobre_o_uso_de_ia_generativa_e_llms_na_empresa__1
   utiliza_chatgpt_ou_llms_no_trabalho
   nao_uso_solucoes_de_ai_generativa_com_foco_em_produtividade
   uso_solucoes_gratuitas_de_ai_generativa_com_foco_em_produtividade
   uso_e_pago_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade
   a_empresa_que_trabalho_paga_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade
   uso_solucoes_do_tipo_copilot
   experiencia_em_processos_seletivos
   nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.
   tecnologia_data_lake
   tecnologia_data_warehouse
   ferramentas_de_qualidade_de_dados_dia_a_dia
   nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.__1
   nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.__2
   ferramentas_autonomia_area_de_negocios
   nenhuma_das_opcoes_listadas_refletem_meu_dia_a_dia.__3
   treino_e_aplico_llms_para_solucionar_problemas_de_negocio.
   utilizo_metodos_estatisticos_classicos_testes_de_hipotese,_analise_multivariada,_sobrevivencia,_dados_longitudinais,_inferencia_estatistica_para_analisar_dados.
   utilizo_llms_para_solucionar_problemas_de_negocio.
   treinando_e_aplicando_llms_para_solucionar_problemas_de_negocio.

In [110]:
def grupo_ia(v):
    return 'Usa IA no trabalho' if 'Utilizo' in str(v) else 'Não usa / não informou'

for df in [df_2023, df_2024, df_2025]:
    df['uso_ia_grupo'] = df['utiliza_chatgpt_ou_llms_no_trabalho'].apply(grupo_ia)

In [111]:
def grupo_prioridade(row):
    if row['ai_generativa_e_uma_prioridade_em_sua_empresa'] == 1:
        return 'IA É prioridade na empresa'
    if row['ia_generativa_e_llms_nao_e_prioridade'] == 1:
        return 'IA NÃO é prioridade'
    return 'Outro cenário'

for df in [df_2023, df_2024, df_2025]:
    df['prioridade_grupo'] = df.apply(grupo_prioridade, axis=1)

In [112]:
def grupo_resultado(v):
    v = str(v).lower()
    if v.startswith('sim'):
        return 'Sim, bons resultados'
    if v.startswith('em partes'):
        return 'Em partes / piloto'
    if 'ainda não' in v:
        return 'Ainda não começou'
    if v.startswith('não'):
        return 'Não, sem resultados'
    return 'Sem resposta'

for df in [df_2023, df_2024, df_2025]:
    if 'empresa_esta_conseguindo_ter_bons_resultados_com_llms' in df.columns:
        df['resultado_grupo'] = df['empresa_esta_conseguindo_ter_bons_resultados_com_llms'].apply(grupo_resultado)

In [113]:
# cria o ano nos dfs
df_2023['ano'] = 2023
df_2024['ano'] = 2024
df_2025['ano'] = 2025

#  monta o extras
colunas_ia = [
    'ano', 'id', 'uso_ia_grupo', 'prioridade_grupo', 'resultado_grupo',
    'utiliza_chatgpt_ou_llms_no_trabalho',
    'ai_generativa_e_uma_prioridade_em_sua_empresa',
    'ia_generativa_e_llms_nao_e_prioridade',
    'nao_uso_solucoes_de_ai_generativa_com_foco_em_produtividade',
    'uso_solucoes_gratuitas_de_ai_generativa_com_foco_em_produtividade',
    'uso_e_pago_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade',
    'a_empresa_que_trabalho_paga_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade',
    'uso_solucoes_do_tipo_copilot',
    'desenvolvedores_utilizando_copilots',
    'empresa_esta_conseguindo_ter_bons_resultados_com_llms'
]

extras_para_5 = pd.concat([
    df_2023[[c for c in colunas_ia if c in df_2023.columns]],
    df_2024[[c for c in colunas_ia if c in df_2024.columns]],
    df_2025[[c for c in colunas_ia if c in df_2025.columns]]
], ignore_index=True)

# salvar para usar no BI
extras_para_5.to_csv('extras_para_5.csv', index=False)

# lê o arquivo
pd.read_csv('extras_para_5.csv').head()

,ano,id,uso_ia_grupo,prioridade_grupo,utiliza_chatgpt_ou_llms_no_trabalho,ai_generativa_e_uma_prioridade_em_sua_empresa,ia_generativa_e_llms_nao_e_prioridade,nao_uso_solucoes_de_ai_generativa_com_foco_em_produtividade,uso_solucoes_gratuitas_de_ai_generativa_com_foco_em_produtividade,uso_e_pago_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade,a_empresa_que_trabalho_paga_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade,uso_solucoes_do_tipo_copilot,desenvolvedores_utilizando_copilots,resultado_grupo,empresa_esta_conseguindo_ter_bons_resultados_com_llms
0,2023,001b2d1qtli8t9z7oqgdhj001b2d4i0g,Não usa / não informou,Outro cenário,Não utilizo nenhum tipo de solução de IA Gener...,NaN,NaN,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1,2023,0026aa3fwd78u0026asg7456tfkjg2cs,Usa IA no trabalho,Outro cenário,Utilizo soluções pagas de AI Generativa (como ...,NaN,NaN,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN
2,2023,00r21rb9pusd1b0v7ew00r21rw3dy69w,Usa IA no trabalho,Outro cenário,Utilizo apenas soluções gratuitas (como por ex...,NaN,NaN,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN
3,2023,00urm3jf2cek12w6ygue00urm3jzd17j,Não usa / não informou,Outro cenário,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023,00v0az4g792svil00vn6y1kfm9hq8vy9,Usa IA no trabalho,Outro cenário,Utilizo apenas soluções gratuitas (como por ex...,NaN,NaN,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN

In [114]:
# Define as colunas binárias de formas de uso
colunas_uso = [
    'uso_solucoes_gratuitas_de_ai_generativa_com_foco_em_produtividade',
    'uso_e_pago_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade',
    'a_empresa_que_trabalho_paga_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade',
    'uso_solucoes_do_tipo_copilot',
    'desenvolvedores_utilizando_copilots',
    'nao_uso_solucoes_de_ai_generativa_com_foco_em_produtividade'
]

# Dicionário de nomes (pra legenda do gráfico)
nomes = {
    'uso_solucoes_gratuitas_de_ai_generativa_com_foco_em_produtividade': 'Soluções gratuitas',
    'uso_e_pago_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade': 'Pago do próprio bolso',
    'a_empresa_que_trabalho_paga_pelas_solucoes_de_ai_generativa_com_foco_em_produtividade': 'Empresa paga',
    'uso_solucoes_do_tipo_copilot': 'Copilot (pessoal)',
    'desenvolvedores_utilizando_copilots': 'Copilot (devs)',
    'nao_uso_solucoes_de_ai_generativa_com_foco_em_produtividade': 'Não uso IA'
}

#  Processa cada ano separadamente (porque nem todas as colunas existem em todos os anos)
dfs_processados = []
for ano, df in [(2023, df_2023), (2024, df_2024), (2025, df_2025)]:
    # Seleciona só as colunas que existem nesse ano
    cols_disponiveis = [c for c in colunas_uso if c in df.columns]
    df_temp = df[['id'] + cols_disponiveis].copy()
    df_temp['ano'] = ano

    # "Derrete" (melt = unpivot do pandas)
    df_long = df_temp.melt(
        id_vars=['id', 'ano'],
        value_vars=cols_disponiveis,
        var_name='forma_uso',
        value_name='usa'
    )

    # Filtra só quem respondeu 1 (usa essa forma)
    df_long = df_long[df_long['usa'] == 1]
    dfs_processados.append(df_long)

# Junta tudo
formas_uso_ia = pd.concat(dfs_processados, ignore_index=True)

#  Aplica os nomes
formas_uso_ia['forma_uso'] = formas_uso_ia['forma_uso'].map(nomes)

# Salvar
formas_uso_ia.to_csv('formas_uso_ia.csv', index=False)

print('Pronto! Tabela com', len(formas_uso_ia), 'linhas')
formas_uso_ia.head()

Pronto! Tabela com 11971 linhas

                                 id   ano           forma_uso  usa
0  00r21rb9pusd1b0v7ew00r21rw3dy69w  2023  Soluções gratuitas  1.0
1  00v0az4g792svil00vn6y1kfm9hq8vy9  2023  Soluções gratuitas  1.0
2  015qqbrh4rr015qje9gvkbsb7ti1n5df  2023  Soluções gratuitas  1.0
3  01810y9hweneb018to8t1p8ubyn1o04m  2023  Soluções gratuitas  1.0
4  01zusm1faol2k2601zlthh05cj7iqyit  2023  Soluções gratuitas  1.0

In [115]:
# 1) Recarrega a base que o Power BI usa
df = pd.read_parquet('silver_unificado.parquet')   # ← ajusta o nome se precisar

# 2) Encurta pelos PEDAÇOS da frase (na ordem certa!)
def forma_curta(v):
    v = str(v).lower()
    if 'flex' in v:                      # "híbrido Flexível..."
        return 'Híbrido flexível'
    if 'remoto' in v:                    # "100% remoto"
        return '100% remoto'
    if 'híbrido' in v or 'hibrido' in v or 'fixos' in v:
        return 'Híbrido fixo'
    if 'presencial' in v:
        return '100% presencial'
    return 'Não informado'

# 3) Cria a coluna curta
df['forma_trabalho_curta'] = df['atualmente_qual_a_sua_forma_de_trabalho'].apply(forma_curta)

# 4) Olhar a coluna
print(df['forma_trabalho_curta'].value_counts())

# 5) Salva em PARQUET (PAraPower BI!)
df.to_parquet('dados_powerbi_completo.parquet', index=False)
print('Salvo!')

forma_trabalho_curta
100% remoto         5703
Híbrido flexível    2601
Híbrido fixo        2285
100% presencial     2252
Não informado       1161
Name: count, dtype: int64
Salvo!